# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Full name of the user')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('api_key', models.TextField(blank=True, db_index=True, default='', verbose_name='API key')),
                ('is_active', models.BooleanField(default=True, verbose_name='The user is allowed to login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date of user creation')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Date of last succesfull login')),
            ],
        ),
    ]
