# Generated by Django 3.2.4 on 2021-06-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_selection', '0004_cleanup'),
        ('web_account', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
