'''
Django settings for SVO project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
'''

from pathlib import Path
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
SETTINGS_DIR = Path(__file__).resolve().parent

BASE_DIR = SETTINGS_DIR.parent.parent

# Application definition
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'tastypie',
	'tastypie_swagger',
	'api',
	'dataset',
	'metadata',
	'data_selection'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': 'solarnet2',
		'USER': 'solarnet',
		'HOST': 'pgsql-as.oma.be',
		'PORT': '5432',
		'CONN_MAX_AGE': 10 * 60
		# 'PASSWORD': '*****', # Do not put password here, instead write it in the .pgpass file of the user running django
	}
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Try to read the secret_key from the file or generate one and write it
SECRET_KEY_FILE = SETTINGS_DIR / 'secret_key.txt'

try:
	with open(SECRET_KEY_FILE, 'rt') as file:
		SECRET_KEY = file.read().strip()
except FileNotFoundError:
	SECRET_KEY = get_random_secret_key()
	with open(SECRET_KEY_FILE, 'wt') as file:
		file.write(SECRET_KEY)

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = True


# Specify ISO time format with timezone
DATETIME_FORMAT = 'Y-m-d H:i:s e' # e.g. 1999-12-31 00:00:00 UTC
DATE_FORMAT = 'Y-m-d' # 31 Dec 1999
TIME_FORMAT = 'H:i:s e' # 00:00:00 UTC

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

### Logging
# Log all message for loggers that start with 'apps.', e.g.:
# import logging
# logger = logging.getLogger('apps.' + __name__)
# logger.info('Hello %s', 'Benjamin')

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'loggers': {
		'apps': {
			'handlers': ['console'],
			'level': 'ERROR',
			'propagate': False,
		},
		'django': {
			'handlers': ['file'],
			'level': 'INFO',
			'propagate': True,
		},

	},
	'handlers': {
		'console': {
			'class': 'logging.StreamHandler',
			'level': 'DEBUG',
			'formatter': 'console',
		},
		'file': {
			'class': 'logging.FileHandler',
			'level': 'DEBUG',
			'formatter': 'file',
			'filename': '/var/log/django.log',
		},
	},
	'formatters': {
		'console': {
			'format': '[{asctime}] [{levelname}] [{module}] {message}',
			'datefmt': '%d/%b/%Y %H:%M:%S',
			'style': '{',
		},
		'file': {
			'format': '[{asctime}] [{levelname}] [{name}] {message}',
			'datefmt': '%Y-%m-%d %H:%M:%S',
			'style': '{',
		}
	},
}

## Project specific settings

# The minimum value for the estimated_count of the metadata models queries, below that value the actual count is used instead
MIN_ESTIMATED_COUNT = 1000

# The characters that should not appear in a data location file_path
FILE_PATH_FORBIDDEN_CHARACTERS = {
	'\\': 'Backslash',
	':': 'Colon',
	'*': 'Asterisk',
	'?': 'QuestionMark',
	'"': 'QuotationMark',
	'\'': 'Apostrophe',
	'<': 'Less-Than Sign',
	'>': 'Greater-Than Sign',
	'|': 'Vertical Line',
	'\r': 'Carriage Return',
	'\n': 'New Line',
	'\0': 'Null',
}

# The maximum size of a ZIP archives generated for a data selection (in bytes)
ZIP_ARCHIVE_MAX_SIZE = 100*1024*1024 # 100 MB

# The maximum size of a file inside a ZIP archives generated for a data selection (in bytes)
ZIP_ARCHIVE_MAX_FILE_SIZE = 100*1024*1024 # 100 MB

# The name of the file in a ZIP archive listing files that could not be included
ZIP_ARCHIVE_MISSING_FILE_NAME = 'missing_files.txt'

# The code to warn the user that the ZIP archive was truncated because it is too large
ZIP_ARCHIVE_TRUNCATED_WARNING = 'Truncated'

# The base URL of the FTP server
FTP_BASE_URL = 'ftp://solarnet.oma.be/data_selection/'

# The maximum size of a file that can be downloaded via FTP (in bytes)
FTP_MAX_FILE_SIZE = 100*1024*1024 # 100 MB
