from api import svo_api
from metadata.resources import (
	AiaLevel1Resource,
	AiaLevel2Resource,
	AiaLevel15Resource,
	ChromisResource,
	ChrotelLevel1Resource,
	CrispResource,
	EitLevel0Resource,
	EitSynopticResource,
	EuiLevel1Resource,
	EuiLevel2Resource,
	EuviLevel0Resource,
	GaiaDemResource,
	GrisLevel1Resource,
	HmiMagnetogramLevel15Resource,
	HmiMagnetogramResource,
	IbisResource,
	LarsLevel1Resource,
	LyraLevel2Resource,
	LyraLevel3Resource,
	RosaResource,
	SwapLevel1Resource,
	TagResource,
	UsetCalciumiiKLevel1Resource,
	UsetHAlphaLevel1Resource,
	UsetWhiteLightLevel1Resource,
	XrtResource,
	ZimpolSpectrographGregorResource,
	ZimpolSpectrographIrsolResource,
)

# Register the metadata resources
svo_api.register(TagResource())
svo_api.register(AiaLevel1Resource())
svo_api.register(AiaLevel15Resource())
svo_api.register(AiaLevel2Resource())
svo_api.register(ChromisResource())
svo_api.register(ChrotelLevel1Resource())
svo_api.register(CrispResource())
svo_api.register(EitLevel0Resource())
svo_api.register(EitSynopticResource())
svo_api.register(EuiLevel1Resource())
svo_api.register(EuiLevel2Resource())
svo_api.register(EuviLevel0Resource())
svo_api.register(GaiaDemResource())
svo_api.register(GrisLevel1Resource())
svo_api.register(HmiMagnetogramResource())
svo_api.register(HmiMagnetogramLevel15Resource())
svo_api.register(IbisResource())
svo_api.register(LarsLevel1Resource())
svo_api.register(LyraLevel2Resource())
svo_api.register(LyraLevel3Resource())
svo_api.register(RosaResource())
svo_api.register(SwapLevel1Resource())
svo_api.register(UsetCalciumiiKLevel1Resource())
svo_api.register(UsetHAlphaLevel1Resource())
svo_api.register(UsetWhiteLightLevel1Resource())
svo_api.register(ZimpolSpectrographGregorResource())
svo_api.register(ZimpolSpectrographIrsolResource())
