#!/usr/bin/python

import sys, os
import logging
import argparse
import pandas
import slumber

SERVER_ADDRESS = "http://solarnet.oma.be/api"

# Start point of the script
if __name__ == "__main__":
	
	# Get the arguments
	parser = argparse.ArgumentParser(description='Ingest keyword attributes into the SDA.')
	parser.add_argument('--debug', '-d', default=False, action='store_true', help='Set the logging level to debug')
	parser.add_argument('--dataset', '-D', required=True, help='The dataset id. Required.')
	parser.add_argument('username', help='Your SDA username')
	parser.add_argument('password', help='Your SDA password')
	parser.add_argument('filename', help='The path to a csv file as generated by the extract_keywords script')
	
	args = parser.parse_args()
	if args.debug:
		logging.basicConfig(level = logging.DEBUG, format='%(levelname)-8s: %(message)s')
	else:
		logging.basicConfig(level = logging.INFO, format='%(levelname)-8s: %(message)s')
	
	API = slumber.API(SERVER_ADDRESS, auth = (args.username, args.password))
	api = API.v1(args.dataset + "_keyword")
	
	csv = pandas.read_csv(args.filename, skipinitialspace = True)
	
	for index, row in csv.iterrows():
		logging.debug("Ingesting row %s", row)
		api.post(row.to_dict())
		
