from .base import Tag
from .aia_lev1 import AiaLev1
from .chrotel import Chrotel
from .eit import Eit
from .hmi_magnetogram import HmiMagnetogram
from .swap_lev1 import SwapLev1
from .themis import Themis
from .xrt import Xrt
from .ibis import Ibis
from .gris_lev1 import GrisLev1
from .rosa import Rosa