from django.db import models

from .base_metadata import BaseMetadata

__all__ = ['Chrotel']

class Chrotel(BaseMetadata):
	'''Model for the metadata of dataset ChroTel'''
	
	class Meta(BaseMetadata.Meta):
		verbose_name = 'ChroTel'
	
	azimuth = models.FloatField(verbose_name = 'AZIMUTH', help_text='telescope azimuth', blank=True, null=True)
	bkpltemp = models.FloatField(verbose_name = 'BKPLTEMP', help_text='Camera backplane temperature', blank=True, null=True)
	bscale = models.FloatField(verbose_name = 'BSCALE', help_text='', blank=True, null=True)
	bunit = models.TextField(verbose_name = 'BUNIT', help_text='Data is encoded in A/D units', blank=True, null=True)
	bzero = models.IntegerField(verbose_name = 'BZERO', help_text='Data is Unsigned Integer', blank=True, null=True)
	ccdgain = models.FloatField(verbose_name = 'CCDGAIN', help_text='CCD gain', blank=True, null=True)
	ccdpress = models.FloatField(verbose_name = 'CCDPRESS', help_text='CCD chamber pressure', blank=True, null=True)
	ccdtemp = models.FloatField(verbose_name = 'CCDTEMP', help_text='CCD temperature', blank=True, null=True)
	cdelt1 = models.FloatField(verbose_name = 'CDELT1', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt1a = models.FloatField(verbose_name = 'CDELT1A', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt1b = models.FloatField(verbose_name = 'CDELT1B', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt1c = models.FloatField(verbose_name = 'CDELT1C', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt1d = models.FloatField(verbose_name = 'CDELT1D', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt1e = models.FloatField(verbose_name = 'CDELT1E', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt1f = models.FloatField(verbose_name = 'CDELT1F', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt1g = models.FloatField(verbose_name = 'CDELT1G', help_text='Plate scale X-axis at CRPIX1', blank=True, null=True)
	cdelt2 = models.FloatField(verbose_name = 'CDELT2', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdelt2a = models.FloatField(verbose_name = 'CDELT2A', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdelt2b = models.FloatField(verbose_name = 'CDELT2B', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdelt2c = models.FloatField(verbose_name = 'CDELT2C', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdelt2d = models.FloatField(verbose_name = 'CDELT2D', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdelt2e = models.FloatField(verbose_name = 'CDELT2E', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdelt2f = models.FloatField(verbose_name = 'CDELT2F', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdelt2g = models.FloatField(verbose_name = 'CDELT2G', help_text='Plate scale Y-axis at CRPIX2', blank=True, null=True)
	cdrcrev = models.TextField(verbose_name = 'CDRCREV', help_text='source code revision', blank=True, null=True)
	cdrcvers = models.TextField(verbose_name = 'CDRCVERS', help_text='data reduction code version', blank=True, null=True)
	content = models.TextField(verbose_name = 'CONTENT', help_text='', blank=True, null=True)
	creator = models.TextField(verbose_name = 'CREATOR', help_text='chrotel data reduction code', blank=True, null=True)
	crln_obs = models.FloatField(verbose_name = 'CRLN_OBS', help_text='sub-observer carrington longitude', blank=True, null=True)
	crpix1 = models.FloatField(verbose_name = 'CRPIX1', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix1a = models.FloatField(verbose_name = 'CRPIX1A', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix1b = models.FloatField(verbose_name = 'CRPIX1B', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix1c = models.FloatField(verbose_name = 'CRPIX1C', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix1d = models.FloatField(verbose_name = 'CRPIX1D', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix1e = models.FloatField(verbose_name = 'CRPIX1E', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix1f = models.FloatField(verbose_name = 'CRPIX1F', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix1g = models.FloatField(verbose_name = 'CRPIX1G', help_text='Reference pixel X-axis (Disk center)', blank=True, null=True)
	crpix2 = models.FloatField(verbose_name = 'CRPIX2', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crpix2a = models.FloatField(verbose_name = 'CRPIX2A', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crpix2b = models.FloatField(verbose_name = 'CRPIX2B', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crpix2c = models.FloatField(verbose_name = 'CRPIX2C', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crpix2d = models.FloatField(verbose_name = 'CRPIX2D', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crpix2e = models.FloatField(verbose_name = 'CRPIX2E', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crpix2f = models.FloatField(verbose_name = 'CRPIX2F', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crpix2g = models.FloatField(verbose_name = 'CRPIX2G', help_text='Reference pixel Y-axis (Disk center)', blank=True, null=True)
	crval1 = models.FloatField(verbose_name = 'CRVAL1', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval1a = models.FloatField(verbose_name = 'CRVAL1A', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval1b = models.FloatField(verbose_name = 'CRVAL1B', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval1c = models.FloatField(verbose_name = 'CRVAL1C', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval1d = models.FloatField(verbose_name = 'CRVAL1D', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval1e = models.FloatField(verbose_name = 'CRVAL1E', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval1f = models.FloatField(verbose_name = 'CRVAL1F', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval1g = models.FloatField(verbose_name = 'CRVAL1G', help_text='X Coordinate at reference pixel', blank=True, null=True)
	crval2 = models.FloatField(verbose_name = 'CRVAL2', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	crval2a = models.FloatField(verbose_name = 'CRVAL2A', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	crval2b = models.FloatField(verbose_name = 'CRVAL2B', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	crval2c = models.FloatField(verbose_name = 'CRVAL2C', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	crval2d = models.FloatField(verbose_name = 'CRVAL2D', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	crval2e = models.FloatField(verbose_name = 'CRVAL2E', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	crval2f = models.FloatField(verbose_name = 'CRVAL2F', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	crval2g = models.FloatField(verbose_name = 'CRVAL2G', help_text='Y Coordinate at reference pixel', blank=True, null=True)
	ctype1 = models.TextField(verbose_name = 'CTYPE1', help_text='Label X-axis', blank=True, null=True)
	ctype1a = models.TextField(verbose_name = 'CTYPE1A', help_text='Label X-axis', blank=True, null=True)
	ctype1b = models.TextField(verbose_name = 'CTYPE1B', help_text='Label X-axis', blank=True, null=True)
	ctype1c = models.TextField(verbose_name = 'CTYPE1C', help_text='Label X-axis', blank=True, null=True)
	ctype1d = models.TextField(verbose_name = 'CTYPE1D', help_text='Label X-axis', blank=True, null=True)
	ctype1e = models.TextField(verbose_name = 'CTYPE1E', help_text='Label X-axis', blank=True, null=True)
	ctype1f = models.TextField(verbose_name = 'CTYPE1F', help_text='Label X-axis', blank=True, null=True)
	ctype1g = models.TextField(verbose_name = 'CTYPE1G', help_text='Label X-axis', blank=True, null=True)
	ctype2 = models.TextField(verbose_name = 'CTYPE2', help_text='Label Y-axis', blank=True, null=True)
	ctype2a = models.TextField(verbose_name = 'CTYPE2A', help_text='Label Y-axis', blank=True, null=True)
	ctype2b = models.TextField(verbose_name = 'CTYPE2B', help_text='Label Y-axis', blank=True, null=True)
	ctype2c = models.TextField(verbose_name = 'CTYPE2C', help_text='Label Y-axis', blank=True, null=True)
	ctype2d = models.TextField(verbose_name = 'CTYPE2D', help_text='Label Y-axis', blank=True, null=True)
	ctype2e = models.TextField(verbose_name = 'CTYPE2E', help_text='Label Y-axis', blank=True, null=True)
	ctype2f = models.TextField(verbose_name = 'CTYPE2F', help_text='Label Y-axis', blank=True, null=True)
	ctype2g = models.TextField(verbose_name = 'CTYPE2G', help_text='Label Y-axis', blank=True, null=True)
	cunit1 = models.TextField(verbose_name = 'CUNIT1', help_text='Unit X-axis', blank=True, null=True)
	cunit1a = models.TextField(verbose_name = 'CUNIT1A', help_text='Unit X-axis', blank=True, null=True)
	cunit1b = models.TextField(verbose_name = 'CUNIT1B', help_text='Unit X-axis', blank=True, null=True)
	cunit1c = models.TextField(verbose_name = 'CUNIT1C', help_text='Unit X-axis', blank=True, null=True)
	cunit1d = models.TextField(verbose_name = 'CUNIT1D', help_text='Unit X-axis', blank=True, null=True)
	cunit1e = models.TextField(verbose_name = 'CUNIT1E', help_text='Unit X-axis', blank=True, null=True)
	cunit1f = models.TextField(verbose_name = 'CUNIT1F', help_text='Unit X-axis', blank=True, null=True)
	cunit1g = models.TextField(verbose_name = 'CUNIT1G', help_text='Unit X-axis', blank=True, null=True)
	cunit2 = models.TextField(verbose_name = 'CUNIT2', help_text='Unit Y-axis', blank=True, null=True)
	cunit2a = models.TextField(verbose_name = 'CUNIT2A', help_text='Unit Y-axis', blank=True, null=True)
	cunit2b = models.TextField(verbose_name = 'CUNIT2B', help_text='Unit Y-axis', blank=True, null=True)
	cunit2c = models.TextField(verbose_name = 'CUNIT2C', help_text='Unit Y-axis', blank=True, null=True)
	cunit2d = models.TextField(verbose_name = 'CUNIT2D', help_text='Unit Y-axis', blank=True, null=True)
	cunit2e = models.TextField(verbose_name = 'CUNIT2E', help_text='Unit Y-axis', blank=True, null=True)
	cunit2f = models.TextField(verbose_name = 'CUNIT2F', help_text='Unit Y-axis', blank=True, null=True)
	cunit2g = models.TextField(verbose_name = 'CUNIT2G', help_text='Unit Y-axis', blank=True, null=True)
	darkfile = models.TextField(verbose_name = 'DARKFILE', help_text='darkframe used for calibration', blank=True, null=True)
	datamax = models.IntegerField(verbose_name = 'DATAMAX', help_text='max data value', blank=True, null=True)
	datamin = models.IntegerField(verbose_name = 'DATAMIN', help_text='min data value', blank=True, null=True)
	datavers = models.TextField(verbose_name = 'DATAVERS', help_text='data format version', blank=True, null=True)
	date = models.DateTimeField(verbose_name = 'DATE', help_text='UTC time of FITS file creation', blank=True, null=True)
	date_obs = models.DateTimeField(verbose_name = 'DATE-OBS', help_text='UTC time of observation', blank=True, null=True)
	diskmax = models.IntegerField(verbose_name = 'DISKMAX', help_text='max data value on solar disk', blank=True, null=True)
	diskmean = models.FloatField(verbose_name = 'DISKMEAN', help_text='mean data value on solar disk', blank=True, null=True)
	diskmedn = models.FloatField(verbose_name = 'DISKMEDN', help_text='median data value on solar disk', blank=True, null=True)
	diskmin = models.IntegerField(verbose_name = 'DISKMIN', help_text='min data value on solar disk', blank=True, null=True)
	diskrms = models.FloatField(verbose_name = 'DISKRMS', help_text='standard deviation of on-disk data values', blank=True, null=True)
	dsun_obs = models.FloatField(verbose_name = 'DSUN_OBS', help_text='distance to Sun', blank=True, null=True)
	elevat = models.FloatField(verbose_name = 'ELEVAT', help_text='telescope elevation', blank=True, null=True)
	exptime = models.FloatField(verbose_name = 'EXPTIME', help_text='exposure time', blank=True, null=True)
	filename = models.TextField(verbose_name = 'FILENAME', help_text='name of this data set', blank=True, null=True)
	filter = models.TextField(verbose_name = 'FILTER', help_text='The used ChroTel bandpass filter', blank=True, null=True)
	filtfwhm = models.FloatField(verbose_name = 'FILTFWHM', help_text='filter passband FWHM', blank=True, null=True)
	fitsfile = models.TextField(verbose_name = 'FITSFILE', help_text='name of this data set', blank=True, null=True)
	flatdark = models.TextField(verbose_name = 'FLATDARK', help_text='flatfield dark used for calibration', blank=True, null=True)
	flatfile = models.TextField(verbose_name = 'FLATFILE', help_text='flatfield used for calibration', blank=True, null=True)
	glocked = models.IntegerField(verbose_name = 'GLOCKED', help_text='true if guiding system was locked on sun', blank=True, null=True)
	hgln_obs = models.FloatField(verbose_name = 'HGLN_OBS', help_text='sub-observer stonyhurst longitude', blank=True, null=True)
	hglt_obs = models.FloatField(verbose_name = 'HGLT_OBS', help_text='sub-observer heliographic latitude', blank=True, null=True)
	img_rot = models.FloatField(verbose_name = 'IMG_ROT', help_text='image rotation wrt geocentric north', blank=True, null=True)
	instrume = models.TextField(verbose_name = 'INSTRUME', help_text='', blank=True, null=True)
	level = models.TextField(verbose_name = 'LEVEL', help_text='processing level of this dataset', blank=True, null=True)
	naxis = models.IntegerField(verbose_name = 'NAXIS', help_text='', blank=True, null=True)
	naxis1 = models.IntegerField(verbose_name = 'NAXIS1', help_text='', blank=True, null=True)
	naxis2 = models.IntegerField(verbose_name = 'NAXIS2', help_text='', blank=True, null=True)
	naxis3 = models.IntegerField(verbose_name = 'NAXIS3', help_text='', blank=True, null=True)
	object = models.TextField(verbose_name = 'OBJECT', help_text='', blank=True, null=True)
	obsnfile = models.TextField(verbose_name = 'OBSNFILE', help_text='raw observation data', blank=True, null=True)
	origin = models.TextField(verbose_name = 'ORIGIN', help_text='Kiepenheuer-Institut fuer Sonnenphysik', blank=True, null=True)
	pc1_1 = models.FloatField(verbose_name = 'PC1_1', help_text='', blank=True, null=True)
	pc1_1a = models.FloatField(verbose_name = 'PC1_1A', help_text='', blank=True, null=True)
	pc1_1b = models.FloatField(verbose_name = 'PC1_1B', help_text='', blank=True, null=True)
	pc1_1c = models.FloatField(verbose_name = 'PC1_1C', help_text='', blank=True, null=True)
	pc1_1d = models.FloatField(verbose_name = 'PC1_1D', help_text='', blank=True, null=True)
	pc1_1e = models.FloatField(verbose_name = 'PC1_1E', help_text='', blank=True, null=True)
	pc1_1f = models.FloatField(verbose_name = 'PC1_1F', help_text='', blank=True, null=True)
	pc1_1g = models.FloatField(verbose_name = 'PC1_1G', help_text='', blank=True, null=True)
	pc1_2 = models.FloatField(verbose_name = 'PC1_2', help_text='', blank=True, null=True)
	pc1_2a = models.FloatField(verbose_name = 'PC1_2A', help_text='', blank=True, null=True)
	pc1_2b = models.FloatField(verbose_name = 'PC1_2B', help_text='', blank=True, null=True)
	pc1_2c = models.FloatField(verbose_name = 'PC1_2C', help_text='', blank=True, null=True)
	pc1_2d = models.FloatField(verbose_name = 'PC1_2D', help_text='', blank=True, null=True)
	pc1_2e = models.FloatField(verbose_name = 'PC1_2E', help_text='', blank=True, null=True)
	pc1_2f = models.FloatField(verbose_name = 'PC1_2F', help_text='', blank=True, null=True)
	pc1_2g = models.FloatField(verbose_name = 'PC1_2G', help_text='', blank=True, null=True)
	pc2_1 = models.FloatField(verbose_name = 'PC2_1', help_text='', blank=True, null=True)
	pc2_1a = models.FloatField(verbose_name = 'PC2_1A', help_text='', blank=True, null=True)
	pc2_1b = models.FloatField(verbose_name = 'PC2_1B', help_text='', blank=True, null=True)
	pc2_1c = models.FloatField(verbose_name = 'PC2_1C', help_text='', blank=True, null=True)
	pc2_1d = models.FloatField(verbose_name = 'PC2_1D', help_text='', blank=True, null=True)
	pc2_1e = models.FloatField(verbose_name = 'PC2_1E', help_text='', blank=True, null=True)
	pc2_1f = models.FloatField(verbose_name = 'PC2_1F', help_text='', blank=True, null=True)
	pc2_1g = models.FloatField(verbose_name = 'PC2_1G', help_text='', blank=True, null=True)
	pc2_2 = models.FloatField(verbose_name = 'PC2_2', help_text='', blank=True, null=True)
	pc2_2a = models.FloatField(verbose_name = 'PC2_2A', help_text='', blank=True, null=True)
	pc2_2b = models.FloatField(verbose_name = 'PC2_2B', help_text='', blank=True, null=True)
	pc2_2c = models.FloatField(verbose_name = 'PC2_2C', help_text='', blank=True, null=True)
	pc2_2d = models.FloatField(verbose_name = 'PC2_2D', help_text='', blank=True, null=True)
	pc2_2e = models.FloatField(verbose_name = 'PC2_2E', help_text='', blank=True, null=True)
	pc2_2f = models.FloatField(verbose_name = 'PC2_2F', help_text='', blank=True, null=True)
	pc2_2g = models.FloatField(verbose_name = 'PC2_2G', help_text='', blank=True, null=True)
	pressure = models.FloatField(verbose_name = 'PRESSURE', help_text='CCD chamber pressure', blank=True, null=True)
	psd_ll = models.FloatField(verbose_name = 'PSD_LL', help_text='PSD light level', blank=True, null=True)
	realtime = models.IntegerField(verbose_name = 'REALTIME', help_text='true if data was processed in realtime mode', blank=True, null=True)
	rot_offs = models.FloatField(verbose_name = 'ROT_OFFS', help_text='filter specific offset to IMG_ROT', blank=True, null=True)
	rsun_obs = models.FloatField(verbose_name = 'RSUN_OBS', help_text='apparent radius of solar disk', blank=True, null=True)
	rsun_ref = models.IntegerField(verbose_name = 'RSUN_REF', help_text='reference radius of the Sun', blank=True, null=True)
	solar_b0 = models.FloatField(verbose_name = 'SOLAR_B0', help_text='Solar B0 angle', blank=True, null=True)
	solar_p0 = models.FloatField(verbose_name = 'SOLAR_P0', help_text='Solar P0 angle', blank=True, null=True)
	telescop = models.TextField(verbose_name = 'TELESCOP', help_text='Chromospheric Telescope', blank=True, null=True)
	temp_bpt = models.FloatField(verbose_name = 'TEMP_BPT', help_text='Camera backplate temperature', blank=True, null=True)
	temp_ccd = models.FloatField(verbose_name = 'TEMP_CCD', help_text='CCD temperature', blank=True, null=True)
	tt_rms = models.FloatField(verbose_name = 'TT_RMS', help_text='Tip-Tilt motion', blank=True, null=True)
	wavelnth = models.FloatField(verbose_name = 'WAVELNTH', help_text='filter center wavelength', blank=True, null=True)
	wcsname = models.TextField(verbose_name = 'WCSNAME', help_text='', blank=True, null=True)
	wcsnamea = models.TextField(verbose_name = 'WCSNAMEA', help_text='', blank=True, null=True)
	wcsnameb = models.TextField(verbose_name = 'WCSNAMEB', help_text='', blank=True, null=True)
	wcsnamec = models.TextField(verbose_name = 'WCSNAMEC', help_text='', blank=True, null=True)
	wcsnamed = models.TextField(verbose_name = 'WCSNAMED', help_text='', blank=True, null=True)
	wcsnamee = models.TextField(verbose_name = 'WCSNAMEE', help_text='', blank=True, null=True)
	wcsnamef = models.TextField(verbose_name = 'WCSNAMEF', help_text='', blank=True, null=True)
	wcsnameg = models.TextField(verbose_name = 'WCSNAMEG', help_text='', blank=True, null=True)
