# Generated by command write_metadata_files version 2
import datetime

from django.db import models

from .base_metadata import BaseMetadata

__all__ = ['Co5BoldIrsol']


class Co5BoldIrsol(BaseMetadata):
	'''Model for the metadata of dataset CO5BOLD@IRSOL'''
	
	# Constant values corresponding to the keyword with constant_value
	
	class Meta(BaseMetadata.Meta):
		verbose_name = 'CO5BOLD@IRSOL metadata'
		verbose_name_plural = 'CO5BOLD@IRSOL metadata'
	
	cadence = models.FloatField(verbose_name = 'CADENCE', help_text='mean gap between published snapshots [s]', blank=True, null=True)
	cdelt1 = models.FloatField(verbose_name = 'CDELT1', help_text='step per pixel', blank=True, null=True)
	cdelt2 = models.FloatField(verbose_name = 'CDELT2', help_text='step per pixel', blank=True, null=True)
	cdelt3 = models.FloatField(verbose_name = 'CDELT3', help_text='step per pixel', blank=True, null=True)
	comment = models.TextField(verbose_name = 'COMMENT', help_text='', blank=True, null=True)
	creator = models.TextField(verbose_name = 'CREATOR', help_text='', blank=True, null=True)
	crpix1 = models.BigIntegerField(verbose_name = 'CRPIX1', help_text='reference pixel', blank=True, null=True)
	crpix2 = models.BigIntegerField(verbose_name = 'CRPIX2', help_text='reference pixel', blank=True, null=True)
	crpix3 = models.BigIntegerField(verbose_name = 'CRPIX3', help_text='reference pixel', blank=True, null=True)
	crval1 = models.FloatField(verbose_name = 'CRVAL1', help_text='value at reference pixel', blank=True, null=True)
	crval2 = models.FloatField(verbose_name = 'CRVAL2', help_text='value at reference pixel', blank=True, null=True)
	crval3 = models.FloatField(verbose_name = 'CRVAL3', help_text='value at reference pixel', blank=True, null=True)
	ctype1 = models.TextField(verbose_name = 'CTYPE1', help_text='axis 1 = x', blank=True, null=True)
	ctype2 = models.TextField(verbose_name = 'CTYPE2', help_text='axis 2 = y', blank=True, null=True)
	ctype3 = models.TextField(verbose_name = 'CTYPE3', help_text='axis 3 = z', blank=True, null=True)
	cunit1 = models.TextField(verbose_name = 'CUNIT1', help_text='unit of x', blank=True, null=True)
	cunit2 = models.TextField(verbose_name = 'CUNIT2', help_text='unit of y', blank=True, null=True)
	cunit3 = models.TextField(verbose_name = 'CUNIT3', help_text='unit of z', blank=True, null=True)
	elapsed = models.FloatField(verbose_name = 'ELAPSED', help_text='simulated time since snapshot 0 [s]', blank=True, null=True)
	extend = models.BooleanField(verbose_name = 'EXTEND', help_text='', blank=True, null=True)
	extname = models.TextField(verbose_name = 'EXTNAME', help_text='', blank=True, null=True)
	naxis = models.BigIntegerField(verbose_name = 'NAXIS', help_text='number of array dimensions', blank=True, null=True)
	observer = models.TextField(verbose_name = 'OBSERVER', help_text='', blank=True, null=True)
	obsrvtry = models.TextField(verbose_name = 'OBSRVTRY', help_text='Istituto Ricerche Solari Locarno Switzerland', blank=True, null=True)
	point_id = models.TextField(verbose_name = 'POINT_ID', help_text='one-off simulation, same as SMLATION', blank=True, null=True)
	settings = models.TextField(verbose_name = 'SETTINGS', help_text='input parameters', blank=True, null=True)
	sim_hdu = models.BigIntegerField(verbose_name = 'SIM_HDU', help_text='1 = simulation data (not observation)', blank=True, null=True)
	sim_nx = models.BigIntegerField(verbose_name = 'SIM_NX', help_text='grid points in x (hdf5: x1)', blank=True, null=True)
	sim_ny = models.BigIntegerField(verbose_name = 'SIM_NY', help_text='grid points in y (hdf5: x2)', blank=True, null=True)
	sim_nz = models.BigIntegerField(verbose_name = 'SIM_NZ', help_text='grid points in z (hdf5: x3)', blank=True, null=True)
	smlation = models.TextField(verbose_name = 'SMLATION', help_text='unique simulation identifier', blank=True, null=True)
	snapshot = models.BigIntegerField(verbose_name = 'SNAPSHOT', help_text='snapshot number', blank=True, null=True)
	solarnet = models.FloatField(verbose_name = 'SOLARNET', help_text='file is solarnet compliant', blank=True, null=True)
	target = models.TextField(verbose_name = 'TARGET', help_text='', blank=True, null=True)
	ztau51 = models.FloatField(verbose_name = 'ZTAU51', help_text='height of optical depth unity at 500nm', blank=True, null=True)
