# Generated by command write_metadata_files version 2
import datetime

from django.db import models

from .base_metadata import BaseMetadata

__all__ = ['EitSynoptic']


class EitSynoptic(BaseMetadata):
	"""Model for the metadata of dataset EIT synoptic"""

	# Constant values corresponding to the keyword with constant_value
	access_estsize = 4096
	access_format = 'image/fits'
	bib_reference = '2005ApJ...625.1063A'
	c1_resol_max = 0.25
	c1_resol_min = 0.25
	c1max = 360.0
	c1min = 0.0
	c2_resol_max = 0.25
	c2_resol_min = 0.25
	c2max = 90.0
	c2min = -90.0
	c3max = 835610.4
	c3min = 696342.0
	dataproduct_type = 'ma'
	granule_gid = 'efz'
	instrument_host_name = '1995-065A#SoHO'
	instrument_name = 'Extreme-ultraviolet Imaging Telescope#EIT'
	map_height = 720.0
	map_projection = 'Heliographic Carrington'
	map_width = 1440.0
	measurement_type = 'phot.radiance;em.UV.10-50nm;obs.image'
	messenger = 'UV'
	processing_level = 5
	producer_institute = "Universite Paris-Saclay#CNRS#Institut d'Astrophysique Spatiale"
	producer_name = 'Frederic Auchere'
	publisher = 'MEDOC'
	service_title = 'eit_syn'
	spatial_coordinate_description = 'HGC'
	spatial_frame_type = 'body'
	spectral_range_max = 1.7531722690058478e16
	spectral_range_min = 9861594013157894.0
	target_class = 'star'
	target_name = 'Sun'
	time_sampling_step_max = 86400.0
	time_sampling_step_min = 86400.0

	class Meta(BaseMetadata.Meta):
		verbose_name = 'EIT synoptic metadata'
		verbose_name_plural = 'EIT synoptic metadata'

	access_url = models.TextField(
		verbose_name='access_url',
		help_text='URL of the data file, case sensitive. If present, then access_format and access_estsize are mandatory.',
		blank=True,
		null=True,
	)
	creation_date = models.DateTimeField(
		verbose_name='creation_date', help_text='Date of first entry of this granule', blank=True, null=True
	)
	datalink_url = models.TextField(
		verbose_name='datalink_url', help_text='Datalinks and services for this objet', blank=True, null=True
	)
	file_name = models.TextField(
		verbose_name='file_name', help_text='Name of the data file only, case sensitive', blank=True, null=True
	)
	granule_uid = models.TextField(
		verbose_name='granule_uid',
		help_text='Internal table row index, which must be unique within the table. Can be alphanumeric.',
		blank=True,
		null=True,
	)
	modification_date = models.DateTimeField(
		verbose_name='modification_date',
		help_text='Date of last modification (used to handle mirroring)',
		blank=True,
		null=True,
	)
	obs_id = models.TextField(
		verbose_name='obs_id',
		help_text='Associates granules derived from the same data (e.g. various representations/processing levels). Can be alphanumeric, may be the ID of original observation.',
		blank=True,
		null=True,
	)
	release_date = models.DateTimeField(
		verbose_name='release_date', help_text='Start of public access period', blank=True, null=True
	)
	thumbnail_url = models.TextField(
		verbose_name='thumbnail_url',
		help_text='URL of a thumbnail image with predefined size (png ~200 pix, for use in a client only)',
		blank=True,
		null=True,
	)
	time_max = models.FloatField(
		verbose_name='time_max', help_text='Acquisition stop time (in JD), as UTC at time_refposition', blank=True, null=True
	)
	time_min = models.FloatField(
		verbose_name='time_min', help_text='Acquisition start time (in JD), as UTC at time_refposition', blank=True, null=True
	)
