from django.db import models

from .base_metadata import BaseMetadata


__all__ = ['GrisLevel1']

class GrisLevel1(BaseMetadata):
	'''Model for the metadata of dataset GRIS level 1'''
	
	class Meta(BaseMetadata.Meta):
		verbose_name = 'GRIS level 1 metadata'
		verbose_name_plural = 'GRIS level 1 metadata'
	
	accumula = models.BigIntegerField(verbose_name = 'ACCUMULA', help_text='number of accumulations', blank=True, null=True)
	adunorm = models.BigIntegerField(verbose_name = 'ADUNORM', help_text='normalization factor to ADU', blank=True, null=True)
	aosystem = models.TextField(verbose_name = 'AOSYSTEM', help_text='adaptative optic system', blank=True, null=True)
	azimut = models.FloatField(verbose_name = 'AZIMUT', help_text='Sun center azimut (degrees)', blank=True, null=True)
	b0angle = models.FloatField(verbose_name = 'B0ANGLE', help_text='B0 angle (degrees)', blank=True, null=True)
	bscale = models.FloatField(verbose_name = 'BSCALE', help_text='data = pixel * BSCALE + BZERO', blank=True, null=True)
	bzero = models.FloatField(verbose_name = 'BZERO', help_text='offset applied to true pixel values', blank=True, null=True)
	camera = models.TextField(verbose_name = 'CAMERA', help_text='camera', blank=True, null=True)
	campos = models.FloatField(verbose_name = 'CAMPOS', help_text='camera mirror position (mm)', blank=True, null=True)
	coefi_1 = models.FloatField(verbose_name = 'COEFI-1', help_text='coefficient I of state 1', blank=True, null=True)
	coefi_2 = models.FloatField(verbose_name = 'COEFI-2', help_text='coefficient I of state 2', blank=True, null=True)
	coefi_3 = models.FloatField(verbose_name = 'COEFI-3', help_text='coefficient I of state 3', blank=True, null=True)
	coefi_4 = models.FloatField(verbose_name = 'COEFI-4', help_text='coefficient I of state 4', blank=True, null=True)
	coefq_1 = models.FloatField(verbose_name = 'COEFQ-1', help_text='coefficient Q of state 1', blank=True, null=True)
	coefq_2 = models.FloatField(verbose_name = 'COEFQ-2', help_text='coefficient Q of state 2', blank=True, null=True)
	coefq_3 = models.FloatField(verbose_name = 'COEFQ-3', help_text='coefficient Q of state 3', blank=True, null=True)
	coefq_4 = models.FloatField(verbose_name = 'COEFQ-4', help_text='coefficient Q of state 4', blank=True, null=True)
	coefu_1 = models.FloatField(verbose_name = 'COEFU-1', help_text='coefficient U of state 1', blank=True, null=True)
	coefu_2 = models.FloatField(verbose_name = 'COEFU-2', help_text='coefficient U of state 2', blank=True, null=True)
	coefu_3 = models.FloatField(verbose_name = 'COEFU-3', help_text='coefficient U of state 3', blank=True, null=True)
	coefu_4 = models.FloatField(verbose_name = 'COEFU-4', help_text='coefficient U of state 4', blank=True, null=True)
	coefv_1 = models.FloatField(verbose_name = 'COEFV-1', help_text='coefficient V of state 1', blank=True, null=True)
	coefv_2 = models.FloatField(verbose_name = 'COEFV-2', help_text='coefficient V of state 2', blank=True, null=True)
	coefv_3 = models.FloatField(verbose_name = 'COEFV-3', help_text='coefficient V of state 3', blank=True, null=True)
	coefv_4 = models.FloatField(verbose_name = 'COEFV-4', help_text='coefficient V of state 4', blank=True, null=True)
	colpos = models.FloatField(verbose_name = 'COLPOS', help_text='collimator mirror position (mm)', blank=True, null=True)
	datafram = models.TextField(verbose_name = 'DATAFRAM', help_text='image portion', blank=True, null=True)
	datavers = models.BigIntegerField(verbose_name = 'DATAVERS', help_text='data version (0 means raw data)', blank=True, null=True)
	date_obs = models.DateTimeField(verbose_name = 'DATE-OBS', help_text='data acquisition date (yyyy-mm-dd)', blank=True, null=True)
	dec = models.FloatField(verbose_name = 'DEC', help_text='Sun center declination (degrees)', blank=True, null=True)
	eimgacc = models.BigIntegerField(verbose_name = 'EIMGACC', help_text='number of extra images to make an accumulation', blank=True, null=True)
	elevatio = models.FloatField(verbose_name = 'ELEVATIO', help_text='Sun center elevation (degrees)', blank=True, null=True)
	elperadu = models.BigIntegerField(verbose_name = 'ELPERADU', help_text='electrons per adu', blank=True, null=True)
	exptime = models.FloatField(verbose_name = 'EXPTIME', help_text='integration time of each image (msec)', blank=True, null=True)
	filename = models.TextField(verbose_name = 'FILENAME', help_text='file name', blank=True, null=True)
	filestat = models.TextField(verbose_name = 'FILESTAT', help_text='file final status', blank=True, null=True)
	fullfram = models.TextField(verbose_name = 'FULLFRAM', help_text='original full frame size', blank=True, null=True)
	gratangl = models.FloatField(verbose_name = 'GRATANGL', help_text='grating angle (degrees)', blank=True, null=True)
	hourangl = models.FloatField(verbose_name = 'HOURANGL', help_text='Sun center hour angle (degrees)', blank=True, null=True)
	ifile = models.BigIntegerField(verbose_name = 'IFILE', help_text='file index', blank=True, null=True)
	imagtype = models.TextField(verbose_name = 'IMAGTYPE', help_text='image type', blank=True, null=True)
	irfilter = models.TextField(verbose_name = 'IRFILTER', help_text='camera filter', blank=True, null=True)
	iserie = models.BigIntegerField(verbose_name = 'ISERIE', help_text='serie index', blank=True, null=True)
	l0angle = models.FloatField(verbose_name = 'L0ANGLE', help_text='L0 angle (degrees)', blank=True, null=True)
	lc1_1 = models.BigIntegerField(verbose_name = 'LC1-1', help_text='state 1 of crystal 1', blank=True, null=True)
	lc1_2 = models.BigIntegerField(verbose_name = 'LC1-2', help_text='state 2 of crystal 1', blank=True, null=True)
	lc1_3 = models.BigIntegerField(verbose_name = 'LC1-3', help_text='state 3 of crystal 1', blank=True, null=True)
	lc1_4 = models.BigIntegerField(verbose_name = 'LC1-4', help_text='state 4 of crystal 1', blank=True, null=True)
	lc2_1 = models.BigIntegerField(verbose_name = 'LC2-1', help_text='state 1 of crystal 2', blank=True, null=True)
	lc2_2 = models.BigIntegerField(verbose_name = 'LC2-2', help_text='state 2 of crystal 2', blank=True, null=True)
	lc2_3 = models.BigIntegerField(verbose_name = 'LC2-3', help_text='state 3 of crystal 2', blank=True, null=True)
	lc2_4 = models.BigIntegerField(verbose_name = 'LC2-4', help_text='state 4 of crystal 2', blank=True, null=True)
	lcs = models.BigIntegerField(verbose_name = 'LCS', help_text='number of liquid crystals', blank=True, null=True)
	measure = models.TextField(verbose_name = 'MEASURE', help_text='measure type', blank=True, null=True)
	naxis = models.BigIntegerField(verbose_name = 'NAXIS', help_text='number of axes', blank=True, null=True)
	naxis1 = models.BigIntegerField(verbose_name = 'NAXIS1', help_text='x', blank=True, null=True)
	naxis2 = models.BigIntegerField(verbose_name = 'NAXIS2', help_text='lambda', blank=True, null=True)
	naxis3 = models.BigIntegerField(verbose_name = 'NAXIS3', help_text='number of frames in this file', blank=True, null=True)
	nfiles = models.BigIntegerField(verbose_name = 'NFILES', help_text='number of split files', blank=True, null=True)
	p0angle = models.FloatField(verbose_name = 'P0ANGLE', help_text='P0 angle (degrees)', blank=True, null=True)
	paraangl = models.FloatField(verbose_name = 'PARAANGL', help_text='parallactic angle (degrees)', blank=True, null=True)
	r0radius = models.FloatField(verbose_name = 'R0RADIUS', help_text='solar radius (arcsec)', blank=True, null=True)
	ra = models.FloatField(verbose_name = 'RA', help_text='Sun center right ascension (degrees)', blank=True, null=True)
	rotangle = models.FloatField(verbose_name = 'ROTANGLE', help_text='rotator angle (degrees)', blank=True, null=True)
	rotcode = models.BigIntegerField(verbose_name = 'ROTCODE', help_text='0 means rotator inserted', blank=True, null=True)
	series = models.BigIntegerField(verbose_name = 'SERIES', help_text='number of repetitions of the measure', blank=True, null=True)
	spsystem = models.TextField(verbose_name = 'SPSYSTEM', help_text='scanning positioner system', blank=True, null=True)
	states = models.BigIntegerField(verbose_name = 'STATES', help_text='number of modulation states', blank=True, null=True)
	stepangl = models.FloatField(verbose_name = 'STEPANGL', help_text='scanning step angle (degrees)', blank=True, null=True)
	steps = models.BigIntegerField(verbose_name = 'STEPS', help_text='steps of each measure', blank=True, null=True)
	stepsh = models.BigIntegerField(verbose_name = 'STEPSH', help_text='steps in the axis parallel to the slit', blank=True, null=True)
	stepsize = models.FloatField(verbose_name = 'STEPSIZE', help_text='scanning step size (arcsec)', blank=True, null=True)
	stepsv = models.BigIntegerField(verbose_name = 'STEPSV', help_text='steps in the axis perpendicular to the slit', blank=True, null=True)
	telescop = models.TextField(verbose_name = 'TELESCOP', help_text='telescope', blank=True, null=True)
	temp_lc1 = models.FloatField(verbose_name = 'TEMP-LC1', help_text='temperature of crystal 1 (C)', blank=True, null=True)
	temp_lc2 = models.FloatField(verbose_name = 'TEMP-LC2', help_text='temperature of crystal 2 (C)', blank=True, null=True)
	waveleng = models.BigIntegerField(verbose_name = 'WAVELENG', help_text='spectrograph wavelength (nm)', blank=True, null=True)
