from __future__ import unicode_literals
from django.db import models
from .base import BaseMetadata

class HmiMagnetogram(BaseMetadata):
	bld_vers = models.TextField('BLD_VERS', help_text='Code release build number of program that created this record', blank=True, null=True)
	bunit = models.TextField('BUNIT', help_text='BUNIT: physical units of data, Gauss', blank=True, null=True)
	cadence = models.FloatField('CADENCE', help_text='repetition interval', blank=True, null=True)
	cal_fsn = models.IntegerField('CAL_FSN', help_text='FSN of the look-up table used to produce the observables', blank=True, null=True)
	calver64 = models.BigIntegerField('CALVER64', help_text='Calibration Version', blank=True, null=True)
	camera = models.IntegerField('CAMERA', help_text='For HMI: 1 (side camera), 2 (front camera), or 3 (both cameras)', blank=True, null=True)
	car_rot = models.IntegerField('CAR_ROT', help_text='Carrington rotation number of CRLN_OBS', blank=True, null=True)
	cdelt1 = models.FloatField('CDELT1', help_text='image scale in the x direction', blank=True, null=True)
	cdelt2 = models.FloatField('CDELT2', help_text='image scale in the y direction', blank=True, null=True)
	codever0 = models.TextField('CODEVER0', help_text='version of the l.o.s. observable code used to produce the data', blank=True, null=True)
	codever1 = models.TextField('CODEVER1', help_text='version of the gapfilling subroutine used to produce the data', blank=True, null=True)
	codever2 = models.TextField('CODEVER2', help_text='version of the temporal interpolation subroutine used to produce the data', blank=True, null=True)
	codever3 = models.TextField('CODEVER3', help_text='version of the polarization calibration subroutine used to produce the data', blank=True, null=True)
	content = models.TextField('CONTENT', help_text='CONTENT: MAGNETOGRAM', blank=True, null=True)
	crder1 = models.FloatField('CRDER1', help_text='CRDER1: estimate of random error in coordinate x', blank=True, null=True)
	crder2 = models.FloatField('CRDER2', help_text='CRDER2: estimate of random error in coordinate y', blank=True, null=True)
	crln_obs = models.FloatField('CRLN_OBS', help_text='Carrington longitude of the observer', blank=True, null=True)
	crlt_obs = models.FloatField('CRLT_OBS', help_text='Carrington latitude of the observer', blank=True, null=True)
	crota2 = models.FloatField('CROTA2', help_text='CROTA2: INST_ROT + SAT_ROT', blank=True, null=True)
	crpix1 = models.FloatField('CRPIX1', help_text='CRPIX1: location of the Sun center in CCD x direction', blank=True, null=True)
	crpix2 = models.FloatField('CRPIX2', help_text='CRPIX2: location of the Sun center in CCD y direction', blank=True, null=True)
	crval1 = models.FloatField('CRVAL1', help_text='CRVAL1: x origin - center of the solar disk', blank=True, null=True)
	crval2 = models.FloatField('CRVAL2', help_text='CRVAL2: y origin - center of the solar disk', blank=True, null=True)
	csyser1 = models.FloatField('CSYSER1', help_text='CSYSER1: estimate of systematic error in coordinate x', blank=True, null=True)
	csyser2 = models.FloatField('CSYSER2', help_text='CSYSER2: estimate of systematic error in coordinate y', blank=True, null=True)
	ctype1 = models.TextField('CTYPE1', help_text='CTYPE1: HPLN-TAN (SOLARX)', blank=True, null=True)
	ctype2 = models.TextField('CTYPE2', help_text='CTYPE2: HPLT-TAN (SOLARY)', blank=True, null=True)
	cunit1 = models.TextField('CUNIT1', help_text='CUNIT1: arcsec', blank=True, null=True)
	cunit2 = models.TextField('CUNIT2', help_text='CUNIT2: arcsec', blank=True, null=True)
	datakur2 = models.FloatField('DATAKUR2', help_text='Kurtosis of all pixels', blank=True, null=True)
	datakurt = models.FloatField('DATAKURT', help_text='Kurtosis of pixels within 99% of solar radius', blank=True, null=True)
	datamax = models.FloatField('DATAMAX', help_text='Maximum value from pixels within 99% of solar radius', blank=True, null=True)
	datamax2 = models.FloatField('DATAMAX2', help_text='Maximum value from all pixels', blank=True, null=True)
	datamea2 = models.FloatField('DATAMEA2', help_text='Mean value from all pixels', blank=True, null=True)
	datamean = models.FloatField('DATAMEAN', help_text='Mean value from pixels within 99% of solar radius', blank=True, null=True)
	datamed2 = models.FloatField('DATAMED2', help_text='Median value from all pixels', blank=True, null=True)
	datamedn = models.FloatField('DATAMEDN', help_text='Median value from pixels within 99% of solar radius', blank=True, null=True)
	datamin = models.FloatField('DATAMIN', help_text='Minimum value from pixels within 99% of solar radius', blank=True, null=True)
	datamin2 = models.FloatField('DATAMIN2', help_text='Minimum value from all pixels', blank=True, null=True)
	datarms = models.FloatField('DATARMS', help_text='Rms deviation from the mean value of pixels within 99% of solar radius', blank=True, null=True)
	datarms2 = models.FloatField('DATARMS2', help_text='Rms deviation from the mean value of all pixels', blank=True, null=True)
	datasign = models.IntegerField('DATASIGN', help_text='DATASIGN: sign of observable quantity wrt Sun center', blank=True, null=True)
	dataske2 = models.FloatField('DATASKE2', help_text='Skewness from the mean value of all pixels', blank=True, null=True)
	dataskew = models.FloatField('DATASKEW', help_text='Skewness from the mean value of pixels within 99% of solar radius', blank=True, null=True)
	datavals = models.IntegerField('DATAVALS', help_text='Actual number of data values in images (pixels)', blank=True, null=True)
	date = models.DateTimeField('DATE', help_text='Date_time of processing; ISO 8601 format UTC', blank=True, null=True)
	date_obs = models.DateTimeField('DATE-OBS', help_text='DATE_OBS = T_OBS - EXPTIME/2.0', blank=True, null=True)
	distcoef = models.TextField('DISTCOEF', help_text='path to the distortion coefficient table used to produce the data', blank=True, null=True)
	dsun_obs = models.FloatField('DSUN_OBS', help_text='Distance from SDO to Sun center.', blank=True, null=True)
	dsun_ref = models.FloatField('DSUN_REF', help_text='Astronomical Unit', blank=True, null=True)
	hcamid = models.IntegerField('HCAMID', help_text='HMI_SEQ_ID_EXP_PATH', blank=True, null=True)
	hcftid = models.IntegerField('HCFTID', help_text='HMI_SEQ_ID_FOCUS', blank=True, null=True)
	hflid = models.IntegerField('HFLID', help_text='HMI_SEQ_ID_FRAMELIST', blank=True, null=True)
	instrume = models.TextField('INSTRUME', help_text='For HMI: HMI_SIDE1, HMI_FRONT2, or HMI_COMBINED', blank=True, null=True)
	lutquery = models.TextField('LUTQUERY', help_text='query used for the look-up tables', blank=True, null=True)
	missvals = models.IntegerField('MISSVALS', help_text='Missing values: TOTVALS - DATAVALS', blank=True, null=True)
	obs_vn = models.FloatField('OBS_VN', help_text='velocity of the observer solar-northward (heliographic). + to north', blank=True, null=True)
	obs_vr = models.FloatField('OBS_VR', help_text='velocity of the observer in radial direction. + is away from Sun', blank=True, null=True)
	obs_vw = models.FloatField('OBS_VW', help_text='velocity of the observer solar-westward. + in rough direction of Earth orbit', blank=True, null=True)
	odicoeff = models.IntegerField('ODICOEFF', help_text='order of the distortion-coefficient polynomials', blank=True, null=True)
	origin = models.TextField('ORIGIN', help_text='ORIGIN: location where file made', blank=True, null=True)
	orocoeff = models.IntegerField('OROCOEFF', help_text='order of the differential-rotation polynomials', blank=True, null=True)
	polcalm = models.IntegerField('POLCALM', help_text='method used by the polarization calibration subroutine', blank=True, null=True)
	qlook = models.IntegerField('QLOOK', help_text='QLOOK: 0=final data, 1=quick-look data', blank=True, null=True)
	quality = models.IntegerField('QUALITY', help_text='Level 1.5 Quality word', blank=True, null=True)
	quallev1 = models.IntegerField('QUALLEV1', help_text='Logical OR on the bits of the level 1 Quality word', blank=True, null=True)
	recnum = models.BigIntegerField('RECNUM', help_text='JSOC Record Number', blank=True, null=True)
	rotcoef = models.TextField('ROTCOEF', help_text='path to the differential-rotation coefficient table used to produce the data', blank=True, null=True)
	rsun_obs = models.FloatField('RSUN_OBS', help_text='angular radius of Sun. Corresponds to arcsin(RSUN_REF/DSUN_OBS)', blank=True, null=True)
	rsun_ref = models.FloatField('RSUN_REF', help_text='Reference radius of the Sun: 696,000,000.0 m', blank=True, null=True)
	satvals = models.IntegerField('SATVALS', help_text='Saturated values', blank=True, null=True)
	segment = models.TextField('SEGMENT', help_text='JSOC Segment File Name', blank=True, null=True)
	series = models.TextField('SERIES', help_text='JSOC Series Name', blank=True, null=True)
	sintnum = models.IntegerField('SINTNUM', help_text='number of points used for the spatial interpolation', blank=True, null=True)
	slotnum = models.IntegerField('SLOTNUM', help_text='JSOC Slot Number', blank=True, null=True)
	source = models.TextField('SOURCE', help_text='level 1 filtergrams used to produce the observables', blank=True, null=True)
	sunum = models.BigIntegerField('SUNUM', help_text='JSOC Storage Unit Number', blank=True, null=True)
	telescop = models.TextField('TELESCOP', help_text='For HMI: SDO/HMI', blank=True, null=True)
	tfront = models.FloatField('TFRONT', help_text='temperature keyword for polarization calibration', blank=True, null=True)
	tintnum = models.IntegerField('TINTNUM', help_text='number of points used for the temporal interpolation', blank=True, null=True)
	t_obs = models.DateTimeField('T_OBS', help_text='nominal time', blank=True, null=True)
	totvals = models.IntegerField('TOTVALS', help_text='Expected number of data values (pixels)', blank=True, null=True)
	t_rec = models.DateTimeField('T_REC', help_text='Slot time', blank=True, null=True)
	tsel = models.FloatField('TSEL', help_text='temperature keyword for polarization calibration', blank=True, null=True)
	wavelnth = models.FloatField('WAVELNTH', help_text='For HMI: 6173.3 Angstroms', blank=True, null=True)
	wcsname = models.TextField('WCSNAME', help_text='WCS system name', blank=True, null=True)
