from django.db import models

from .base_metadata import BaseMetadata


__all__ = ['Ibis']

class Ibis(BaseMetadata):
	'''Model for the metadata of dataset IBIS'''
	
	class Meta(BaseMetadata.Meta):
		verbose_name = 'IBIS metadata'
		verbose_name_plural = 'IBIS metadata'
	
	baseclmp = models.BigIntegerField(verbose_name = 'BASECLMP', help_text='Baseline clamp value', blank=True, null=True)
	binning = models.BigIntegerField(verbose_name = 'BINNING', help_text='BINNING FACTOR', blank=True, null=True)
	bscale = models.FloatField(verbose_name = 'BSCALE', help_text='TRUE=(FITS VALUE)*BSCALE + BZERO', blank=True, null=True)
	buf_info = models.BigIntegerField(verbose_name = 'BUF_INFO', help_text='', blank=True, null=True)
	bunit = models.TextField(verbose_name = 'BUNIT', help_text='PIXEL VALUE', blank=True, null=True)
	bzero = models.FloatField(verbose_name = 'BZERO', help_text='THE OFFSET', blank=True, null=True)
	ccd_temp = models.BigIntegerField(verbose_name = 'CCD_TEMP', help_text='CCD SENSOR TEMP', blank=True, null=True)
	channel = models.TextField(verbose_name = 'CHANNEL', help_text='CAMERA IDENTIFER', blank=True, null=True)
	date = models.DateTimeField(verbose_name = 'DATE', help_text='DATE THE FILE WAS WRITTEN yyyy-mm-dd', blank=True, null=True)
	date_obs = models.DateTimeField(verbose_name = 'DATE-OBS', help_text='STARTING DATE AND TIME IN U.T.', blank=True, null=True)
	detector = models.TextField(verbose_name = 'DETECTOR', help_text='DETECTOR USED TO ACQUIRE THE DATA', blank=True, null=True)
	dst_az = models.FloatField(verbose_name = 'DST_AZ', help_text='', blank=True, null=True)
	dst_bee0 = models.FloatField(verbose_name = 'DST_BEE0', help_text='', blank=True, null=True)
	dst_el = models.FloatField(verbose_name = 'DST_EL', help_text='', blank=True, null=True)
	dst_ell0 = models.FloatField(verbose_name = 'DST_ELL0', help_text='', blank=True, null=True)
	dst_gdrn = models.FloatField(verbose_name = 'DST_GDRN', help_text='', blank=True, null=True)
	dst_gpa = models.FloatField(verbose_name = 'DST_GPA', help_text='', blank=True, null=True)
	dst_hpa = models.FloatField(verbose_name = 'DST_HPA', help_text='', blank=True, null=True)
	dst_llvl = models.FloatField(verbose_name = 'DST_LLVL', help_text='', blank=True, null=True)
	dst_pee = models.FloatField(verbose_name = 'DST_PEE', help_text='', blank=True, null=True)
	dst_rv = models.FloatField(verbose_name = 'DST_RV', help_text='', blank=True, null=True)
	dst_saz = models.FloatField(verbose_name = 'DST_SAZ', help_text='', blank=True, null=True)
	dst_sdim = models.FloatField(verbose_name = 'DST_SDIM', help_text='', blank=True, null=True)
	dst_see = models.FloatField(verbose_name = 'DST_SEE', help_text='', blank=True, null=True)
	dst_sel = models.FloatField(verbose_name = 'DST_SEL', help_text='', blank=True, null=True)
	dst_slat = models.FloatField(verbose_name = 'DST_SLAT', help_text='', blank=True, null=True)
	dst_slng = models.FloatField(verbose_name = 'DST_SLNG', help_text='', blank=True, null=True)
	dst_tbl = models.FloatField(verbose_name = 'DST_TBL', help_text='', blank=True, null=True)
	dst_time = models.TextField(verbose_name = 'DST_TIME', help_text='', blank=True, null=True)
	dst_xgdr = models.FloatField(verbose_name = 'DST_XGDR', help_text='', blank=True, null=True)
	dst_ygdr = models.FloatField(verbose_name = 'DST_YGDR', help_text='', blank=True, null=True)
	exp_eff = models.FloatField(verbose_name = 'EXP_EFF', help_text='ACTUAL EXPOSURE TIME SEC', blank=True, null=True)
	exptime = models.FloatField(verbose_name = 'EXPTIME', help_text='', blank=True, null=True)
	extend = models.BigIntegerField(verbose_name = 'EXTEND', help_text='True = EXTENSIONS MAY BE PRESENT IN FILE', blank=True, null=True)
	filename = models.TextField(verbose_name = 'FILENAME', help_text='DA', blank=True, null=True)
	fileorig = models.TextField(verbose_name = 'FILEORIG', help_text='OR', blank=True, null=True)
	filter = models.BigIntegerField(verbose_name = 'FILTER', help_text='', blank=True, null=True)
	fp1_volt = models.FloatField(verbose_name = 'FP1_VOLT', help_text='', blank=True, null=True)
	fp2_volt = models.FloatField(verbose_name = 'FP2_VOLT', help_text='', blank=True, null=True)
	framenum = models.BigIntegerField(verbose_name = 'FRAMENUM', help_text='', blank=True, null=True)
	gain_em = models.BigIntegerField(verbose_name = 'GAIN_EM', help_text='ELECTRON MULTIPIER GAIN', blank=True, null=True)
	gain_pre = models.TextField(verbose_name = 'GAIN_PRE', help_text='PRE-AMPLIFIER GAIN', blank=True, null=True)
	gcount = models.BigIntegerField(verbose_name = 'GCOUNT', help_text='', blank=True, null=True)
	instrume = models.TextField(verbose_name = 'INSTRUME', help_text='INSTRUMENT USED TO ACQUIRE THE DATA', blank=True, null=True)
	lcvr1_re = models.FloatField(verbose_name = 'LCVR1_RE', help_text='', blank=True, null=True)
	lcvr1_v = models.FloatField(verbose_name = 'LCVR1_V', help_text='', blank=True, null=True)
	lcvr2_re = models.FloatField(verbose_name = 'LCVR2_RE', help_text='', blank=True, null=True)
	lcvr2_v = models.FloatField(verbose_name = 'LCVR2_V', help_text='', blank=True, null=True)
	naxis = models.BigIntegerField(verbose_name = 'NAXIS', help_text='NUMBER OF AXES', blank=True, null=True)
	naxis1 = models.BigIntegerField(verbose_name = 'NAXIS1', help_text='', blank=True, null=True)
	naxis2 = models.BigIntegerField(verbose_name = 'NAXIS2', help_text='', blank=True, null=True)
	nimages = models.BigIntegerField(verbose_name = 'NIMAGES', help_text='', blank=True, null=True)
	observer = models.TextField(verbose_name = 'OBSERVER', help_text='TELESCOPE OPERATORS', blank=True, null=True)
	origin = models.TextField(verbose_name = 'ORIGIN', help_text='DST', blank=True, null=True)
	pcount = models.BigIntegerField(verbose_name = 'PCOUNT', help_text='', blank=True, null=True)
	pt4_fs = models.TextField(verbose_name = 'PT4_FS', help_text='', blank=True, null=True)
	pt4_mir = models.TextField(verbose_name = 'PT4_MIR', help_text='', blank=True, null=True)
	pt4_pol = models.FloatField(verbose_name = 'PT4_POL', help_text='', blank=True, null=True)
	pt4_pstg = models.TextField(verbose_name = 'PT4_PSTG', help_text='', blank=True, null=True)
	pt4_ret = models.FloatField(verbose_name = 'PT4_RET', help_text='', blank=True, null=True)
	pt4_rstg = models.TextField(verbose_name = 'PT4_RSTG', help_text='', blank=True, null=True)
	pt4_time = models.TextField(verbose_name = 'PT4_TIME', help_text='', blank=True, null=True)
	rel_wave = models.FloatField(verbose_name = 'REL_WAVE', help_text='', blank=True, null=True)
	seq_ctr = models.BigIntegerField(verbose_name = 'SEQ_CTR', help_text='', blank=True, null=True)
	seq_num = models.TextField(verbose_name = 'SEQ_NUM', help_text='SEQUENCE NUMBER  (sxxx)', blank=True, null=True)
	ser_num = models.BigIntegerField(verbose_name = 'SER_NUM', help_text='CAMERA SERIAL NUMBER', blank=True, null=True)
	seriesid = models.TextField(verbose_name = 'SERIESID', help_text='SAME TEXT AS PARENT DIRECTORY', blank=True, null=True)
	stokes = models.TextField(verbose_name = 'STOKES', help_text='', blank=True, null=True)
	target = models.TextField(verbose_name = 'TARGET', help_text='Indicates the observation region', blank=True, null=True)
	telescop = models.TextField(verbose_name = 'TELESCOP', help_text='NAME OF THE TELESCOPE', blank=True, null=True)
	wavelnth = models.FloatField(verbose_name = 'WAVELNTH', help_text='THE (APPROXIMATE ABS) WAVELENGTH OF THE OBSERVA', blank=True, null=True)
	waveunit = models.BigIntegerField(verbose_name = 'WAVEUNIT', help_text='', blank=True, null=True)
	wl_prflt = models.TextField(verbose_name = 'WL_PRFLT', help_text='WHITE LIGHT CAMERA PRE-FILTER WAVELENGTH', blank=True, null=True)
	x_start = models.BigIntegerField(verbose_name = 'X_START', help_text='X Start position of image', blank=True, null=True)
	xtension = models.TextField(verbose_name = 'XTENSION', help_text='', blank=True, null=True)
	y_start = models.BigIntegerField(verbose_name = 'Y_START', help_text='Y Start position of image', blank=True, null=True)
