# Generated by command write_metadata_files version 2
import datetime

from django.db import models

from .base_metadata import BaseMetadata

__all__ = ['LsoCompSLevel1']


class LsoCompSLevel1(BaseMetadata):
	"""Model for the metadata of dataset LSO CoMP-S level 1"""

	# Constant values corresponding to the keyword with constant_value

	class Meta(BaseMetadata.Meta):
		verbose_name = 'LSO CoMP-S level 1 metadata'
		verbose_name_plural = 'LSO CoMP-S level 1 metadata'

	aperture = models.FloatField(verbose_name='APERTURE', help_text='Telescope entrance aperture', blank=True, null=True)
	awavlnth = models.FloatField(verbose_name='AWAVLNTH', help_text='Wavelength in air', blank=True, null=True)
	beam = models.BigIntegerField(
		verbose_name='BEAM', help_text='Lyot filter beam (1=LINE, 2=QUASI-CONTINUUM)', blank=True, null=True
	)
	blank = models.BigIntegerField(verbose_name='BLANK', help_text='Value of missing pixels', blank=True, null=True)
	bscale = models.FloatField(verbose_name='BSCALE', help_text='', blank=True, null=True)
	btype = models.TextField(
		verbose_name='BTYPE', help_text='Description of what the data array represents', blank=True, null=True
	)
	bunit = models.TextField(verbose_name='BUNIT', help_text='Data array units', blank=True, null=True)
	bzero = models.BigIntegerField(verbose_name='BZERO', help_text='', blank=True, null=True)
	cam_loc = models.TextField(
		verbose_name='CAM-LOC', help_text='Camera location: T=transmissive, R=reflective', blank=True, null=True
	)
	cam_pixs = models.FloatField(verbose_name='CAM-PIXS', help_text='Camera pixel size', blank=True, null=True)
	cam_posi = models.FloatField(verbose_name='CAM-POSI', help_text='Camera chip position', blank=True, null=True)
	cam_rox1 = models.BigIntegerField(
		verbose_name='CAM-ROX1', help_text='Camera ROI - longer  chip left  edge', blank=True, null=True
	)
	cam_rox2 = models.BigIntegerField(
		verbose_name='CAM-ROX2', help_text='Camera ROI - longer  chip right edge', blank=True, null=True
	)
	cam_roy1 = models.BigIntegerField(
		verbose_name='CAM-ROY1', help_text='Camera ROI - shorter chip left  edge', blank=True, null=True
	)
	cam_roy2 = models.BigIntegerField(
		verbose_name='CAM-ROY2', help_text='Camera ROI - shorter chip right edge', blank=True, null=True
	)
	cam_sn = models.TextField(verbose_name='CAM-SN', help_text='Camera serial number', blank=True, null=True)
	cam_temp = models.FloatField(verbose_name='CAM-TEMP', help_text='Camera chip temperature', blank=True, null=True)
	camera = models.TextField(verbose_name='CAMERA', help_text='Camera chip type', blank=True, null=True)
	cdelt1 = models.FloatField(verbose_name='CDELT1', help_text='Theta_X plate scale', blank=True, null=True)
	cdelt2 = models.FloatField(verbose_name='CDELT2', help_text='Theta_Y plate scale', blank=True, null=True)
	cdelt3 = models.BigIntegerField(
		verbose_name='CDELT3', help_text='Conventional Stokes value step', blank=True, null=True
	)
	cdelt4 = models.FloatField(verbose_name='CDELT4', help_text='Image time step', blank=True, null=True)
	comment = models.TextField(verbose_name='COMMENT', help_text='', blank=True, null=True)
	crder1 = models.FloatField(
		verbose_name='CRDER1', help_text='Theta_X maximum random error estimate', blank=True, null=True
	)
	crder2 = models.FloatField(
		verbose_name='CRDER2', help_text='Theta_Y maximum random error estimate', blank=True, null=True
	)
	crder4 = models.FloatField(
		verbose_name='CRDER4', help_text='Time sampling maximum random error estimate', blank=True, null=True
	)
	creator = models.TextField(
		verbose_name='CREATOR', help_text='Name of software that produced the FITS file', blank=True, null=True
	)
	crpix1 = models.FloatField(verbose_name='CRPIX1', help_text='Theta_X reference pixel', blank=True, null=True)
	crpix2 = models.FloatField(verbose_name='CRPIX2', help_text='Theta_Y reference pixel', blank=True, null=True)
	crpix3 = models.BigIntegerField(verbose_name='CRPIX3', help_text='Stokes reference pixel', blank=True, null=True)
	crpix4 = models.BigIntegerField(verbose_name='CRPIX4', help_text='Time reference pixe', blank=True, null=True)
	crval1 = models.FloatField(
		verbose_name='CRVAL1', help_text='Theta_X Coordinate at reference pixel', blank=True, null=True
	)
	crval2 = models.FloatField(
		verbose_name='CRVAL2', help_text='Theta_Y Coordinate at reference pixel', blank=True, null=True
	)
	crval3 = models.BigIntegerField(
		verbose_name='CRVAL3', help_text='Conventional Stokes value at reference pixel', blank=True, null=True
	)
	crval4 = models.FloatField(
		verbose_name='CRVAL4', help_text='Offset from DATEREF reference pixel', blank=True, null=True
	)
	csyer1 = models.FloatField(
		verbose_name='CSYER1', help_text='Theta_X maximum systematic error estimate', blank=True, null=True
	)
	csyer2 = models.FloatField(
		verbose_name='CSYER2', help_text='Theta_Y maximum systematic error estimate', blank=True, null=True
	)
	csyer4 = models.FloatField(verbose_name='CSYER4', help_text='Time systematic error estimate', blank=True, null=True)
	ctype1 = models.TextField(verbose_name='CTYPE1', help_text='Axis label (Theta_X)', blank=True, null=True)
	ctype2 = models.TextField(verbose_name='CTYPE2', help_text='Axis label (Theta_Y)', blank=True, null=True)
	ctype3 = models.TextField(verbose_name='CTYPE3', help_text='Axis label (Stokes parameter)', blank=True, null=True)
	ctype4 = models.TextField(verbose_name='CTYPE4', help_text='Time of image acquisition', blank=True, null=True)
	cunit1 = models.TextField(verbose_name='CUNIT1', help_text='Theta_X angle unit', blank=True, null=True)
	cunit2 = models.TextField(verbose_name='CUNIT2', help_text='Theta_Y angle unit', blank=True, null=True)
	cunit3 = models.TextField(verbose_name='CUNIT3', help_text='Stokes parameter unit undefined', blank=True, null=True)
	cunit4 = models.TextField(verbose_name='CUNIT4', help_text='Time unit', blank=True, null=True)
	datatype = models.TextField(verbose_name='DATATYPE', help_text='Data type', blank=True, null=True)
	date_obs = models.DateTimeField(
		verbose_name='DATE-OBS', help_text='Start date/time of data acquisition', blank=True, null=True
	)
	dateref = models.DateTimeField(verbose_name='DATEREF', help_text='Time coordinate zero point', blank=True, null=True)
	detector = models.TextField(
		verbose_name='DETECTOR', help_text='Camera used for data acquisition', blank=True, null=True
	)
	diffuser = models.TextField(verbose_name='DIFFUSER', help_text="'IN BEAM' or 'OUT OF BEAM'", blank=True, null=True)
	elev_ang = models.FloatField(verbose_name='ELEV_ANG', help_text='Telescope elevation angle', blank=True, null=True)
	equinox = models.FloatField(verbose_name='EQUINOX', help_text='Equinox', blank=True, null=True)
	extname = models.TextField(verbose_name='EXTNAME', help_text='HDU (Header Data Unit) name', blank=True, null=True)
	filter = models.TextField(verbose_name='FILTER', help_text='Type of filter used', blank=True, null=True)
	flc_1 = models.TextField(
		verbose_name='FLC-1', help_text='FLC Variable retarder 1 tuning voltage', blank=True, null=True
	)
	flc_2 = models.TextField(
		verbose_name='FLC-2', help_text='FLC Variable retarder 2 tuning voltage', blank=True, null=True
	)
	flcangle = models.FloatField(verbose_name='FLCANGLE', help_text='FLC Variable retarder angle', blank=True, null=True)
	focus = models.FloatField(verbose_name='FOCUS', help_text='Telescope objective lens position', blank=True, null=True)
	fova1max = models.FloatField(
		verbose_name='FOVA1MAX', help_text='Maximum of the first spatial coordinate', blank=True, null=True
	)
	fova1min = models.FloatField(
		verbose_name='FOVA1MIN', help_text='Minimum of the first spatial coordinate', blank=True, null=True
	)
	fova2max = models.FloatField(
		verbose_name='FOVA2MAX', help_text='Minimum of the second spatial coordinate', blank=True, null=True
	)
	fova2min = models.FloatField(
		verbose_name='FOVA2MIN', help_text='Maximum of the second spatial coordinate', blank=True, null=True
	)
	ft_lock = models.BigIntegerField(
		verbose_name='FT_LOCK', help_text='Feature tracking (0-OFF,1-ON)', blank=True, null=True
	)
	fw_calib = models.TextField(verbose_name='FW-CALIB', help_text='Calibration optics element', blank=True, null=True)
	fw_wvlng = models.FloatField(verbose_name='FW-WVLNG', help_text='Pre-filter center wavelength', blank=True, null=True)
	gcount = models.BigIntegerField(verbose_name='GCOUNT', help_text='', blank=True, null=True)
	hduextnr = models.DateTimeField(
		verbose_name='HDUEXTNR', help_text='The order number of the binary extension', blank=True, null=True
	)
	hglt_obs = models.FloatField(
		verbose_name='HGLT_OBS', help_text='Latitude of the solar disk central point', blank=True, null=True
	)
	infodata = models.TextField(verbose_name='INFODATA', help_text='', blank=True, null=True)
	infopa = models.TextField(verbose_name='INFOPA', help_text='', blank=True, null=True)
	instrume = models.TextField(verbose_name='INSTRUME', help_text='Name of instrument', blank=True, null=True)
	level = models.BigIntegerField(verbose_name='LEVEL', help_text='Data processing level = 1', blank=True, null=True)
	longstrn = models.TextField(
		verbose_name='LONGSTRN', help_text='The OGIP long string convention may be used.', blank=True, null=True
	)
	lonpole = models.FloatField(
		verbose_name='LONPOLE', help_text='Native longitude of the celestial pole', blank=True, null=True
	)
	naxis = models.BigIntegerField(verbose_name='NAXIS', help_text='Number of axes', blank=True, null=True)
	naxis1 = models.BigIntegerField(
		verbose_name='NAXIS1', help_text='Length of the axis 1 - spatial axis', blank=True, null=True
	)
	naxis2 = models.BigIntegerField(
		verbose_name='NAXIS2', help_text='Length of the axis 2 - spatial axis', blank=True, null=True
	)
	naxis3 = models.BigIntegerField(
		verbose_name='NAXIS3', help_text='Length of the axis 3 - polarization axis', blank=True, null=True
	)
	nbin = models.BigIntegerField(verbose_name='NBIN', help_text='Product of all NBINs', blank=True, null=True)
	nbin1 = models.BigIntegerField(verbose_name='NBIN1', help_text='Binning in data dimension 1', blank=True, null=True)
	nbin2 = models.BigIntegerField(verbose_name='NBIN2', help_text='Binning in data dimension 2', blank=True, null=True)
	nlc_1 = models.FloatField(
		verbose_name='NLC-1', help_text='LC Variable retarder 1 tuning voltage', blank=True, null=True
	)
	nlc_2 = models.FloatField(
		verbose_name='NLC-2', help_text='LC Variable retarder 2 tuning voltage', blank=True, null=True
	)
	nlc_3 = models.FloatField(
		verbose_name='NLC-3', help_text='LC Variable retarder 3 tuning voltage', blank=True, null=True
	)
	nlc_4 = models.FloatField(
		verbose_name='NLC-4', help_text='LC Variable retarder 4 tuning voltage', blank=True, null=True
	)
	nsumexp = models.BigIntegerField(verbose_name='NSUMEXP', help_text='Number of summed exposures', blank=True, null=True)
	obs_hdu = models.BigIntegerField(
		verbose_name='OBS_HDU', help_text='This HDU contains observational data', blank=True, null=True
	)
	obs_mode = models.TextField(
		verbose_name='OBS_MODE', help_text='Predefined setting file - cookbook', blank=True, null=True
	)
	obs_prog = models.TextField(verbose_name='OBS_PROG', help_text='Observing program', blank=True, null=True)
	observer = models.TextField(verbose_name='OBSERVER', help_text='Observer', blank=True, null=True)
	obsgeo_x = models.FloatField(
		verbose_name='OBSGEO-X', help_text='Observer: fixed geographic X coordinate', blank=True, null=True
	)
	obsgeo_y = models.FloatField(
		verbose_name='OBSGEO-Y', help_text='Observer: fixed geographic Y coordinate', blank=True, null=True
	)
	obsgeo_z = models.FloatField(
		verbose_name='OBSGEO-Z', help_text='Observer: fixed geographic Z coordinate', blank=True, null=True
	)
	obsrvtry = models.TextField(verbose_name='OBSRVTRY', help_text='Name of observatory', blank=True, null=True)
	occ_size = models.FloatField(verbose_name='OCC-SIZE', help_text='Occulter diameter', blank=True, null=True)
	origin = models.TextField(
		verbose_name='ORIGIN', help_text='Location where FITS file has been created', blank=True, null=True
	)
	pc1_1 = models.FloatField(verbose_name='PC1_1', help_text='', blank=True, null=True)
	pc1_2 = models.FloatField(verbose_name='PC1_2', help_text='', blank=True, null=True)
	pc2_1 = models.FloatField(verbose_name='PC2_1', help_text='', blank=True, null=True)
	pc2_2 = models.FloatField(verbose_name='PC2_2', help_text='', blank=True, null=True)
	pc3_3 = models.FloatField(verbose_name='PC3_3', help_text='', blank=True, null=True)
	pc4_3 = models.FloatField(verbose_name='PC4_3', help_text='', blank=True, null=True)
	pcount = models.BigIntegerField(verbose_name='PCOUNT', help_text='', blank=True, null=True)
	point_id = models.TextField(
		verbose_name='POINT_ID', help_text='DATE_TIME_PA of the last re-pointing', blank=True, null=True
	)
	polcangl = models.FloatField(
		verbose_name='POLCANGL', help_text='Rotation of pol. reference system', blank=True, null=True
	)
	polcconv = models.TextField(verbose_name='POLCCONV', help_text='Polarimetric reference system', blank=True, null=True)
	project = models.TextField(
		verbose_name='PROJECT', help_text='Name of the observational project', blank=True, null=True
	)
	prproc2 = models.TextField(verbose_name='PRPROC2', help_text='Step 2: FITS keywords document2', blank=True, null=True)
	prpver2 = models.FloatField(
		verbose_name='PRPVER2', help_text='Step 2: Version of document related to PRSTEP2', blank=True, null=True
	)
	prstep1 = models.TextField(verbose_name='PRSTEP1', help_text='Step 1: binning', blank=True, null=True)
	prstep2 = models.TextField(
		verbose_name='PRSTEP2', help_text='Step 2: FITS keywords recommendations', blank=True, null=True
	)
	rot_comp = models.BigIntegerField(
		verbose_name='ROT_COMP', help_text='Solar rotation compensation (0-OFF,1-ON)', blank=True, null=True
	)
	rot_modl = models.TextField(
		verbose_name='ROT_MODL', help_text='Mode used for rotation compensation', blank=True, null=True
	)
	rotpos = models.FloatField(
		verbose_name='ROTPOS', help_text='Polar angle / FOV tilt to solar North', blank=True, null=True
	)
	rsun_arc = models.FloatField(
		verbose_name='RSUN_ARC', help_text='Solar radius outside Earth atmosphere', blank=True, null=True
	)
	rsun_ref = models.FloatField(
		verbose_name='RSUN_REF', help_text='Solar R used for pixel scale calculation', blank=True, null=True
	)
	solar_p0 = models.FloatField(
		verbose_name='SOLAR_P0', help_text='Angle between celestial N and solar N', blank=True, null=True
	)
	solarnet = models.FloatField(
		verbose_name='SOLARNET', help_text='Fully SOLARNET-compliant=1.0, partially=0.5', blank=True, null=True
	)
	specreso = models.BigIntegerField(
		verbose_name='SPECRESO', help_text='Lyot filter theoretical spectral resolution R', blank=True, null=True
	)
	specsys = models.TextField(
		verbose_name='SPECSYS', help_text='Coordinate reference frame = observer', blank=True, null=True
	)
	stok_fr1 = models.BigIntegerField(
		verbose_name='STOK-FR1', help_text='Frame 1 - Stokes XX, polarization X parallel li', blank=True, null=True
	)
	stok_fr2 = models.BigIntegerField(
		verbose_name='STOK-FR2', help_text='Frame 2 - Stokes YY, polarization Y parallel li', blank=True, null=True
	)
	stok_fr3 = models.BigIntegerField(
		verbose_name='STOK-FR3', help_text='Frame 3 - Stokes XY, polarization XY cross line', blank=True, null=True
	)
	stok_fr4 = models.BigIntegerField(
		verbose_name='STOK-FR4', help_text='Frame 4 - Stokes YX, polarization YX cross line', blank=True, null=True
	)
	telconfg = models.TextField(verbose_name='TELCONFG', help_text='Telescope configuration', blank=True, null=True)
	telescop = models.TextField(verbose_name='TELESCOP', help_text='Name of telescope', blank=True, null=True)
	texposur = models.FloatField(verbose_name='TEXPOSUR', help_text='Single-exposure time', blank=True, null=True)
	time_fr1 = models.DateTimeField(verbose_name='TIME-FR1', help_text='Frame 1 - time of exposure', blank=True, null=True)
	time_fr2 = models.DateTimeField(verbose_name='TIME-FR2', help_text='Frame 2 - time of exposure', blank=True, null=True)
	time_fr3 = models.DateTimeField(verbose_name='TIME-FR3', help_text='Frame 3 - time of exposure', blank=True, null=True)
	time_fr4 = models.DateTimeField(verbose_name='TIME-FR4', help_text='Frame 4 - time of exposure', blank=True, null=True)
	timesys = models.TextField(verbose_name='TIMESYS', help_text='', blank=True, null=True)
	tunedlay = models.FloatField(verbose_name='TUNEDLAY', help_text='LCVRs relaxation delay', blank=True, null=True)
	velosys = models.BigIntegerField(
		verbose_name='VELOSYS', help_text='No velocity correction applied to AWAVL', blank=True, null=True
	)
	vers_sw = models.FloatField(verbose_name='VERS_SW', help_text='Version of software applied', blank=True, null=True)
	version = models.BigIntegerField(
		verbose_name='VERSION', help_text='Data processing version of the file', blank=True, null=True
	)
	waveband = models.TextField(
		verbose_name='WAVEBAND', help_text='Strongest emission line in data', blank=True, null=True
	)
	waveref = models.TextField(verbose_name='WAVEREF', help_text='Wavelength related kwds in air', blank=True, null=True)
	waveunit = models.BigIntegerField(
		verbose_name='WAVEUNIT', help_text='Wavelength related kwds unit: 10^(WAVEUNIT)', blank=True, null=True
	)
	wcsaxes = models.BigIntegerField(
		verbose_name='WCSAXES', help_text='Number of axes in WCS description', blank=True, null=True
	)
	wcsname = models.TextField(verbose_name='WCSNAME', help_text='World Coordinate System', blank=True, null=True)
	xposure = models.FloatField(verbose_name='XPOSURE', help_text='Accumulated exposure time', blank=True, null=True)
	xtension = models.TextField(verbose_name='XTENSION', help_text='Extension type', blank=True, null=True)
