# Generated by command write_metadata_files version 1
from django.db import models

from .base_metadata import BaseMetadata

__all__ = ['LyraLevel2']

class LyraLevel2(BaseMetadata):
	'''Model for the metadata of dataset LYRA level 2'''
	
	class Meta(BaseMetadata.Meta):
		verbose_name = 'LYRA level 2 metadata'
		verbose_name_plural = 'LYRA level 2 metadata'
	
	fits_header = models.TextField(null=True, blank=True)
	algor_v = models.TextField(verbose_name = 'ALGOR_V', help_text='LYRA calibration S/W version', blank=True, null=True)
	datasrc = models.TextField(verbose_name = 'DATASRC', help_text='receiving ground station', blank=True, null=True)
	date = models.DateTimeField(verbose_name = 'DATE', help_text='', blank=True, null=True)
	date_obs = models.DateTimeField(verbose_name = 'DATE-OBS', help_text='UTC start of observation', blank=True, null=True)
	filename = models.TextField(verbose_name = 'FILENAME', help_text='name of this FITS file', blank=True, null=True)
	instrume = models.TextField(verbose_name = 'INSTRUME', help_text='', blank=True, null=True)
	level = models.BigIntegerField(verbose_name = 'LEVEL', help_text='calibration level', blank=True, null=True)
	naxis = models.BigIntegerField(verbose_name = 'NAXIS', help_text='', blank=True, null=True)
	object = models.TextField(verbose_name = 'OBJECT', help_text='', blank=True, null=True)
	obs_mode = models.TextField(verbose_name = 'OBS_MODE', help_text='science data', blank=True, null=True)
	origin = models.TextField(verbose_name = 'ORIGIN', help_text='', blank=True, null=True)
	telescop = models.TextField(verbose_name = 'TELESCOP', help_text='', blank=True, null=True)
