# Generated by command write_metadata_files version 1
from django.db import models

from .base_metadata import BaseMetadata

__all__ = ['SpocaCoronalHole']

class SpocaCoronalHole(BaseMetadata):
	'''Model for the metadata of dataset SPoCA Coronal Hole'''
	
	class Meta(BaseMetadata.Meta):
		verbose_name = 'SPoCA Coronal Hole metadata'
		verbose_name_plural = 'SPoCA Coronal Hole metadata'
	
	aggregat = models.BigIntegerField(verbose_name = 'AGGREGAT', help_text='Aggregation factor in arcsec', blank=True, null=True)
	cd1_1 = models.FloatField(verbose_name = 'CD1_1', help_text='', blank=True, null=True)
	cd1_2 = models.FloatField(verbose_name = 'CD1_2', help_text='', blank=True, null=True)
	cd2_1 = models.FloatField(verbose_name = 'CD2_1', help_text='', blank=True, null=True)
	cd2_2 = models.FloatField(verbose_name = 'CD2_2', help_text='', blank=True, null=True)
	cdelt1 = models.FloatField(verbose_name = 'CDELT1', help_text='image scale in the x direction', blank=True, null=True)
	cdelt2 = models.FloatField(verbose_name = 'CDELT2', help_text='image scale in the y direction', blank=True, null=True)
	cfuzfier = models.FloatField(verbose_name = 'CFUZFIER', help_text='the fuzzifier exponent', blank=True, null=True)
	channels = models.TextField(verbose_name = 'CHANNELS', help_text='', blank=True, null=True)
	clastype = models.TextField(verbose_name = 'CLASTYPE', help_text='the type of classifier', blank=True, null=True)
	cleaning = models.BigIntegerField(verbose_name = 'CLEANING', help_text='Cleaning factor in arcsec', blank=True, null=True)
	clsctr01 = models.TextField(verbose_name = 'CLSCTR01', help_text='value of the center of class 1', blank=True, null=True)
	clsctr02 = models.TextField(verbose_name = 'CLSCTR02', help_text='value of the center of class 2', blank=True, null=True)
	clsctr03 = models.TextField(verbose_name = 'CLSCTR03', help_text='value of the center of class 3', blank=True, null=True)
	clsctr04 = models.TextField(verbose_name = 'CLSCTR04', help_text='value of the center of class 4', blank=True, null=True)
	cmaxiter = models.BigIntegerField(verbose_name = 'CMAXITER', help_text='maximal number of iteration for the classification', blank=True, null=True)
	cnbrclas = models.BigIntegerField(verbose_name = 'CNBRCLAS', help_text='number of classes', blank=True, null=True)
	cprecis = models.FloatField(verbose_name = 'CPRECIS', help_text='precision to be reached to stop the classification', blank=True, null=True)
	cpreproc = models.TextField(verbose_name = 'CPREPROC', help_text='preprocessing steps to apply to the sun images', blank=True, null=True)
	crln_obs = models.FloatField(verbose_name = 'CRLN_OBS', help_text='Carrington longitude of the observer', blank=True, null=True)
	crpix1 = models.FloatField(verbose_name = 'CRPIX1', help_text='location of sun center in CCD x direction', blank=True, null=True)
	crpix2 = models.FloatField(verbose_name = 'CRPIX2', help_text='location of sun center in CCD y direction', blank=True, null=True)
	ctype1 = models.TextField(verbose_name = 'CTYPE1', help_text='', blank=True, null=True)
	ctype2 = models.TextField(verbose_name = 'CTYPE2', help_text='', blank=True, null=True)
	cunit1 = models.TextField(verbose_name = 'CUNIT1', help_text='', blank=True, null=True)
	cunit2 = models.TextField(verbose_name = 'CUNIT2', help_text='', blank=True, null=True)
	date_obs = models.DateTimeField(verbose_name = 'DATE_OBS', help_text='date when observation started', blank=True, null=True)
	dsun_obs = models.FloatField(verbose_name = 'DSUN_OBS', help_text='Distance from SDO to Sun center', blank=True, null=True)
	extname = models.TextField(verbose_name = 'EXTNAME', help_text='', blank=True, null=True)
	fraggmtd = models.BooleanField(verbose_name = 'FRAGGMTD', help_text='Regions are fragmented', blank=True, null=True)
	hgln_obs = models.FloatField(verbose_name = 'HGLN_OBS', help_text='Stonyhurst heliographic longitude of the observer', blank=True, null=True)
	hglt_obs = models.FloatField(verbose_name = 'HGLT_OBS', help_text='Stonyhurst heliographic latitude of the observer', blank=True, null=True)
	image001 = models.TextField(verbose_name = 'IMAGE001', help_text='name of the image of the first channel', blank=True, null=True)
	instrume = models.TextField(verbose_name = 'INSTRUME', help_text='SPoCA coronal region map', blank=True, null=True)
	minsize = models.BigIntegerField(verbose_name = 'MINSIZE', help_text='Min size of regions in arcsec', blank=True, null=True)
	naxis = models.BigIntegerField(verbose_name = 'NAXIS', help_text='dimension of original image', blank=True, null=True)
	naxis1 = models.BigIntegerField(verbose_name = 'NAXIS1', help_text='length of original image axis', blank=True, null=True)
	naxis2 = models.BigIntegerField(verbose_name = 'NAXIS2', help_text='length of original image axis', blank=True, null=True)
	projectn = models.TextField(verbose_name = 'PROJECTN', help_text='Projection used for the cleaning and aggregation', blank=True, null=True)
	rsun_obs = models.FloatField(verbose_name = 'RSUN_OBS', help_text='Apparent radius of the Sun seen by SDO', blank=True, null=True)
	rsun_ref = models.FloatField(verbose_name = 'RSUN_REF', help_text='Reference radius of the Sun', blank=True, null=True)
	segmtype = models.TextField(verbose_name = 'SEGMTYPE', help_text='type of segmentation', blank=True, null=True)
	telescop = models.TextField(verbose_name = 'TELESCOP', help_text='', blank=True, null=True)
	thrawar = models.BooleanField(verbose_name = 'THRAWAR', help_text='Min size threshold on raw area', blank=True, null=True)
