# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-22 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
