# Generated by Django 3.2.4 on 2021-10-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('metadata', '0002_add_lyra_level_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyraLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID')),
                ('fits_header', models.TextField(blank=True, null=True)),
                ('date_beg', models.DateTimeField(blank=True, db_index=True, help_text='Start time of the observation [UTC]', null=True, verbose_name='DATE-BEG')),
                ('date_end', models.DateTimeField(blank=True, db_index=True, help_text='End time of the observation [UTC]', null=True, verbose_name='DATE-END')),
                ('wavemin', models.FloatField(blank=True, db_index=True, help_text='Min value of the observation spectral range [nm]', null=True, verbose_name='WAVEMIN')),
                ('wavemax', models.FloatField(blank=True, db_index=True, help_text='Max value of the observation spectral range [nm]', null=True, verbose_name='WAVEMAX')),
                ('algor_v', models.TextField(blank=True, help_text='LYRA calibration S/W version', null=True, verbose_name='ALGOR_V')),
                ('datasrc', models.TextField(blank=True, help_text='receiving ground station', null=True, verbose_name='DATASRC')),
                ('date', models.DateTimeField(blank=True, help_text='Date at which this fits file was processed', null=True, verbose_name='DATE')),
                ('date_obs', models.DateTimeField(blank=True, help_text='UTC start of observation', null=True, verbose_name='DATE-OBS')),
                ('del_time', models.BigIntegerField(blank=True, help_text='one-minute averages', null=True, verbose_name='DEL_TIME')),
                ('extend', models.BooleanField(blank=True, help_text='File contains extensions', null=True, verbose_name='EXTEND')),
                ('filename', models.TextField(blank=True, help_text='name of this FITS file', null=True, verbose_name='FILENAME')),
                ('instrume', models.TextField(blank=True, help_text='Name of the payload producing the data', null=True, verbose_name='INSTRUME')),
                ('level', models.DateTimeField(blank=True, help_text='calibration level', null=True, verbose_name='LEVEL')),
                ('naxis', models.BigIntegerField(blank=True, null=True, verbose_name='NAXIS')),
                ('object', models.TextField(blank=True, help_text='Type of data contained in this fits file', null=True, verbose_name='OBJECT')),
                ('obs_mode', models.TextField(blank=True, help_text='science data', null=True, verbose_name='OBS_MODE')),
                ('origin', models.TextField(blank=True, help_text='Institute in charge of the data processing', null=True, verbose_name='ORIGIN')),
                ('telescop', models.TextField(blank=True, help_text='Name of the satellite', null=True, verbose_name='TELESCOP')),
                ('data_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_lyralevel3', to='dataset.datalocation')),
                ('tags', models.ManyToManyField(blank=True, related_name='metadata_lyralevel3', to='metadata.Tag')),
            ],
            options={
                'verbose_name': 'LYRA level 3 metadata',
                'verbose_name_plural': 'LYRA level 3 metadata',
                'ordering': ['date_beg'],
                'abstract': False,
            },
        ),
    ]
