# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_ibis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibis',
            name='date_obs',
            field=models.DateTimeField(blank=True, help_text='STARTING DATE AND TIME IN U.T.', null=True, verbose_name='DATE-OBS'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='wavelnth',
            field=models.FloatField(blank=True, help_text='THE (APPROXIMATE ABS) WAVELENGTH OF THE OBSERVA', null=True, verbose_name='WAVELNTH'),
        ),
    ]
