# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20170314_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibis',
            name='channel',
            field=models.TextField(blank=True, null=True, verbose_name='CHANNEL'),
        ),
    ]
