# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-14 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_ibis_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibis',
            name='baseclmp',
            field=models.BigIntegerField(blank=True, help_text='Baseline clamp value', null=True, verbose_name='BASECLMP'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='binning',
            field=models.BigIntegerField(blank=True, help_text='BINNING FACTOR', null=True, verbose_name='BINNING'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='bscale',
            field=models.FloatField(blank=True, help_text='TRUE=(FITS VALUE)*BSCALE + BZERO', null=True, verbose_name='BSCALE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='buf_info',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='BUF_INFO'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='bunit',
            field=models.TextField(blank=True, help_text='PIXEL VALUE', null=True, verbose_name='BUNIT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='bzero',
            field=models.FloatField(blank=True, help_text='THE OFFSET', null=True, verbose_name='BZERO'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='ccd_temp',
            field=models.BigIntegerField(blank=True, help_text='CCD SENSOR TEMP', null=True, verbose_name='CCD_TEMP'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='date',
            field=models.DateTimeField(blank=True, help_text='DATE THE FILE WAS WRITTEN yyyy-mm-dd', null=True, verbose_name='DATE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='detector',
            field=models.TextField(blank=True, help_text='DETECTOR USED TO ACQUIRE THE DATA', null=True, verbose_name='DETECTOR'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_az',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_AZ'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_bee0',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_BEE0'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_el',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_EL'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_ell0',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_ELL0'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_gdrn',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_GDRN'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_gpa',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_GPA'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_hpa',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_HPA'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_llvl',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_LLVL'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_pee',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_PEE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_rv',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_RV'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_saz',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_SAZ'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_sdim',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_SDIM'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_see',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_SEE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_sel',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_SEL'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_slat',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_SLAT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_slng',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_SLNG'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_tbl',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_TBL'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_time',
            field=models.TextField(blank=True, null=True, verbose_name='DST_TIME'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_xgdr',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_XGDR'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='dst_ygdr',
            field=models.FloatField(blank=True, null=True, verbose_name='DST_YGDR'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='exp_eff',
            field=models.FloatField(blank=True, help_text='ACTUAL EXPOSURE TIME SEC', null=True, verbose_name='EXP_EFF'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='exptime',
            field=models.FloatField(blank=True, null=True, verbose_name='EXPTIME'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='extend',
            field=models.BigIntegerField(blank=True, help_text='True = EXTENSIONS MAY BE PRESENT IN FILE', null=True, verbose_name='EXTEND'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='filename',
            field=models.TextField(blank=True, help_text='DA', null=True, verbose_name='FILENAME'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='fileorig',
            field=models.TextField(blank=True, help_text='OR', null=True, verbose_name='FILEORIG'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='filter',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='FILTER'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='fp1_volt',
            field=models.FloatField(blank=True, null=True, verbose_name='FP1_VOLT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='fp2_volt',
            field=models.FloatField(blank=True, null=True, verbose_name='FP2_VOLT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='framenum',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='FRAMENUM'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='gain_em',
            field=models.BigIntegerField(blank=True, help_text='ELECTRON MULTIPIER GAIN', null=True, verbose_name='GAIN_EM'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='gain_pre',
            field=models.TextField(blank=True, help_text='PRE-AMPLIFIER GAIN', null=True, verbose_name='GAIN_PRE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='gcount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='GCOUNT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='instrume',
            field=models.TextField(blank=True, help_text='INSTRUMENT USED TO ACQUIRE THE DATA', null=True, verbose_name='INSTRUME'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='lcvr1_re',
            field=models.FloatField(blank=True, null=True, verbose_name='LCVR1_RE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='lcvr1_v',
            field=models.FloatField(blank=True, null=True, verbose_name='LCVR1_V'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='lcvr2_re',
            field=models.FloatField(blank=True, null=True, verbose_name='LCVR2_RE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='lcvr2_v',
            field=models.FloatField(blank=True, null=True, verbose_name='LCVR2_V'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='naxis',
            field=models.BigIntegerField(blank=True, help_text='NUMBER OF AXES', null=True, verbose_name='NAXIS'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='naxis1',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='NAXIS1'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='naxis2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='NAXIS2'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='nimages',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='NIMAGES'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='observer',
            field=models.TextField(blank=True, help_text='TELESCOPE OPERATORS', null=True, verbose_name='OBSERVER'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='origin',
            field=models.TextField(blank=True, help_text='DST', null=True, verbose_name='ORIGIN'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pcount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='PCOUNT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pt4_fs',
            field=models.TextField(blank=True, null=True, verbose_name='PT4_FS'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pt4_mir',
            field=models.TextField(blank=True, null=True, verbose_name='PT4_MIR'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pt4_pol',
            field=models.FloatField(blank=True, null=True, verbose_name='PT4_POL'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pt4_pstg',
            field=models.TextField(blank=True, null=True, verbose_name='PT4_PSTG'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pt4_ret',
            field=models.FloatField(blank=True, null=True, verbose_name='PT4_RET'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pt4_rstg',
            field=models.TextField(blank=True, null=True, verbose_name='PT4_RSTG'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='pt4_time',
            field=models.TextField(blank=True, null=True, verbose_name='PT4_TIME'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='rel_wave',
            field=models.FloatField(blank=True, null=True, verbose_name='REL_WAVE'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='seq_ctr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='SEQ_CTR'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='seq_num',
            field=models.TextField(blank=True, help_text='SEQUENCE NUMBER  (sxxx)', null=True, verbose_name='SEQ_NUM'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='ser_num',
            field=models.BigIntegerField(blank=True, help_text='CAMERA SERIAL NUMBER', null=True, verbose_name='SER_NUM'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='seriesid',
            field=models.TextField(blank=True, help_text='SAME TEXT AS PARENT DIRECTORY', null=True, verbose_name='SERIESID'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='stokes',
            field=models.TextField(blank=True, null=True, verbose_name='STOKES'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='telescop',
            field=models.TextField(blank=True, help_text='NAME OF THE TELESCOPE', null=True, verbose_name='TELESCOP'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='waveunit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='WAVEUNIT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='wl_prflt',
            field=models.TextField(blank=True, help_text='WHITE LIGHT CAMERA PRE-FILTER WAVELENGTH', null=True, verbose_name='WL_PRFLT'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='x_start',
            field=models.BigIntegerField(blank=True, help_text='X Start position of image', null=True, verbose_name='X_START'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='xtension',
            field=models.TextField(blank=True, null=True, verbose_name='XTENSION'),
        ),
        migrations.AddField(
            model_name='ibis',
            name='y_start',
            field=models.BigIntegerField(blank=True, help_text='Y Start position of image', null=True, verbose_name='Y_START'),
        ),
        migrations.AlterField(
            model_name='ibis',
            name='channel',
            field=models.TextField(blank=True, help_text='CAMERA IDENTIFER', null=True, verbose_name='CHANNEL'),
        ),
    ]
