# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-16 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_auto_20170316_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grislev1',
            old_name='wavelnth',
            new_name='waveleng',
        ),
    ]
