# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-16 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20170316_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grislev1',
            name='utime',
        ),
    ]
