# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20170316_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grislev1',
            name='date_obs',
            field=models.DateTimeField(blank=True, help_text='data acquisition date (yyyy-mm-dd)', null=True, verbose_name='DATE-OBS'),
        ),
    ]
