# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_rosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosa',
            name='cadence',
            field=models.FloatField(blank=True, null=True, verbose_name='CADENCE'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='channel',
            field=models.TextField(blank=True, null=True, verbose_name='CHANNEL'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='goes_class',
            field=models.TextField(blank=True, help_text='GOES Class', null=True, verbose_name='GOES-CLS'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='instrume',
            field=models.TextField(blank=True, null=True, verbose_name='INSTRUME'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='obsrvtry',
            field=models.TextField(blank=True, null=True, verbose_name='OBSRVTRY'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='pointing',
            field=models.TextField(blank=True, null=True, verbose_name='POINTING'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='TARGET'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='telescop',
            field=models.TextField(blank=True, null=True, verbose_name='TELESCOP'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='wavelnth',
            field=models.IntegerField(blank=True, null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='xposure',
            field=models.FloatField(blank=True, help_text='Exposure time', null=True, verbose_name='XPOSURE'),
        ),
    ]
