# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_auto_20170321_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rosa',
            old_name='goes_class',
            new_name='goes_cls',
        ),
    ]
