# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_auto_20170321_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosa',
            name='cadence',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='goes_cls',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='instrume',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='obsrvtry',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='pointing',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='target',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='telescop',
        ),
        migrations.RemoveField(
            model_name='rosa',
            name='xposure',
        ),
    ]
