# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_auto_20170321_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosa',
            name='cadence',
            field=models.FloatField(blank=True, null=True, verbose_name='CADENCE'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='channel',
            field=models.TextField(blank=True, null=True, verbose_name='CHANNEL'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='date',
            field=models.TextField(blank=True, help_text='Creation UTC (CCCC-MM-DD) date of FITS header', null=True, verbose_name='DATE'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='extend',
            field=models.BigIntegerField(blank=True, help_text='FITS data may contain extensions', null=True, verbose_name='EXTEND'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='goes_cls',
            field=models.TextField(blank=True, null=True, verbose_name='GOES_CLS'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='instrume',
            field=models.TextField(blank=True, null=True, verbose_name='INSTRUME'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='naxis',
            field=models.BigIntegerField(blank=True, help_text='Number of data axes', null=True, verbose_name='NAXIS'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='naxis1',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='NAXIS1'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='naxis2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='NAXIS2'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='obsrvtry',
            field=models.TextField(blank=True, null=True, verbose_name='OBSRVTRY'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='pointing',
            field=models.TextField(blank=True, null=True, verbose_name='POINTING'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='solarnet',
            field=models.FloatField(blank=True, null=True, verbose_name='SOLARNET'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='TARGET'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='telescop',
            field=models.TextField(blank=True, null=True, verbose_name='TELESCOP'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='xposure',
            field=models.FloatField(blank=True, null=True, verbose_name='XPOSURE'),
        ),
        migrations.AlterField(
            model_name='rosa',
            name='wavelnth',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='WAVELNTH'),
        ),
    ]
