# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_auto_20170321_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosa',
            name='cdelt1',
            field=models.FloatField(blank=True, help_text='Coordinate increment', null=True, verbose_name='CDELT1'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='cdelt2',
            field=models.FloatField(blank=True, help_text='Coordinate increment', null=True, verbose_name='CDELT2'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='cunit1',
            field=models.TextField(blank=True, help_text='Axis units', null=True, verbose_name='CUNIT1'),
        ),
        migrations.AddField(
            model_name='rosa',
            name='cunit2',
            field=models.TextField(blank=True, help_text='Axis units', null=True, verbose_name='CUNIT2'),
        ),
        migrations.AlterField(
            model_name='rosa',
            name='wavelnth',
            field=models.FloatField(blank=True, help_text='Central wavelength of filter', null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AlterField(
            model_name='rosa',
            name='xposure',
            field=models.FloatField(blank=True, help_text='Exposure', null=True, verbose_name='XPOSURE'),
        ),
    ]
