# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0018_auto_20170324_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibis',
            name='target',
            field=models.TextField(blank=True, help_text='Indicates the observation region', null=True, verbose_name='TARGET'),
        ),
    ]
