# Generated by Django 3.2.13 on 2023-05-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0018_add_lars_level_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chrotel',
        ),
    ]
