# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-23 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_chromis_crisp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromis',
            name='ao_lock',
            field=models.FloatField(blank=True, help_text='Fraction of time the AO was locking, 2s average', null=True, verbose_name='AO_LOCK'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ao_nmode',
            field=models.BigIntegerField(blank=True, help_text='Number of AO corrected Mirror modes', null=True, verbose_name='AO_NMODE'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='atmos_r0',
            field=models.FloatField(blank=True, help_text='Atmospheric coherence length (mean value)', null=True, verbose_name='ATMOS_R0'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='btype',
            field=models.TextField(blank=True, help_text='Type of data in array', null=True, verbose_name='BTYPE'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='bunit',
            field=models.TextField(blank=True, help_text='Units in array', null=True, verbose_name='BUNIT'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cadavg',
            field=models.FloatField(blank=True, help_text='Average of actual cadence', null=True, verbose_name='CADAVG'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cadmax',
            field=models.FloatField(blank=True, help_text='Maximum of actual cadence', null=True, verbose_name='CADMAX'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cadmin',
            field=models.FloatField(blank=True, help_text='Minimum of actual cadence', null=True, verbose_name='CADMIN'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cadvar',
            field=models.FloatField(blank=True, help_text='Variance of actual cadence', null=True, verbose_name='CADVAR'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='camera',
            field=models.TextField(blank=True, null=True, verbose_name='CAMERA'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cdelt1',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CDELT1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cdelt1a',
            field=models.FloatField(blank=True, help_text='Zero FOV extent', null=True, verbose_name='CDELT1A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cdelt2',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CDELT2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cdelt2a',
            field=models.FloatField(blank=True, help_text='Zero FOV extent', null=True, verbose_name='CDELT2A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cdelt3',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CDELT3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cdelt4',
            field=models.BigIntegerField(blank=True, help_text='Stokes indices [1,2,3,4] --> [I,Q,U,V]', null=True, verbose_name='CDELT4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cdelt5',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CDELT5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cname1',
            field=models.TextField(blank=True, null=True, verbose_name='CNAME1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cname2',
            field=models.TextField(blank=True, null=True, verbose_name='CNAME2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cname3',
            field=models.TextField(blank=True, null=True, verbose_name='CNAME3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cname5',
            field=models.TextField(blank=True, null=True, verbose_name='CNAME5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crpix1',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRPIX1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crpix1a',
            field=models.FloatField(blank=True, help_text='Center pixel of image array', null=True, verbose_name='CRPIX1A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crpix2',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRPIX2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crpix2a',
            field=models.FloatField(blank=True, help_text='Center pixel of image array', null=True, verbose_name='CRPIX2A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crpix3',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRPIX3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crpix4',
            field=models.BigIntegerField(blank=True, help_text='Index of Stokes components in pixel 1', null=True, verbose_name='CRPIX4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crpix5',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRPIX5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crval1',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRVAL1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crval1a',
            field=models.FloatField(blank=True, help_text='Coordinates of center of image array', null=True, verbose_name='CRVAL1A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crval2',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRVAL2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crval2a',
            field=models.FloatField(blank=True, help_text='Coordinates of center of image array', null=True, verbose_name='CRVAL2A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crval3',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRVAL3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crval4',
            field=models.BigIntegerField(blank=True, help_text='The first Stokes index is 1', null=True, verbose_name='CRVAL4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='crval5',
            field=models.BigIntegerField(blank=True, help_text='Unity transform', null=True, verbose_name='CRVAL5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='csyer1',
            field=models.BigIntegerField(blank=True, help_text='Orientation unknown', null=True, verbose_name='CSYER1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='csyer2',
            field=models.BigIntegerField(blank=True, help_text='Orientation unknown', null=True, verbose_name='CSYER2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ctype1',
            field=models.TextField(blank=True, help_text='SOLAR X', null=True, verbose_name='CTYPE1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ctype2',
            field=models.TextField(blank=True, help_text='SOLAR Y', null=True, verbose_name='CTYPE2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ctype3',
            field=models.TextField(blank=True, help_text='Wavelength, function of tuning and scan number', null=True, verbose_name='CTYPE3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ctype4',
            field=models.TextField(blank=True, help_text='Stokes vector [I,Q,U,V]', null=True, verbose_name='CTYPE4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ctype5',
            field=models.TextField(blank=True, help_text='Time, function of tuning and scan number', null=True, verbose_name='CTYPE5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cunit1',
            field=models.TextField(blank=True, help_text='Unit along axis 1', null=True, verbose_name='CUNIT1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cunit2',
            field=models.TextField(blank=True, help_text='Unit along axis 2', null=True, verbose_name='CUNIT2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cunit3',
            field=models.TextField(blank=True, help_text='Wavelength unit, tabulated for dim. 3 and 5', null=True, verbose_name='CUNIT3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cunit5',
            field=models.TextField(blank=True, null=True, verbose_name='CUNIT5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cwdis3',
            field=models.TextField(blank=True, help_text='WAVE distortions in lookup table', null=True, verbose_name='CWDIS3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='cwerr3',
            field=models.FloatField(blank=True, help_text='Max total distortion', null=True, verbose_name='CWERR3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datakurt',
            field=models.FloatField(blank=True, help_text='The kurtosis (provided value)', null=True, verbose_name='DATAKURT'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datamax',
            field=models.FloatField(blank=True, help_text='The maximum data value (provided value)', null=True, verbose_name='DATAMAX'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datamean',
            field=models.FloatField(blank=True, help_text='The average data value (provided value)', null=True, verbose_name='DATAMEAN'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datamedn',
            field=models.FloatField(blank=True, help_text='The median data value (provided value)', null=True, verbose_name='DATAMEDN'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datamin',
            field=models.FloatField(blank=True, help_text='The minimum data value (provided value)', null=True, verbose_name='DATAMIN'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap01',
            field=models.FloatField(blank=True, help_text='The 01 percentile (provided value)', null=True, verbose_name='DATAP01'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap10',
            field=models.FloatField(blank=True, help_text='The 10 percentile (provided value)', null=True, verbose_name='DATAP10'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap25',
            field=models.FloatField(blank=True, help_text='The 25 percentile (provided value)', null=True, verbose_name='DATAP25'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap75',
            field=models.FloatField(blank=True, help_text='The 75 percentile (provided value)', null=True, verbose_name='DATAP75'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap90',
            field=models.FloatField(blank=True, help_text='The 90 percentile (provided value)', null=True, verbose_name='DATAP90'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap95',
            field=models.FloatField(blank=True, help_text='The 95 percentile (provided value)', null=True, verbose_name='DATAP95'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap98',
            field=models.FloatField(blank=True, help_text='The 98 percentile (provided value)', null=True, verbose_name='DATAP98'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datap99',
            field=models.FloatField(blank=True, help_text='The 99 percentile (provided value)', null=True, verbose_name='DATAP99'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='datarms',
            field=models.FloatField(blank=True, help_text='The RMS deviation from the mean (provided value', null=True, verbose_name='DATARMS'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dataskew',
            field=models.FloatField(blank=True, help_text='The skewness (provided value)', null=True, verbose_name='DATASKEW'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Creation UTC date of FITS header', null=True, verbose_name='DATE'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='date_avg',
            field=models.DateTimeField(blank=True, help_text='Average time of observation (provided value)', null=True, verbose_name='DATE-AVG'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='date_obs',
            field=models.DateTimeField(blank=True, help_text='Inferred from directory.', null=True, verbose_name='DATE-OBS'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dateref',
            field=models.DateTimeField(blank=True, help_text='Reference time in ISO-8601', null=True, verbose_name='DATEREF'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='detector',
            field=models.TextField(blank=True, help_text='Inferred from filename.', null=True, verbose_name='DETECTOR'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='detfirm',
            field=models.TextField(blank=True, null=True, verbose_name='DETFIRM'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='detgain',
            field=models.FloatField(blank=True, help_text='or camera specific unit', null=True, verbose_name='DETGAIN'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='detmodel',
            field=models.TextField(blank=True, null=True, verbose_name='DETMODEL'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='detoffs',
            field=models.BigIntegerField(blank=True, help_text='or camera specific unit', null=True, verbose_name='DETOFFS'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_apply',
            field=models.FloatField(blank=True, help_text='Application stage (world coordinates)', null=True, verbose_name='DW3.APPLY'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_associate',
            field=models.FloatField(blank=True, help_text='Association stage (pixel coordinates)', null=True, verbose_name='DW3.ASSOCIATE'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_axis1',
            field=models.BigIntegerField(blank=True, help_text='Spatial X', null=True, verbose_name='DW3 AXIS1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_axis2',
            field=models.BigIntegerField(blank=True, help_text='Spatial Y', null=True, verbose_name='DW3 AXIS2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_axis3',
            field=models.BigIntegerField(blank=True, help_text='Scan number', null=True, verbose_name='DW3 AXIS3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_axis_1',
            field=models.FloatField(blank=True, help_text='Spatial X', null=True, verbose_name='DW3.AXIS.1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_axis_2',
            field=models.FloatField(blank=True, help_text='Spatial Y', null=True, verbose_name='DW3.AXIS.2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_axis_3',
            field=models.FloatField(blank=True, help_text='Scan number', null=True, verbose_name='DW3.AXIS.3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_cwdis_lookup',
            field=models.FloatField(blank=True, help_text='Distortions in lookup table', null=True, verbose_name='DW3.CWDIS.LOOKUP'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_cwerr',
            field=models.FloatField(blank=True, help_text='Max distortion (this correction step)', null=True, verbose_name='DW3 CWERR'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_extver',
            field=models.FloatField(blank=True, help_text='Extension version number', null=True, verbose_name='DW3.EXTVER'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_name',
            field=models.TextField(blank=True, help_text='Type of correction', null=True, verbose_name='DW3 NAME'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='dw3_naxes',
            field=models.BigIntegerField(blank=True, help_text='3 axes in the lookup table', null=True, verbose_name='DW3 NAXES'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='elev_ang',
            field=models.FloatField(blank=True, help_text='Elevation angle (mean value)', null=True, verbose_name='ELEV_ANG'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='extend',
            field=models.BigIntegerField(blank=True, help_text='The file has extension(s).', null=True, verbose_name='EXTEND'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='extname',
            field=models.TextField(blank=True, null=True, verbose_name='EXTNAME'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='filename',
            field=models.TextField(blank=True, null=True, verbose_name='FILENAME'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='filled',
            field=models.BigIntegerField(blank=True, help_text='Missing pixels have been filled.', null=True, verbose_name='FILLED'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='filter1',
            field=models.TextField(blank=True, help_text='Inferred from filename.', null=True, verbose_name='FILTER1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='instrume',
            field=models.TextField(blank=True, help_text='Name of instrument', null=True, verbose_name='INSTRUME'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='longstrn',
            field=models.TextField(blank=True, help_text='The OGIP long string convention may be used.', null=True, verbose_name='LONGSTRN'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='naxis',
            field=models.BigIntegerField(blank=True, help_text='Number of data axes', null=True, verbose_name='NAXIS'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='naxis1',
            field=models.BigIntegerField(blank=True, help_text='Number of positions along axis 1', null=True, verbose_name='NAXIS1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='naxis2',
            field=models.BigIntegerField(blank=True, help_text='Number of positions along axis 2', null=True, verbose_name='NAXIS2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='naxis3',
            field=models.BigIntegerField(blank=True, help_text='Number of positions along axis 3', null=True, verbose_name='NAXIS3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='naxis4',
            field=models.BigIntegerField(blank=True, help_text='Number of positions along axis 4', null=True, verbose_name='NAXIS4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='naxis5',
            field=models.BigIntegerField(blank=True, help_text='Number of positions along axis 5', null=True, verbose_name='NAXIS5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='nsumexp',
            field=models.FloatField(blank=True, help_text='Number of summed exposures (median value)', null=True, verbose_name='NSUMEXP'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='object',
            field=models.TextField(blank=True, null=True, verbose_name='OBJECT'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='obs_hdu',
            field=models.BigIntegerField(blank=True, help_text='Observational Header and Data Unit', null=True, verbose_name='OBS_HDU'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='observer',
            field=models.TextField(blank=True, null=True, verbose_name='OBSERVER'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='obsgeo_x',
            field=models.BigIntegerField(blank=True, help_text='SST location', null=True, verbose_name='OBSGEO-X'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='obsgeo_y',
            field=models.BigIntegerField(blank=True, help_text='SST location', null=True, verbose_name='OBSGEO-Y'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='obsgeo_z',
            field=models.BigIntegerField(blank=True, help_text='SST location', null=True, verbose_name='OBSGEO-Z'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='obsrvtry',
            field=models.TextField(blank=True, help_text='Name of observatory', null=True, verbose_name='OBSRVTRY'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='origin',
            field=models.TextField(blank=True, null=True, verbose_name='ORIGIN'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pc1_1',
            field=models.FloatField(blank=True, help_text='No rotations', null=True, verbose_name='PC1_1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pc2_2',
            field=models.FloatField(blank=True, help_text='No rotations', null=True, verbose_name='PC2_2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pc3_3',
            field=models.FloatField(blank=True, help_text='No rotations', null=True, verbose_name='PC3_3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pc4_4',
            field=models.FloatField(blank=True, help_text='No rotations', null=True, verbose_name='PC4_4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pc5_5',
            field=models.FloatField(blank=True, help_text='No rotations', null=True, verbose_name='PC5_5'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prbra1',
            field=models.TextField(blank=True, help_text='Version control branch', null=True, verbose_name='PRBRA1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prbra2',
            field=models.TextField(blank=True, help_text='Version control branch', null=True, verbose_name='PRBRA2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prbra3',
            field=models.TextField(blank=True, help_text='Version control branch', null=True, verbose_name='PRBRA3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prbra4',
            field=models.TextField(blank=True, help_text='Version control branch', null=True, verbose_name='PRBRA4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib1',
            field=models.TextField(blank=True, help_text='Software library', null=True, verbose_name='PRLIB1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib1a',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB1A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib1b',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB1B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib1c',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB1C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib1d',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB1D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib1e',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB1E'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib2',
            field=models.TextField(blank=True, help_text='Software library containing chromis::make_wb_cu', null=True, verbose_name='PRLIB2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib2a',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB2A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib2b',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB2B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib2c',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB2C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib2d',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB2D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib3',
            field=models.TextField(blank=True, help_text='Software library containing chromis::make_nb_cu', null=True, verbose_name='PRLIB3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib3a',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB3A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib3b',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB3B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib3c',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB3C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib3d',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB3D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib4',
            field=models.TextField(blank=True, help_text='Software library containing red::fitscube_expor', null=True, verbose_name='PRLIB4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib4a',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB4A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib4b',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB4B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib4c',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB4C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prlib4d',
            field=models.TextField(blank=True, help_text='Additional software library', null=True, verbose_name='PRLIB4D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prmode1',
            field=models.TextField(blank=True, help_text='Processing mode', null=True, verbose_name='PRMODE1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prmode2',
            field=models.TextField(blank=True, help_text='Processing mode', null=True, verbose_name='PRMODE2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prmode3',
            field=models.TextField(blank=True, help_text='Processing mode', null=True, verbose_name='PRMODE3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prmode4',
            field=models.TextField(blank=True, help_text='Processing mode', null=True, verbose_name='PRMODE4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prpara1',
            field=models.TextField(blank=True, help_text='List of parameters/options for PRPROC1', null=True, verbose_name='PRPARA1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prpara2',
            field=models.TextField(blank=True, help_text='List of parameters/opt', null=True, verbose_name='PRPARA2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prpara3',
            field=models.TextField(blank=True, help_text='List of parameters/options for PRPROC2', null=True, verbose_name='PRPARA3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prpara4',
            field=models.TextField(blank=True, help_text='List of parameters/options for PRPROC4', null=True, verbose_name='PRPARA4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prproc2',
            field=models.TextField(blank=True, help_text='Name of procedure used', null=True, verbose_name='PRPROC2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prproc3',
            field=models.TextField(blank=True, help_text='Name of procedure used', null=True, verbose_name='PRPROC3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prproc4',
            field=models.TextField(blank=True, help_text='Name of procedure used', null=True, verbose_name='PRPROC4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prstep1',
            field=models.TextField(blank=True, help_text='Processing step name', null=True, verbose_name='PRSTEP1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prstep2',
            field=models.TextField(blank=True, help_text='Processing step name', null=True, verbose_name='PRSTEP2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prstep3',
            field=models.TextField(blank=True, help_text='Processing step name', null=True, verbose_name='PRSTEP3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prstep4',
            field=models.TextField(blank=True, help_text='Processing step name', null=True, verbose_name='PRSTEP4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver1',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver1a',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER1A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver1b',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER1B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver1c',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER1C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver1d',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER1D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver1e',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update (From .momfb', null=True, verbose_name='PRVER1E'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver2',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver2a',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER2A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver2b',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER2B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver2c',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER2C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver2d',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER2D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver3',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver3a',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER3A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver3b',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER3B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver3c',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER3C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver3d',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER3D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver4',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER4'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver4a',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER4A'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver4b',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER4B'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver4c',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER4C'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='prver4d',
            field=models.TextField(blank=True, help_text='Library version/MJD of last update', null=True, verbose_name='PRVER4D'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps1_0',
            field=models.TextField(blank=True, help_text='EXTNAME; EXTVER=EXTLEVEL=1 is default', null=True, verbose_name='PS1_0'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps1_1',
            field=models.TextField(blank=True, help_text='TTYPE for column w/coordinates', null=True, verbose_name='PS1_1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps1_2',
            field=models.TextField(blank=True, help_text='TTYPE for INDEX', null=True, verbose_name='PS1_2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps2_0',
            field=models.TextField(blank=True, help_text='EXTNAME; EXTVER=EXTLEVEL=1 is default', null=True, verbose_name='PS2_0'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps2_1',
            field=models.TextField(blank=True, help_text='TTYPE for column w/coordinates', null=True, verbose_name='PS2_1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps2_2',
            field=models.TextField(blank=True, help_text='TTYPE for INDEX', null=True, verbose_name='PS2_2'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps3_0',
            field=models.TextField(blank=True, help_text='EXTNAME; EXTVER=EXTLEVEL=1 is default', null=True, verbose_name='PS3_0'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps3_1',
            field=models.TextField(blank=True, help_text='TTYPE for column w/coordinates', null=True, verbose_name='PS3_1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps5_0',
            field=models.TextField(blank=True, help_text='EXTNAME; EXTVER=EXTLEVEL=1 is default', null=True, verbose_name='PS5_0'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='ps5_1',
            field=models.TextField(blank=True, help_text='TTYPE for column w/coordinates', null=True, verbose_name='PS5_1'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pv1_3',
            field=models.BigIntegerField(blank=True, help_text='Coord. 1 tabulated coordinate number', null=True, verbose_name='PV1_3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pv2_3',
            field=models.BigIntegerField(blank=True, help_text='Coord. 2 tabulated coordinate number', null=True, verbose_name='PV2_3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pv3_3',
            field=models.BigIntegerField(blank=True, help_text='Coord. 3 tabulated coordinate number', null=True, verbose_name='PV3_3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='pv5_3',
            field=models.BigIntegerField(blank=True, help_text='Coord. 5 tabulated coordinate number', null=True, verbose_name='PV5_3'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='release',
            field=models.TextField(blank=True, null=True, verbose_name='RELEASE'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='releasec',
            field=models.TextField(blank=True, null=True, verbose_name='RELEASEC'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='requestr',
            field=models.TextField(blank=True, null=True, verbose_name='REQUESTR'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='scannum',
            field=models.BigIntegerField(blank=True, help_text='Scan number (first value)', null=True, verbose_name='SCANNUM'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='solarnet',
            field=models.FloatField(blank=True, null=True, verbose_name='SOLARNET'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='startobs',
            field=models.DateTimeField(blank=True, null=True, verbose_name='STARTOBS'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='telconfg',
            field=models.TextField(blank=True, help_text='Telescope configuration', null=True, verbose_name='TELCONFG'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='telescop',
            field=models.TextField(blank=True, help_text='Name of telescope', null=True, verbose_name='TELESCOP'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='texposur',
            field=models.FloatField(blank=True, help_text='Single-exposure time (median value)', null=True, verbose_name='TEXPOSUR'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='timesys',
            field=models.TextField(blank=True, null=True, verbose_name='TIMESYS'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='var_keys',
            field=models.TextField(blank=True, help_text='SOLARNET variable-keywords', null=True, verbose_name='VAR_KEYS'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='waveband',
            field=models.TextField(blank=True, null=True, verbose_name='WAVEBAND'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='wavelnth',
            field=models.FloatField(blank=True, help_text='Prefilter peak wavelength', null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='waveunit',
            field=models.BigIntegerField(blank=True, help_text='WAVELNTH in units 10^WAVEUNIT m = nm', null=True, verbose_name='WAVEUNIT'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='wcsnamea',
            field=models.TextField(blank=True, null=True, verbose_name='WCSNAMEA'),
        ),
        migrations.AddField(
            model_name='chromis',
            name='xposure',
            field=models.FloatField(blank=True, help_text='Summed exposure times (median value)', null=True, verbose_name='XPOSURE'),
        ),
    ]
