# Generated by Django 3.2.13 on 2024-01-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0021_add_aia_level_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aialevel2',
            name='calver32',
        ),
        migrations.RemoveField(
            model_name='aialevel2',
            name='crota2',
        ),
        migrations.RemoveField(
            model_name='aialevel2',
            name='datacent',
        ),
    ]
