# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-29 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_auto_20190723_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chromis',
            name='extend',
        ),
        migrations.RemoveField(
            model_name='crisp',
            name='extend',
        ),
    ]
