# Generated by Django 3.2.4 on 2021-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0024_auto_20191029_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themis',
            name='actifmir',
            field=models.BooleanField(blank=True, help_text='None', null=True, verbose_name='ACTIFMIR'),
        ),
        migrations.AlterField(
            model_name='themis',
            name='beamex',
            field=models.BooleanField(blank=True, help_text='None', null=True, verbose_name='BEAMEX'),
        ),
        migrations.AlterField(
            model_name='themis',
            name='extend',
            field=models.BooleanField(blank=True, help_text='None', null=True, verbose_name='EXTEND'),
        ),
        migrations.AlterField(
            model_name='themis',
            name='offsets',
            field=models.BooleanField(blank=True, help_text='None', null=True, verbose_name='OFFSETS'),
        ),
        migrations.AlterField(
            model_name='themis',
            name='pipeline',
            field=models.BooleanField(blank=True, help_text='None', null=True, verbose_name='PIPELINE'),
        ),
        migrations.AlterField(
            model_name='themis',
            name='yfirst',
            field=models.BooleanField(blank=True, help_text='None', null=True, verbose_name='YFIRST'),
        ),
    ]
