# Generated by Django 3.2.4 on 2021-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0025_auto_20210621_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aialev1',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aialev1',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='chromis',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chromis',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='chrotel',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chrotel',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='crisp',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crisp',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='eit',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eit',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='grislev1',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grislev1',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='hmimagnetogram',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hmimagnetogram',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='ibis',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ibis',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='rosa',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rosa',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='swaplev1',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swaplev1',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='themis',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themis',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
        migrations.AlterField(
            model_name='xrt',
            name='fits_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrt',
            name='oid',
            field=models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID'),
        ),
    ]
