# Generated by Django 3.2.13 on 2024-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0025_update_uset_calciumii_k_level_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='center_x',
        ),
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='center_y',
        ),
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='crota1',
        ),
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='crota2',
        ),
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='fits_header',
        ),
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='gain',
        ),
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='prstep1',
        ),
        migrations.RemoveField(
            model_name='usetwhitelightlevel1',
            name='version',
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='contact',
            field=models.TextField(blank=True, help_text='Contact person at the institution', null=True, verbose_name='CONTACT'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='crota',
            field=models.FloatField(blank=True, help_text='rotation angle', null=True, verbose_name='CROTA'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='doi',
            field=models.TextField(blank=True, help_text='Digital Object Identifier', null=True, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='pc1_1',
            field=models.FloatField(blank=True, help_text='WCS coordinate transformation matrix', null=True, verbose_name='PC1_1'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='pc1_2',
            field=models.FloatField(blank=True, help_text='WCS coordinate transformation matrix', null=True, verbose_name='PC1_2'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='pc2_1',
            field=models.FloatField(blank=True, help_text='WCS coordinate transformation matrix', null=True, verbose_name='PC2_1'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='pc2_2',
            field=models.FloatField(blank=True, help_text='WCS coordinate transformation matrix', null=True, verbose_name='PC2_2'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='physpara',
            field=models.TextField(blank=True, help_text='Physical parameter represented in the data', null=True, verbose_name='PHYSPARA'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='r_error',
            field=models.FloatField(blank=True, help_text='error on the estimated radius', null=True, verbose_name='R_ERROR'),
        ),
        migrations.AddField(
            model_name='usetwhitelightlevel1',
            name='solar_b0',
            field=models.FloatField(blank=True, help_text='tilt of the solar North Pole', null=True, verbose_name='SOLAR_B0'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='btype',
            field=models.TextField(blank=True, help_text='type of data, Unified Content Descriptor', null=True, verbose_name='BTYPE'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='bunit',
            field=models.TextField(blank=True, help_text='unit of physical value', null=True, verbose_name='BUNIT'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='cdelt1',
            field=models.FloatField(blank=True, help_text='pixel scale along axis 1', null=True, verbose_name='CDELT1'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='cdelt2',
            field=models.FloatField(blank=True, help_text='pixel scale along axis 2', null=True, verbose_name='CDELT2'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='creator',
            field=models.TextField(blank=True, help_text='Name of software that produced the FITS', null=True, verbose_name='CREATOR'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='crpix1',
            field=models.FloatField(blank=True, help_text='reference pixel location along axis 1', null=True, verbose_name='CRPIX1'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='crpix2',
            field=models.FloatField(blank=True, help_text='reference pixel location along axis 2', null=True, verbose_name='CRPIX2'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='crval1',
            field=models.BigIntegerField(blank=True, help_text='value of reference pixel along axis 1', null=True, verbose_name='CRVAL1'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='crval2',
            field=models.BigIntegerField(blank=True, help_text='value of reference pixel along axis 2', null=True, verbose_name='CRVAL2'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='cunit1',
            field=models.TextField(blank=True, help_text='units along axis 1', null=True, verbose_name='CUNIT1'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='cunit2',
            field=models.TextField(blank=True, help_text='units along axis 2', null=True, verbose_name='CUNIT2'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='date_obs',
            field=models.DateTimeField(blank=True, help_text='deprecated, same as DATE-BEG', null=True, verbose_name='DATE-OBS'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='extname',
            field=models.TextField(blank=True, help_text='Extention name', null=True, verbose_name='EXTNAME'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='solar_p0',
            field=models.FloatField(blank=True, help_text='celestial North to solar North angle', null=True, verbose_name='SOLAR_P0'),
        ),
        migrations.AlterField(
            model_name='usetwhitelightlevel1',
            name='solar_r',
            field=models.FloatField(blank=True, help_text='estimated radius of the sun', null=True, verbose_name='SOLAR_R'),
        ),
    ]
