# Generated by Django 3.2.13 on 2024-06-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0026_update_uset_white_light_level_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrt',
            name='fits_header',
        ),
    ]
