# Generated by Django 3.2.4 on 2021-06-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

		dependencies = [
				('metadata', '0028_big_auto_field'),
		]

		operations = [
			migrations.RenameModel('AiaLev1', 'AiaLevel1'),
			migrations.RenameModel('Eit', 'EitLevel0'),
			migrations.RenameModel('GrisLev1', 'GrisLevel1'),
			migrations.RenameModel('SwapLev1', 'SwapLevel1'),
		]
