# Generated by Django 3.2.13 on 2025-10-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0002_dataset_doi_url'),
        ('metadata', '0029_add_zimpol_spectrograph_gregor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZimpolSpectrographIrsol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID')),
                ('date_beg', models.DateTimeField(blank=True, db_index=True, help_text='Start time of the observation [UTC]', null=True, verbose_name='DATE-BEG')),
                ('date_end', models.DateTimeField(blank=True, db_index=True, help_text='End time of the observation [UTC]', null=True, verbose_name='DATE-END')),
                ('wavemin', models.FloatField(blank=True, db_index=True, help_text='Min value of the observation spectral range [nm]', null=True, verbose_name='WAVEMIN')),
                ('wavemax', models.FloatField(blank=True, db_index=True, help_text='Max value of the observation spectral range [nm]', null=True, verbose_name='WAVEMAX')),
                ('sun_feature', models.TextField(blank=True, null=True, verbose_name='SUN_FEATURE')),
                ('data_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_zimpolspectrographirsol', to='dataset.datalocation')),
                ('tags', models.ManyToManyField(blank=True, related_name='metadata_zimpolspectrographirsol', to='metadata.Tag')),
            ],
            options={
                'verbose_name': 'ZIMPOL+Spectrograph@IRSOL metadata',
                'verbose_name_plural': 'ZIMPOL+Spectrograph@IRSOL metadata',
                'ordering': ['date_beg'],
                'abstract': False,
            },
        ),
    ]
