# Generated by Django 3.2.4 on 2021-06-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0026_big_auto_field'),
        ('metadata', '0029_rename_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aialevel1',
            name='data_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_aialevel1', to='dataset.datalocation'),
        ),
        migrations.AlterField(
            model_name='aialevel1',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='metadata_aialevel1', to='metadata.Tag'),
        ),
        migrations.AlterField(
            model_name='eitlevel0',
            name='data_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_eitlevel0', to='dataset.datalocation'),
        ),
        migrations.AlterField(
            model_name='eitlevel0',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='metadata_eitlevel0', to='metadata.Tag'),
        ),
        migrations.AlterField(
            model_name='grislevel1',
            name='data_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_grislevel1', to='dataset.datalocation'),
        ),
        migrations.AlterField(
            model_name='grislevel1',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='metadata_grislevel1', to='metadata.Tag'),
        ),
        migrations.AlterField(
            model_name='swaplevel1',
            name='data_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_swaplevel1', to='dataset.datalocation'),
        ),
        migrations.AlterField(
            model_name='swaplevel1',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='metadata_swaplevel1', to='metadata.Tag'),
        ),
    ]
