# Generated by Django 3.2.13 on 2026-04-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0002_dataset_doi_url'),
        ('metadata', '0030_add_zimpol_spectrograph_irsol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpocaCoronalHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID')),
                ('date_beg', models.DateTimeField(blank=True, db_index=True, help_text='Start time of the observation [UTC]', null=True, verbose_name='DATE-BEG')),
                ('date_end', models.DateTimeField(blank=True, db_index=True, help_text='End time of the observation [UTC]', null=True, verbose_name='DATE-END')),
                ('wavemin', models.FloatField(blank=True, db_index=True, help_text='Min value of the observation spectral range [nm]', null=True, verbose_name='WAVEMIN')),
                ('wavemax', models.FloatField(blank=True, db_index=True, help_text='Max value of the observation spectral range [nm]', null=True, verbose_name='WAVEMAX')),
                ('aggregat', models.BigIntegerField(blank=True, help_text='Aggregation factor in arcsec', null=True, verbose_name='AGGREGAT')),
                ('cd1_1', models.FloatField(blank=True, null=True, verbose_name='CD1_1')),
                ('cd1_2', models.FloatField(blank=True, null=True, verbose_name='CD1_2')),
                ('cd2_1', models.FloatField(blank=True, null=True, verbose_name='CD2_1')),
                ('cd2_2', models.FloatField(blank=True, null=True, verbose_name='CD2_2')),
                ('cdelt1', models.FloatField(blank=True, help_text='image scale in the x direction', null=True, verbose_name='CDELT1')),
                ('cdelt2', models.FloatField(blank=True, help_text='image scale in the y direction', null=True, verbose_name='CDELT2')),
                ('cfuzfier', models.FloatField(blank=True, help_text='the fuzzifier exponent', null=True, verbose_name='CFUZFIER')),
                ('channels', models.TextField(blank=True, null=True, verbose_name='CHANNELS')),
                ('clastype', models.TextField(blank=True, help_text='the type of classifier', null=True, verbose_name='CLASTYPE')),
                ('cleaning', models.BigIntegerField(blank=True, help_text='Cleaning factor in arcsec', null=True, verbose_name='CLEANING')),
                ('clsctr01', models.TextField(blank=True, help_text='value of the center of class 1', null=True, verbose_name='CLSCTR01')),
                ('clsctr02', models.TextField(blank=True, help_text='value of the center of class 2', null=True, verbose_name='CLSCTR02')),
                ('clsctr03', models.TextField(blank=True, help_text='value of the center of class 3', null=True, verbose_name='CLSCTR03')),
                ('clsctr04', models.TextField(blank=True, help_text='value of the center of class 4', null=True, verbose_name='CLSCTR04')),
                ('cmaxiter', models.BigIntegerField(blank=True, help_text='maximal number of iteration for the classification', null=True, verbose_name='CMAXITER')),
                ('cnbrclas', models.BigIntegerField(blank=True, help_text='number of classes', null=True, verbose_name='CNBRCLAS')),
                ('cprecis', models.FloatField(blank=True, help_text='precision to be reached to stop the classification', null=True, verbose_name='CPRECIS')),
                ('cpreproc', models.TextField(blank=True, help_text='preprocessing steps to apply to the sun images', null=True, verbose_name='CPREPROC')),
                ('crln_obs', models.FloatField(blank=True, help_text='Carrington longitude of the observer', null=True, verbose_name='CRLN_OBS')),
                ('crpix1', models.FloatField(blank=True, help_text='location of sun center in CCD x direction', null=True, verbose_name='CRPIX1')),
                ('crpix2', models.FloatField(blank=True, help_text='location of sun center in CCD y direction', null=True, verbose_name='CRPIX2')),
                ('ctype1', models.TextField(blank=True, null=True, verbose_name='CTYPE1')),
                ('ctype2', models.TextField(blank=True, null=True, verbose_name='CTYPE2')),
                ('cunit1', models.TextField(blank=True, null=True, verbose_name='CUNIT1')),
                ('cunit2', models.TextField(blank=True, null=True, verbose_name='CUNIT2')),
                ('date_obs', models.DateTimeField(blank=True, help_text='date when observation started', null=True, verbose_name='DATE_OBS')),
                ('dsun_obs', models.FloatField(blank=True, help_text='Distance from SDO to Sun center', null=True, verbose_name='DSUN_OBS')),
                ('extname', models.TextField(blank=True, null=True, verbose_name='EXTNAME')),
                ('fraggmtd', models.BooleanField(blank=True, help_text='Regions are fragmented', null=True, verbose_name='FRAGGMTD')),
                ('hgln_obs', models.FloatField(blank=True, help_text='Stonyhurst heliographic longitude of the observer', null=True, verbose_name='HGLN_OBS')),
                ('hglt_obs', models.FloatField(blank=True, help_text='Stonyhurst heliographic latitude of the observer', null=True, verbose_name='HGLT_OBS')),
                ('image001', models.TextField(blank=True, help_text='name of the image of the first channel', null=True, verbose_name='IMAGE001')),
                ('instrume', models.TextField(blank=True, help_text='SPoCA coronal region map', null=True, verbose_name='INSTRUME')),
                ('minsize', models.BigIntegerField(blank=True, help_text='Min size of regions in arcsec', null=True, verbose_name='MINSIZE')),
                ('naxis', models.BigIntegerField(blank=True, help_text='dimension of original image', null=True, verbose_name='NAXIS')),
                ('naxis1', models.BigIntegerField(blank=True, help_text='length of original image axis', null=True, verbose_name='NAXIS1')),
                ('naxis2', models.BigIntegerField(blank=True, help_text='length of original image axis', null=True, verbose_name='NAXIS2')),
                ('projectn', models.TextField(blank=True, help_text='Projection used for the cleaning and aggregation', null=True, verbose_name='PROJECTN')),
                ('rsun_obs', models.FloatField(blank=True, help_text='Apparent radius of the Sun seen by SDO', null=True, verbose_name='RSUN_OBS')),
                ('rsun_ref', models.FloatField(blank=True, help_text='Reference radius of the Sun', null=True, verbose_name='RSUN_REF')),
                ('segmtype', models.TextField(blank=True, help_text='type of segmentation', null=True, verbose_name='SEGMTYPE')),
                ('telescop', models.TextField(blank=True, null=True, verbose_name='TELESCOP')),
                ('thrawar', models.BooleanField(blank=True, help_text='Min size threshold on raw area', null=True, verbose_name='THRAWAR')),
                ('data_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_spocacoronalhole', to='dataset.datalocation')),
                ('tags', models.ManyToManyField(blank=True, related_name='metadata_spocacoronalhole', to='metadata.Tag')),
            ],
            options={
                'verbose_name': 'SPoCA Coronal Hole metadata',
                'verbose_name_plural': 'SPoCA Coronal Hole metadata',
                'ordering': ['date_beg'],
                'abstract': False,
            },
        ),
    ]
