# Generated by Django 3.2.13 on 2026-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0031_add_spoca_coronal_hole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aialevel15',
            name='wavelnth',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Wavelength', null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AlterField(
            model_name='eitlevel0',
            name='sci_obj',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='SCI_OBJ'),
        ),
        migrations.AlterField(
            model_name='eitlevel0',
            name='wavelnth',
            field=models.IntegerField(blank=True, db_index=True, help_text='Wavelength 284 / 171 = Fe IX/X, 195 = Fe XII, / 284 = Fe XV, 304 = He ', null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AlterField(
            model_name='euilevel1',
            name='compress',
            field=models.TextField(blank=True, db_index=True, help_text='data compression quality (None/Lossless/Lossy)', null=True, verbose_name='COMPRESS'),
        ),
        migrations.AlterField(
            model_name='euilevel1',
            name='detector',
            field=models.TextField(blank=True, db_index=True, help_text='instrument subunit or sensor', null=True, verbose_name='DETECTOR'),
        ),
        migrations.AlterField(
            model_name='euilevel1',
            name='wavelnth',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='characteristic wavelength observation', null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AlterField(
            model_name='euilevel2',
            name='compress',
            field=models.TextField(blank=True, db_index=True, help_text='data compression quality (None/Lossless/Lossy)', null=True, verbose_name='COMPRESS'),
        ),
        migrations.AlterField(
            model_name='euilevel2',
            name='detector',
            field=models.TextField(blank=True, db_index=True, help_text='instrument subunit or sensor', null=True, verbose_name='DETECTOR'),
        ),
        migrations.AlterField(
            model_name='euilevel2',
            name='wavelnth',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='characteristic wavelength observation', null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AlterField(
            model_name='euvilevel0',
            name='obsrvtry',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='OBSRVTRY'),
        ),
        migrations.AlterField(
            model_name='euvilevel0',
            name='wavelnth',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='WAVELNTH'),
        ),
        migrations.AlterField(
            model_name='gaiadem',
            name='granule_gid',
            field=models.TextField(blank=True, db_index=True, help_text='Common to granules of same type (e.g. same map projection, or geometry data products). Can be alphanumeric.', null=True, verbose_name='granule_gid'),
        ),
        migrations.AlterField(
            model_name='swaplevel1',
            name='obs_mode',
            field=models.TextField(blank=True, db_index=True, help_text='sun_cen, fix_off, var_off, cme_track', null=True, verbose_name='OBS_MODE'),
        ),
    ]
