# Generated by Django 3.2.13 on 2026-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0033_add_crisp2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromis',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='crisp',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='eitlevel0',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='euilevel1',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='euilevel2',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='euvilevel0',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='ibis',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='lyralevel2',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='lyralevel3',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
        migrations.AlterField(
            model_name='swaplevel1',
            name='fits_header',
            field=models.TextField(blank=True, help_text='Header of the relevant HDU in the FITS file', null=True, verbose_name='FITS header'),
        ),
    ]
