# Generated by Django 3.2.13 on 2026-05-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0034_updated_fitsheader_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xrt',
        ),
    ]
