# Generated by Django 3.2.13 on 2026-08-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0043_update_eui_datasets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grislevel1',
            name='accumula',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='adunorm',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='aosystem',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='azimut',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='b0angle',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='bscale',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='bzero',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='campos',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefi_1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefi_2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefi_3',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefi_4',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefq_1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefq_2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefq_3',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefq_4',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefu_1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefu_2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefu_3',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefu_4',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefv_1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefv_2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefv_3',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='coefv_4',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='colpos',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='datafram',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='datavers',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='date_obs',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='dec',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='eimgacc',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='elevatio',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='elperadu',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='exptime',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='filestat',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='fullfram',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='gratangl',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='hourangl',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='ifile',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='imagtype',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='irfilter',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='iserie',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='l0angle',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc1_1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc1_2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc1_3',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc1_4',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc2_1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc2_2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc2_3',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lc2_4',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='lcs',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='naxis',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='naxis1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='naxis2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='naxis3',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='nfiles',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='p0angle',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='paraangl',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='r0radius',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='rotangle',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='rotcode',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='series',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='spsystem',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='states',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='stepangl',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='stepsh',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='stepsize',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='stepsv',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='telescop',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='temp_lc1',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='temp_lc2',
        ),
        migrations.RemoveField(
            model_name='grislevel1',
            name='waveleng',
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='access_estsize',
            field=models.BigIntegerField(blank=True, help_text='Estimated file size in kbyte.', null=True, verbose_name='access_estsize'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='access_format',
            field=models.TextField(blank=True, help_text='File format type (RFC 6838 Media Type a.k.a. MIME type)', null=True, verbose_name='access_format'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='access_url',
            field=models.TextField(blank=True, help_text='URL of the data file, case sensitive. If present, then access_format and access_estsize are mandatory.', null=True, verbose_name='access_url'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='bib_reference',
            field=models.TextField(blank=True, help_text='Bibcode or DOI preferred if available, or other bibliographic identifier or URL', null=True, verbose_name='bib_reference'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c1_resol_max',
            field=models.FloatField(blank=True, help_text='Resolution in the first coordinate, upper limit', null=True, verbose_name='c1_resol_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c1_resol_min',
            field=models.FloatField(blank=True, help_text='Resolution in the first coordinate, lower limit.', null=True, verbose_name='c1_resol_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c1max',
            field=models.FloatField(blank=True, help_text='Longitude on body, upper limit', null=True, verbose_name='c1max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c1min',
            field=models.FloatField(blank=True, help_text='Longitude on body, lower limit.', null=True, verbose_name='c1min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c2_resol_max',
            field=models.FloatField(blank=True, help_text='Resolution in the second coordinate, upper limit', null=True, verbose_name='c2_resol_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c2_resol_min',
            field=models.FloatField(blank=True, help_text='Resolution in the second coordinate, lower limit.', null=True, verbose_name='c2_resol_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c2max',
            field=models.FloatField(blank=True, help_text='Latitude on body, upper limit', null=True, verbose_name='c2max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c2min',
            field=models.FloatField(blank=True, help_text='Latitude on body, lower limit.', null=True, verbose_name='c2min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c3_resol_max',
            field=models.FloatField(blank=True, help_text='Resolution in the third coordinate, upper limit', null=True, verbose_name='c3_resol_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c3_resol_min',
            field=models.FloatField(blank=True, help_text='Resolution in the third coordinate, lower limit.', null=True, verbose_name='c3_resol_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c3max',
            field=models.FloatField(blank=True, help_text='Altitude from reference surface, upper limit', null=True, verbose_name='c3max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='c3min',
            field=models.FloatField(blank=True, help_text='Altitude from reference surface, lower limit.', null=True, verbose_name='c3min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='creation_date',
            field=models.DateTimeField(blank=True, help_text='Date of first entry of this granule', null=True, verbose_name='creation_date'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='dataproduct_type',
            field=models.TextField(blank=True, help_text="The high-level organization of the data product, from a controlled vocabulary (e.g., 'im' for image, sp for spectrum). Multiple terms may be used, separated by # characters.", null=True, verbose_name='dataproduct_type'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='emergence_max',
            field=models.FloatField(blank=True, help_text='Emergence angle during data acquisition, upper limit', null=True, verbose_name='emergence_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='emergence_min',
            field=models.FloatField(blank=True, help_text='Emergence angle during data acquisition, lower limit.', null=True, verbose_name='emergence_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='file_name',
            field=models.TextField(blank=True, help_text='Name of the data file only, case sensitive', null=True, verbose_name='file_name'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='filter',
            field=models.TextField(blank=True, help_text='Identifies filter in use, typically for images', null=True, verbose_name='filter'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='granule_gid',
            field=models.TextField(blank=True, help_text='Common to granules of same type (e.g. same map projection, or geometry data products). Can be alphanumeric.', null=True, verbose_name='granule_gid'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='granule_uid',
            field=models.TextField(blank=True, help_text='Internal table row index, which must be unique within the table. Can be alphanumeric.', null=True, verbose_name='granule_uid'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='incidence_max',
            field=models.FloatField(blank=True, help_text='Incidence angle (solar zenithal angle) during data acquisition, upper limit', null=True, verbose_name='incidence_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='incidence_min',
            field=models.FloatField(blank=True, help_text='Incidence angle (solar zenithal angle) during data acquisition, lower limit.', null=True, verbose_name='incidence_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='instrument_host_name',
            field=models.TextField(blank=True, help_text='Standard name of the observatory or spacecraft', null=True, verbose_name='instrument_host_name'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='instrument_name',
            field=models.TextField(blank=True, help_text='Standard name of instrument', null=True, verbose_name='instrument_name'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='measurement_type',
            field=models.TextField(blank=True, help_text='UCD(s) defining the data, with multiple entries separated by hash (#) characters.', null=True, verbose_name='measurement_type'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='modification_date',
            field=models.DateTimeField(blank=True, help_text='Date of last modification (used to handle mirroring)', null=True, verbose_name='modification_date'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='obs_id',
            field=models.TextField(blank=True, help_text='Associates granules derived from the same data (e.g. various representations/processing levels). Can be alphanumeric, may be the ID of original observation.', null=True, verbose_name='obs_id'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='obs_mode',
            field=models.TextField(blank=True, help_text='Observing mode', null=True, verbose_name='obs_mode'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='phase_max',
            field=models.FloatField(blank=True, help_text='Phase angle during data acquisition, upper limit', null=True, verbose_name='phase_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='phase_min',
            field=models.FloatField(blank=True, help_text='Phase angle during data acquisition, lower limit.', null=True, verbose_name='phase_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='processing_level',
            field=models.BigIntegerField(blank=True, help_text='Dataset-related encoding, or simplified CODMAC calibration level', null=True, verbose_name='processing_level'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='publisher',
            field=models.TextField(blank=True, help_text='A short string identifying the entity running the data service used', null=True, verbose_name='publisher'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Start of public access period', null=True, verbose_name='release_date'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='s_region',
            field=models.TextField(blank=True, help_text='ObsCore-like footprint, valid for celestial, spherical, or body-fixed frames', null=True, verbose_name='s_region'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='service_title',
            field=models.TextField(blank=True, help_text='Title of resource (an acronym really, will be used to handle multiservice results)', null=True, verbose_name='service_title'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spatial_coordinate_description',
            field=models.TextField(blank=True, help_text='ID or specific coordinate system and version', null=True, verbose_name='spatial_coordinate_description'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spatial_frame_type',
            field=models.TextField(blank=True, help_text="Flavor of coordinate system, defines the nature of coordinates. From a controlled vocabulary, where 'none' means undefined.", null=True, verbose_name='spatial_frame_type'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spatial_origin',
            field=models.TextField(blank=True, help_text='Defines the frame origin', null=True, verbose_name='spatial_origin'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spectral_range_max',
            field=models.FloatField(blank=True, help_text='Spectral range (frequency), upper limit', null=True, verbose_name='spectral_range_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spectral_range_min',
            field=models.FloatField(blank=True, help_text='Spectral range (frequency), lower limit.', null=True, verbose_name='spectral_range_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spectral_resolution_max',
            field=models.FloatField(blank=True, help_text='Spectral resolution, upper limit', null=True, verbose_name='spectral_resolution_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spectral_resolution_min',
            field=models.FloatField(blank=True, help_text='Spectral resolution, lower limit.', null=True, verbose_name='spectral_resolution_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spectral_sampling_step_max',
            field=models.FloatField(blank=True, help_text='Spectral sampling step, upper limit', null=True, verbose_name='spectral_sampling_step_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='spectral_sampling_step_min',
            field=models.FloatField(blank=True, help_text='Spectral sampling step, lower limit.', null=True, verbose_name='spectral_sampling_step_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='target_class',
            field=models.TextField(blank=True, help_text='Type of target, from a controlled vocabulary.', null=True, verbose_name='target_class'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='target_name',
            field=models.TextField(blank=True, help_text='Standard IAU name of target (from a list related to target class), case sensitive', null=True, verbose_name='target_name'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='thumbnail_url',
            field=models.TextField(blank=True, help_text='URL of a thumbnail image with predefined size (png ~200 pix, for use in a client only)', null=True, verbose_name='thumbnail_url'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='time_exp_max',
            field=models.FloatField(blank=True, help_text='Integration time of the measurement, upper limit', null=True, verbose_name='time_exp_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='time_exp_min',
            field=models.FloatField(blank=True, help_text='Integration time of the measurement, lower limit.', null=True, verbose_name='time_exp_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='time_max',
            field=models.FloatField(blank=True, help_text='Acquisition stop time (in JD), as UTC at time_refposition', null=True, verbose_name='time_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='time_min',
            field=models.FloatField(blank=True, help_text='Acquisition start time (in JD), as UTC at time_refposition', null=True, verbose_name='time_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='time_sampling_step_max',
            field=models.FloatField(blank=True, help_text='Sampling time for measurements of dynamical phenomena, upper limit', null=True, verbose_name='time_sampling_step_max'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='time_sampling_step_min',
            field=models.FloatField(blank=True, help_text='Sampling time for measurements of dynamical phenomena, lower limit.', null=True, verbose_name='time_sampling_step_min'),
        ),
        migrations.AddField(
            model_name='grislevel1',
            name='time_scale',
            field=models.TextField(blank=True, help_text='Defaults to UTC in data services; takes values from http://www.ivoa.net/rdf/time_scale otherwise', null=True, verbose_name='time_scale'),
        ),
    ]
