# Generated by Django 3.2.13 on 2026-08-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0047_updated_euvi_level_0_with_constants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eitlevel0',
            name='datasrc',
        ),
        migrations.RemoveField(
            model_name='eitlevel0',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='eitlevel0',
            name='image_of_seq',
        ),
        migrations.RemoveField(
            model_name='eitlevel0',
            name='instrume',
        ),
        migrations.RemoveField(
            model_name='eitlevel0',
            name='leb_proc',
        ),
        migrations.RemoveField(
            model_name='eitlevel0',
            name='line_sync',
        ),
        migrations.RemoveField(
            model_name='eitlevel0',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='eitlevel0',
            name='telescop',
        ),
    ]
