# Generated by Django 3.2.13 on 2026-08-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0048_updated_eit_level_0_with_constants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aialevel15',
            name='crota2',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='crpix1',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='crpix2',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='crval1',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='crval2',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='ctype1',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='ctype2',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='cunit1',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='cunit2',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='dsun_ref',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='gcount',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='lvl_num',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='naxis',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='naxis1',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='naxis2',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='pcount',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='rsun_ref',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='telescop',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='totvals',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='trecepoc',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='trecstep',
        ),
        migrations.RemoveField(
            model_name='aialevel15',
            name='waveunit',
        ),
    ]
