# Generated by Django 3.2.13 on 2026-09-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0003_add_keyword_constant_value'),
        ('metadata', '0050_updated_eit_synoptic_with_constants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co5BoldIrsol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID')),
                ('date_beg', models.DateTimeField(blank=True, db_index=True, help_text='Start time of the observation [UTC]', null=True, verbose_name='DATE-BEG')),
                ('date_end', models.DateTimeField(blank=True, db_index=True, help_text='End time of the observation [UTC]', null=True, verbose_name='DATE-END')),
                ('wavemin', models.FloatField(blank=True, db_index=True, help_text='Min value of the observation spectral range [nm]', null=True, verbose_name='WAVEMIN')),
                ('wavemax', models.FloatField(blank=True, db_index=True, help_text='Max value of the observation spectral range [nm]', null=True, verbose_name='WAVEMAX')),
                ('cadence', models.FloatField(blank=True, help_text='mean gap between published snapshots [s]', null=True, verbose_name='CADENCE')),
                ('cdelt1', models.FloatField(blank=True, help_text='step per pixel', null=True, verbose_name='CDELT1')),
                ('cdelt2', models.FloatField(blank=True, help_text='step per pixel', null=True, verbose_name='CDELT2')),
                ('cdelt3', models.FloatField(blank=True, help_text='step per pixel', null=True, verbose_name='CDELT3')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='COMMENT')),
                ('creator', models.TextField(blank=True, null=True, verbose_name='CREATOR')),
                ('crpix1', models.BigIntegerField(blank=True, help_text='reference pixel', null=True, verbose_name='CRPIX1')),
                ('crpix2', models.BigIntegerField(blank=True, help_text='reference pixel', null=True, verbose_name='CRPIX2')),
                ('crpix3', models.BigIntegerField(blank=True, help_text='reference pixel', null=True, verbose_name='CRPIX3')),
                ('crval1', models.FloatField(blank=True, help_text='value at reference pixel', null=True, verbose_name='CRVAL1')),
                ('crval2', models.FloatField(blank=True, help_text='value at reference pixel', null=True, verbose_name='CRVAL2')),
                ('crval3', models.FloatField(blank=True, help_text='value at reference pixel', null=True, verbose_name='CRVAL3')),
                ('ctype1', models.TextField(blank=True, help_text='axis 1 = x', null=True, verbose_name='CTYPE1')),
                ('ctype2', models.TextField(blank=True, help_text='axis 2 = y', null=True, verbose_name='CTYPE2')),
                ('ctype3', models.TextField(blank=True, help_text='axis 3 = z', null=True, verbose_name='CTYPE3')),
                ('cunit1', models.TextField(blank=True, help_text='unit of x', null=True, verbose_name='CUNIT1')),
                ('cunit2', models.TextField(blank=True, help_text='unit of y', null=True, verbose_name='CUNIT2')),
                ('cunit3', models.TextField(blank=True, help_text='unit of z', null=True, verbose_name='CUNIT3')),
                ('elapsed', models.FloatField(blank=True, help_text='simulated time since snapshot 0 [s]', null=True, verbose_name='ELAPSED')),
                ('extend', models.BooleanField(blank=True, null=True, verbose_name='EXTEND')),
                ('extname', models.TextField(blank=True, null=True, verbose_name='EXTNAME')),
                ('naxis', models.BigIntegerField(blank=True, help_text='number of array dimensions', null=True, verbose_name='NAXIS')),
                ('observer', models.TextField(blank=True, null=True, verbose_name='OBSERVER')),
                ('obsrvtry', models.TextField(blank=True, help_text='Istituto Ricerche Solari Locarno Switzerland', null=True, verbose_name='OBSRVTRY')),
                ('point_id', models.TextField(blank=True, help_text='one-off simulation, same as SMLATION', null=True, verbose_name='POINT_ID')),
                ('settings', models.TextField(blank=True, help_text='input parameters', null=True, verbose_name='SETTINGS')),
                ('sim_hdu', models.BigIntegerField(blank=True, help_text='1 = simulation data (not observation)', null=True, verbose_name='SIM_HDU')),
                ('sim_nx', models.BigIntegerField(blank=True, help_text='grid points in x (hdf5: x1)', null=True, verbose_name='SIM_NX')),
                ('sim_ny', models.BigIntegerField(blank=True, help_text='grid points in y (hdf5: x2)', null=True, verbose_name='SIM_NY')),
                ('sim_nz', models.BigIntegerField(blank=True, help_text='grid points in z (hdf5: x3)', null=True, verbose_name='SIM_NZ')),
                ('smlation', models.TextField(blank=True, help_text='unique simulation identifier', null=True, verbose_name='SMLATION')),
                ('snapshot', models.BigIntegerField(blank=True, help_text='snapshot number', null=True, verbose_name='SNAPSHOT')),
                ('solarnet', models.FloatField(blank=True, help_text='file is solarnet compliant', null=True, verbose_name='SOLARNET')),
                ('target', models.TextField(blank=True, null=True, verbose_name='TARGET')),
                ('ztau51', models.FloatField(blank=True, help_text='height of optical depth unity at 500nm', null=True, verbose_name='ZTAU51')),
                ('data_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_co5boldirsol', to='dataset.datalocation')),
                ('tags', models.ManyToManyField(blank=True, related_name='metadata_co5boldirsol', to='metadata.Tag')),
            ],
            options={
                'verbose_name': 'CO5BOLD@IRSOL metadata',
                'verbose_name_plural': 'CO5BOLD@IRSOL metadata',
                'ordering': ['date_beg'],
                'abstract': False,
            },
        ),
    ]
