# Generated by Django 3.2.13 on 2026-09-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0053_update_xrt_level_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrtlevel0',
            name='data_location',
        ),
        migrations.RemoveField(
            model_name='xrtlevel0',
            name='tags',
        ),
        migrations.DeleteModel(
            name='AiaLevel1',
        ),
        migrations.DeleteModel(
            name='XrtLevel0',
        ),
    ]
