# Generated by Django 3.2.13 on 2026-09-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('metadata', '0054_removed_aialevel1_xrtlevel0'),
	]

	operations = [
		migrations.RenameModel(
			old_name='LsoCompSLevel1',
			new_name='CompSLevel1',
		),
		migrations.RunSQL(
			sql=[
				"ALTER SEQUENCE metadata_lsocompslevel1_id_seq RENAME TO metadata_compslevel1_id_seq;",
				"ALTER SEQUENCE metadata_lsocompslevel1_tags_id_seq RENAME TO metadata_compslevel1_tags_id_seq;",
			],
			reverse_sql=[
				"ALTER SEQUENCE metadata_compslevel1_id_seq RENAME TO metadata_lsocompslevel1_id_seq;",
				"ALTER SEQUENCE metadata_compslevel1_tags_id_seq RENAME TO metadata_lsocompslevel1_tags_id_seq;",
			],
		),
	]
