# Generated by Django 3.2.13 on 2026-09-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0003_add_keyword_constant_value'),
        ('metadata', '0055_rename_lsocompslevel1_to_compslevel1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compslevel1',
            options={'ordering': ['date_beg'], 'verbose_name': 'CoMP-S level 1 metadata', 'verbose_name_plural': 'CoMP-S level 1 metadata'},
        ),
        migrations.AlterField(
            model_name='compslevel1',
            name='data_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_compslevel1', to='dataset.datalocation'),
        ),
        migrations.AlterField(
            model_name='compslevel1',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='metadata_compslevel1', to='metadata.Tag'),
        ),
    ]
