# Generated by Django 3.2.13 on 2026-09-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0003_add_keyword_constant_value'),
        ('metadata', '0056_fix_comp_s_level_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbisLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.TextField(db_index=True, help_text='Unique identification string for the observation metadata, usually in the form YYYYMMDDHHMMSS; cannot be modified once it is set', unique=True, verbose_name='Observation ID')),
                ('date_beg', models.DateTimeField(blank=True, db_index=True, help_text='Start time of the observation [UTC]', null=True, verbose_name='DATE-BEG')),
                ('date_end', models.DateTimeField(blank=True, db_index=True, help_text='End time of the observation [UTC]', null=True, verbose_name='DATE-END')),
                ('wavemin', models.FloatField(blank=True, db_index=True, help_text='Min value of the observation spectral range [nm]', null=True, verbose_name='WAVEMIN')),
                ('wavemax', models.FloatField(blank=True, db_index=True, help_text='Max value of the observation spectral range [nm]', null=True, verbose_name='WAVEMAX')),
                ('btype', models.TextField(blank=True, help_text='Description of what the data array represents', null=True, verbose_name='BTYPE')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='COMMENT')),
                ('date', models.DateTimeField(blank=True, help_text='Date of FITS file creation', null=True, verbose_name='DATE')),
                ('dst_see', models.FloatField(blank=True, help_text='Mean Seykora scintillation monitor valu', null=True, verbose_name='DST_SEE')),
                ('dst_slat', models.FloatField(blank=True, help_text='Stonyhurst Heliographic solar lat.', null=True, verbose_name='DST_SLAT')),
                ('dst_slng', models.FloatField(blank=True, help_text='Stonyhurst Heliographic solar long.', null=True, verbose_name='DST_SLNG')),
                ('extend', models.BooleanField(blank=True, help_text='FITS data may contain extensions', null=True, verbose_name='EXTEND')),
                ('extname', models.TextField(blank=True, help_text='Name of HDU', null=True, verbose_name='EXTNAME')),
                ('info_url', models.TextField(blank=True, help_text='IBIS archive web page', null=True, verbose_name='INFO_URL')),
                ('instrume', models.TextField(blank=True, help_text='Name of instrument', null=True, verbose_name='INSTRUME')),
                ('level', models.DateTimeField(blank=True, help_text='Data level of FITS file', null=True, verbose_name='LEVEL')),
                ('naxis', models.BigIntegerField(blank=True, help_text='Number of data axes', null=True, verbose_name='NAXIS')),
                ('obs_hdu', models.BigIntegerField(blank=True, help_text='This HDU contains observational data', null=True, verbose_name='OBS_HDU')),
                ('obs_mode', models.TextField(blank=True, help_text='settings used during obs.', null=True, verbose_name='OBS_MODE')),
                ('obsrvtry', models.TextField(blank=True, help_text='Name of observatory', null=True, verbose_name='OBSRVTRY')),
                ('origin', models.TextField(blank=True, help_text='Creator of FITS files', null=True, verbose_name='ORIGIN')),
                ('prproc1', models.TextField(blank=True, help_text='Name of procedure used written in IDL', null=True, verbose_name='PRPROC1')),
                ('prproc2', models.TextField(blank=True, help_text='Name of procedure used written in IDL', null=True, verbose_name='PRPROC2')),
                ('prproc3', models.TextField(blank=True, help_text='Name of procedure used written in IDL', null=True, verbose_name='PRPROC3')),
                ('prproc4', models.TextField(blank=True, help_text='Name of procedure used written in IDL', null=True, verbose_name='PRPROC4')),
                ('prproc5', models.TextField(blank=True, help_text='Name of procedure used written in IDL', null=True, verbose_name='PRPROC5')),
                ('prproc6', models.TextField(blank=True, help_text='Name of procedure used', null=True, verbose_name='PRPROC6')),
                ('prstep1', models.TextField(blank=True, help_text='Bias, dark and flatfielding correction', null=True, verbose_name='PRSTEP1')),
                ('prstep2', models.TextField(blank=True, help_text='Blueshift and gain correction', null=True, verbose_name='PRSTEP2')),
                ('prstep3', models.TextField(blank=True, help_text='MOMFBD output', null=True, verbose_name='PRSTEP3')),
                ('prstep4', models.TextField(blank=True, null=True, verbose_name='PRSTEP4')),
                ('prstep5', models.TextField(blank=True, null=True, verbose_name='PRSTEP5')),
                ('prstep6', models.TextField(blank=True, help_text='Processing step', null=True, verbose_name='PRSTEP6')),
                ('px_scale', models.TextField(blank=True, help_text='Pixel scale of the image', null=True, verbose_name='PX_SCALE')),
                ('rsun_arc', models.FloatField(blank=True, help_text='Apparent photospheric Solar radius', null=True, verbose_name='RSUN_ARC')),
                ('scan_dur', models.FloatField(blank=True, help_text='Time required for line scan', null=True, verbose_name='SCAN_DUR')),
                ('solar_b0', models.FloatField(blank=True, help_text='Solar B0 angle', null=True, verbose_name='SOLAR B0')),
                ('solar_l0', models.FloatField(blank=True, help_text='Solar L0 angle', null=True, verbose_name='SOLAR L0')),
                ('solar_p0', models.FloatField(blank=True, help_text='Solar P angle', null=True, verbose_name='SOLAR P0')),
                ('solarnet', models.FloatField(blank=True, help_text='Fully SOLARNET-compliant=1.0, partially=0.5', null=True, verbose_name='SOLARNET')),
                ('telescop', models.TextField(blank=True, help_text='Name of the telescope', null=True, verbose_name='TELESCOP')),
                ('timesys', models.TextField(blank=True, null=True, verbose_name='TIMESYS')),
                ('waveband', models.TextField(blank=True, help_text='PRE-FILTER name', null=True, verbose_name='WAVEBAND')),
                ('data_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_ibislevel2', to='dataset.datalocation')),
                ('tags', models.ManyToManyField(blank=True, related_name='metadata_ibislevel2', to='metadata.Tag')),
            ],
            options={
                'verbose_name': 'IBIS level 2 metadata',
                'verbose_name_plural': 'IBIS level 2 metadata',
                'ordering': ['date_beg'],
                'abstract': False,
            },
        ),
    ]
