# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_account', '0001_initial'),
        ('data_selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSelectionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name of the data selection group')),
                ('created', models.DateTimeField(verbose_name='Date of creation')),
                ('updated', models.DateTimeField(verbose_name='Date of last update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_account.User')),
            ],
            options={
                'ordering': ['-updated'],
                'db_table': 'data_selection_group',
                'get_latest_by': 'updated',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userdataselection',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userdataselection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataselection',
            name='metadata_oids',
        ),
        migrations.RemoveField(
            model_name='dataselection',
            name='user_data_selection',
        ),
        migrations.AddField(
            model_name='dataselection',
            name='query',
            field=picklefield.fields.PickledObjectField(default=None, editable=False, verbose_name='Django QuerySet query'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataselection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='dataselection',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_selections', related_query_name='data_selection', to='dataset.Dataset'),
        ),
        migrations.AlterField(
            model_name='dataselection',
            name='number_items',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of items in the data selection'),
        ),
        migrations.AlterField(
            model_name='dataselection',
            name='query_string',
            field=models.TextField(blank=True, null=True, verbose_name='Query string for the data selection'),
        ),
        migrations.DeleteModel(
            name='UserDataSelection',
        ),
        migrations.AddField(
            model_name='dataselection',
            name='data_selection_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_selections', to='data_selection.DataSelectionGroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dataselectiongroup',
            unique_together=set([('user', 'name')]),
        ),
    ]
