# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-22 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_selection', '0002_auto_20160518_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataselectiongroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_selection_groups', related_query_name='data_selection_group', to='web_account.User'),
        ),
    ]
