# Generated by Django 3.2.4 on 2021-06-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_selection', '0003_auto_20160522_0831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataselectiongroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dataselectiongroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='DataSelection',
        ),
        migrations.DeleteModel(
            name='DataSelectionGroup',
        ),
    ]
