# Generated by Django 3.2.4 on 2021-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_selection', '0005_create_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataselection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
