from .tag import *
from .aia_level_1 import *
from .aia_level_2 import *
from .chromis import *
from .chrotel_level_1 import *
from .crisp import *
from .eit_level_0 import *
from .eit_synoptic import *
from .eui_level_1 import *
from .eui_level_2 import *
from .euvi_level_0 import *
from .gaia_dem import *
from .gris_level_1 import *
from .hmi_magnetogram import *
from .hmi_magnetogram_level_1_5 import *
from .ibis import *
from .lars_level_1 import *
from .lyra_level_2 import *
from .lyra_level_3 import *
from .rosa import *
from .swap_level_1 import *
from .uset_calciumii_k_level_1 import *
from .uset_white_light_level_1 import *
from .xrt import *
