# Generated by command write_metadata_files version 2
from metadata.models import AiaLevel15
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['AiaLevel15Admin']


@admin.register(AiaLevel15)
class AiaLevel15Admin(BaseMetadataAdmin):
	readonly_fields = ['crota2','crpix1','crpix2','crval1','crval2','ctype1','ctype2','cunit1','cunit2','dsun_ref','gcount','lvl_num','naxis','naxis1','naxis2','origin','pcount','rsun_ref','telescop','totvals','trecepoc','trecstep','waveunit',]

	def get_list_filter(self, request):
		return list(super().get_list_filter(request)) + ['wavelnth']

	def get_list_display(self, request):
		return list(super().get_list_display(request)) + ['wavelnth']