# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import AiaLevel15
from .base_metadata import BaseMetadataAdmin

__all__ = ['AiaLevel15Admin']

@admin.register(AiaLevel15)
class AiaLevel15Admin(BaseMetadataAdmin):
	pass
