# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import AiaLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['AiaLevel1Admin']

@admin.register(AiaLevel1)
class AiaLevel1Admin(BaseMetadataAdmin):
	list_filter = BaseMetadataAdmin.list_filter + ['wavelnth']
	list_display = BaseMetadataAdmin.list_display + ['wavelnth']
