# Generated by command write_metadata_files version 2
from metadata.models import AiaLevel2
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['AiaLevel2Admin']


@admin.register(AiaLevel2)
class AiaLevel2Admin(BaseMetadataAdmin):
	readonly_fields = ['acs_cgt','acs_mode','cdelt1','cdelt2','crval1','crval2','ctype1','ctype2','cunit1','cunit2','dsun_ref','exptime','img_type','ispsname','keywddoc','lvl_num','origin','pc1_1','pc2_2','pixlunit','roi_llx1','roi_llx2','roi_lly1','roi_lly2','roi_nax1','roi_nax2','roi_nay1','roi_nay2','roi_sum','rsun_ref','segment','series','slotnum','telescop','waveunit',]
