# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import AspiicsLevel3
from .base_metadata import BaseMetadataAdmin

__all__ = ['AspiicsLevel3Admin']

@admin.register(AspiicsLevel3)
class AspiicsLevel3Admin(BaseMetadataAdmin):
	pass
