# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import AspiicsLevel2
from .base_metadata import BaseMetadataAdmin

__all__ = ['AspiicsLevel2Admin']

@admin.register(AspiicsLevel2)
class AspiicsLevel2Admin(BaseMetadataAdmin):
	pass
