# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import ChrotelLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['ChrotelLevel1Admin']

@admin.register(ChrotelLevel1)
class ChrotelLevel1Admin(BaseMetadataAdmin):
	pass
