# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import Chrotel
from .base_metadata import BaseMetadataAdmin

__all__ = ['ChrotelAdmin']

@admin.register(Chrotel)
class ChrotelAdmin(BaseMetadataAdmin):
	list_filter = BaseMetadataAdmin.list_filter + ['wavelnth']
	list_display = BaseMetadataAdmin.list_display + ['wavelnth']
