# Generated by command write_metadata_files version 2
from metadata.models import Co5BoldIrsol
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['Co5BoldIrsolAdmin']


@admin.register(Co5BoldIrsol)
class Co5BoldIrsolAdmin(BaseMetadataAdmin):
	readonly_fields = []
