# Generated by command write_metadata_files version 2
from metadata.models import CompSLevel1
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['CompSLevel1Admin']


@admin.register(CompSLevel1)
class CompSLevel1Admin(BaseMetadataAdmin):
	readonly_fields = []
