# Generated by command write_metadata_files version 1
from metadata.models import Crisp
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['CrispAdmin']


@admin.register(Crisp)
class CrispAdmin(BaseMetadataAdmin):
	pass
