# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import Crisp
from .base_metadata import BaseMetadataAdmin

__all__ = ['CrispAdmin']

@admin.register(Crisp)
class CrispAdmin(BaseMetadataAdmin):
	pass
