# Generated by command write_metadata_files version 1
from metadata.models import Crisp2
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['Crisp2Admin']


@admin.register(Crisp2)
class Crisp2Admin(BaseMetadataAdmin):
	pass
