# Generated by command write_metadata_files version 1
from metadata.models import EitSynoptic
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EitSynopticAdmin']


@admin.register(EitSynoptic)
class EitSynopticAdmin(BaseMetadataAdmin):
	pass
