# Generated by command write_metadata_files version 1
from metadata.models import EitLevel0
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EitLevel0Admin']


@admin.register(EitLevel0)
class EitLevel0Admin(BaseMetadataAdmin):
	def get_list_filter(self, request):
		return list(super().get_list_filter(request)) + ['wavelnth']

	def get_list_display(self, request):
		return list(super().get_list_display(request)) + ['wavelnth']
