# Generated by command write_metadata_files version 2
from metadata.models import EitSynoptic
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EitSynopticAdmin']


@admin.register(EitSynoptic)
class EitSynopticAdmin(BaseMetadataAdmin):
	readonly_fields = ['access_estsize','access_format','bib_reference','c1_resol_max','c1_resol_min','c1max','c1min','c2_resol_max','c2_resol_min','c2max','c2min','c3max','c3min','dataproduct_type','granule_gid','instrument_host_name','instrument_name','map_height','map_projection','map_width','measurement_type','messenger','processing_level','producer_institute','producer_name','publisher','service_title','spatial_coordinate_description','spatial_frame_type','spectral_range_max','spectral_range_min','target_class','target_name','time_sampling_step_max','time_sampling_step_min',]
