# Generated by command write_metadata_files version 1
from django.contrib import admin

from metadata.models import EitSynoptic
from .base_metadata import BaseMetadataAdmin

__all__ = ['EitSynopticAdmin']

@admin.register(EitSynoptic)
class EitSynopticAdmin(BaseMetadataAdmin):
	pass
