# Generated by command write_metadata_files version 2
from metadata.models import EitLevel0
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EitLevel0Admin']


@admin.register(EitLevel0)
class EitLevel0Admin(BaseMetadataAdmin):
	readonly_fields = ['datasrc','filter','image_of_seq','instrume','leb_proc','line_sync','origin','telescop',]

	def get_list_filter(self, request):
		return list(super().get_list_filter(request)) + ['wavelnth']

	def get_list_display(self, request):
		return list(super().get_list_display(request)) + ['wavelnth']
