# Generated by command write_metadata_files version 1
from metadata.models import EuiLevel2
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EuiLevel2Admin']


@admin.register(EuiLevel2)
class EuiLevel2Admin(BaseMetadataAdmin):
	def get_list_filter(self, request):
		return list(super().get_list_filter(request)) + ['detector', 'wavelnth']

	def get_list_display(self, request):
		return list(super().get_list_display(request)) + ['detector', 'wavelnth']
