# Generated by command write_metadata_files version 1
from metadata.models import EuiLevel1
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EuiLevel1Admin']


@admin.register(EuiLevel1)
class EuiLevel1Admin(BaseMetadataAdmin):
	def get_list_filter(self, request):
		return list(super().get_list_filter(request)) + ['detector', 'wavelnth']

	def get_list_display(self, request):
		return list(super().get_list_display(request)) + ['detector', 'wavelnth']
