# Generated by command write_metadata_files version 1
from django.contrib import admin

from metadata.models import EuiLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['EuiLevel1Admin']

@admin.register(EuiLevel1)
class EuiLevel1Admin(BaseMetadataAdmin):
	pass
