# Generated by command write_metadata_files version 2
from metadata.models import EuviLevel0
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EuviLevel0Admin']


@admin.register(EuviLevel0)
class EuviLevel0Admin(BaseMetadataAdmin):
	readonly_fields = ['blank','bscale','bunit','bzero','calfac','cam_stat','ccdsum','ceb_stat','clr_tbl','cosmics','critevt','crval1','crval2','ctype1','ctype1a','ctype2','ctype2a','cunit1','cunit1a','cunit2','cunit2a','detector','gaincmd','gainmode','instrume','ledcolor','ledpulse','lonpole','naxis','object','observer','obt_time','offset','offsetcr','origin','polar','pv2_1','pv2_1a','sumcol','sumrow','telescop','tempthrm',]
