# Generated by command write_metadata_files version 1
from metadata.models import EuviLevel0
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['EuviLevel0Admin']


@admin.register(EuviLevel0)
class EuviLevel0Admin(BaseMetadataAdmin):
	pass
