# Generated by command write_metadata_files version 1
from django.contrib import admin

from metadata.models import GrisLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['GrisLevel1Admin']

@admin.register(GrisLevel1)
class GrisLevel1Admin(BaseMetadataAdmin):
	list_display = BaseMetadataAdmin.list_display + ['waveleng']
