# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import HmiMagnetogram
from .base_metadata import BaseMetadataAdmin

__all__ = ['HmiMagnetogramAdmin']

@admin.register(HmiMagnetogram)
class HmiMagnetogramAdmin(BaseMetadataAdmin):
	pass
