# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import Ibis
from .base_metadata import BaseMetadataAdmin

__all__ = ['IbisAdmin']

@admin.register(Ibis)
class IbisAdmin(BaseMetadataAdmin):
	list_filter = BaseMetadataAdmin.list_filter + ['channel']
	list_display = BaseMetadataAdmin.list_display + ['channel']
