# Generated by command write_metadata_files version 2
from metadata.models import IbisLevel2
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['IbisLevel2Admin']


@admin.register(IbisLevel2)
class IbisLevel2Admin(BaseMetadataAdmin):
	readonly_fields = []
