# Generated by command write_metadata_files version 2
from metadata.models import LsoCompSLevel1
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['LsoCompSLevel1Admin']


@admin.register(LsoCompSLevel1)
class LsoCompSLevel1Admin(BaseMetadataAdmin):
	readonly_fields = []
