# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import LyraLevel3
from .base_metadata import BaseMetadataAdmin

__all__ = ['LyraLevel3Admin']

@admin.register(LyraLevel3)
class LyraLevel3Admin(BaseMetadataAdmin):
	pass
