# Generated by command write_metadata_files version 1
from django.contrib import admin

from metadata.models import LyraLevel2
from .base_metadata import BaseMetadataAdmin

__all__ = ['LyraLevel2Admin']

@admin.register(LyraLevel2)
class LyraLevel2Admin(BaseMetadataAdmin):
	pass
