# Generated by command write_metadata_files version 1
from metadata.models import SpocaCoronalHole
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['SpocaCoronalHoleAdmin']


@admin.register(SpocaCoronalHole)
class SpocaCoronalHoleAdmin(BaseMetadataAdmin):
	pass
