# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import SpocaCoronalHole
from .base_metadata import BaseMetadataAdmin

__all__ = ['SpocaCoronalHoleAdmin']

@admin.register(SpocaCoronalHole)
class SpocaCoronalHoleAdmin(BaseMetadataAdmin):
	pass
