# Generated by command write_metadata_files version 2
from metadata.models import SwapLevel1
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['SwapLevel1Admin']


@admin.register(SwapLevel1)
class SwapLevel1Admin(BaseMetadataAdmin):
	readonly_fields = ['bunit','cd1_1','cd1_2','cd2_1','cd2_2','cdelt1','cdelt2','crota1','crota2','crval1','crval2','ctype1','ctype2','cunit1','cunit2','detector','filter','instrume','level','lonpole','naxis','naxis1','naxis2','object','origin','telescop','wavelnth','wcsname',]
