# Generated by command write_metadata_files version 1
from django.contrib import admin

from metadata.models import SwapLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['SwapLevel1Admin']

@admin.register(SwapLevel1)
class SwapLevel1Admin(BaseMetadataAdmin):
	pass
