# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import Themis
from .base_metadata import BaseMetadataAdmin

__all__ = ['ThemisAdmin']

@admin.register(Themis)
class ThemisAdmin(BaseMetadataAdmin):
	pass
