# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import UsetWhiteLightLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['UsetWhiteLightLevel1Admin']

@admin.register(UsetWhiteLightLevel1)
class UsetWhiteLightLevel1Admin(BaseMetadataAdmin):
	pass
