# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import UsetHAlphaLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['UsetHAlphaLevel1Admin']

@admin.register(UsetHAlphaLevel1)
class UsetHAlphaLevel1Admin(BaseMetadataAdmin):
	pass
