# Generated by command write_metadata_files version 1
from django.contrib import admin

from metadata.models import UsetCalciumiiKLevel1
from .base_metadata import BaseMetadataAdmin

__all__ = ['UsetCalciumiiKLevel1Admin']

@admin.register(UsetCalciumiiKLevel1)
class UsetCalciumiiKLevel1Admin(BaseMetadataAdmin):
	pass
