# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import Xrt
from .base_metadata import BaseMetadataAdmin

__all__ = ['XrtAdmin']

@admin.register(Xrt)
class XrtAdmin(BaseMetadataAdmin):
	list_filter = BaseMetadataAdmin.list_filter + ["target"]
	list_display = BaseMetadataAdmin.list_display + ["target", "noaa_num"]
