# Generated by command write_metadata_files version 2
from metadata.models import XrtLevel1
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['XrtLevel1Admin']


@admin.register(XrtLevel1)
class XrtLevel1Admin(BaseMetadataAdmin):
	readonly_fields = ['achf_ver','bitc_ver','bitcomp1','ctype1','ctype2','cunit1','cunit2','data_lev','datatype','e_etim','e_sh_ccw','e_sh_cw','e_sh_err','e_sh_wa','e_sh_wb','e_sh_wc','e_ttn','ec_cd_mo_name','ec_imtyp','ec_imtyp_name','effport','exccdex','instrume','jop_id','naxis','rsun_ref','s_dat_id','s_instru','satellit','telescop','timesys',]
