# Generated by command write_metadata_files version 1
from metadata.models import XrtLevel1
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['XrtLevel1Admin']


@admin.register(XrtLevel1)
class XrtLevel1Admin(BaseMetadataAdmin):
	pass
