# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import XrtLevel0
from .base_metadata import BaseMetadataAdmin

__all__ = ['XrtLevel0Admin']

@admin.register(XrtLevel0)
class XrtLevel0Admin(BaseMetadataAdmin):
	pass
