# Generated by command write_metadata_files version 1
from metadata.models import ZimpolSpectrographGregor
from project import admin

from .base_metadata import BaseMetadataAdmin

__all__ = ['ZimpolSpectrographGregorAdmin']


@admin.register(ZimpolSpectrographGregor)
class ZimpolSpectrographGregorAdmin(BaseMetadataAdmin):
	pass
