# Generated by command write_metadata_files version 1
from project import admin
from metadata.models import ZimpolSpectrographIrsol
from .base_metadata import BaseMetadataAdmin

__all__ = ['ZimpolSpectrographIrsolAdmin']

@admin.register(ZimpolSpectrographIrsol)
class ZimpolSpectrographIrsolAdmin(BaseMetadataAdmin):
	pass
