# Generated by command write_metadata_files version 1
from metadata.models import AiaLevel2
from .base_metadata import BaseMetadataResource

__all__ = ['AiaLevel2Resource']


class AiaLevel2Resource(BaseMetadataResource):
	'''RESTful resource for model AiaLevel2'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = AiaLevel2.objects.all()
		resource_name = 'metadata_aia_level_2'
