# Generated by command write_metadata_files version 2
import datetime

from tastypie import fields

from metadata.models import AiaLevel2

from .base_metadata import BaseMetadataResource

__all__ = ['AiaLevel2Resource']


class AiaLevel2Resource(BaseMetadataResource):
	'''RESTful resource for model AiaLevel2'''
	
	# Fields for keywords with constant_value and that don't have a corresponding model field/database column
	acs_cgt = fields.CharField(default='GT3', null=True, blank=True, readonly=True, help_text='ACS ID of Controlling Guide Telescope - ACS_AN_NUM_CGT')
	acs_mode = fields.CharField(default='SCIENCE', null=True, blank=True, readonly=True, help_text='ACS pointing mode - ACS_AN_ACS_MODE')
	cdelt1 = fields.FloatField(default=0.6, null=True, blank=True, readonly=True, help_text='CDELT1: image scale in the x direction')
	cdelt2 = fields.FloatField(default=0.6, null=True, blank=True, readonly=True, help_text='CDELT2: image scale in the y direction')
	crval1 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='CRVAL1: image scale in the x direction')
	crval2 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='CRVAL2: image scale in the x direction')
	ctype1 = fields.CharField(default='HPLN-TAN', null=True, blank=True, readonly=True, help_text='CTYPE1; Typically HPLN-TAN (SOLARX)')
	ctype2 = fields.CharField(default='HPLT-TAN', null=True, blank=True, readonly=True, help_text='CTYPE2; Typically HPLT-TAN (SOLARY)')
	cunit1 = fields.CharField(default='arcsec', null=True, blank=True, readonly=True, help_text='CUNIT1; Typically arcsec')
	cunit2 = fields.CharField(default='arcsec', null=True, blank=True, readonly=True, help_text='CUNIT2; Typically arcsec')
	dsun_ref = fields.FloatField(default=149597870691.0, null=True, blank=True, readonly=True, help_text='Reference distance to Sun: 149,597,870,691.0 m')
	exptime = fields.FloatField(default=1.0, null=True, blank=True, readonly=True, help_text='Exposure duration: mean shutter open time')
	img_type = fields.CharField(default='LIGHT', null=True, blank=True, readonly=True, help_text='Image type: LIGHT or DARK')
	ispsname = fields.CharField(default='aia.lev0_isp_0011', null=True, blank=True, readonly=True, help_text='ISP SERIES NAME')
	keywddoc = fields.CharField(default='http://www.lmsal.com/sdodocs/aiafitskeywords.pdf', null=True, blank=True, readonly=True, help_text='AIA FITS keyword documentation')
	lvl_num = fields.FloatField(default=2.0, null=True, blank=True, readonly=True, help_text='LVL_NUM data level number')
	origin = fields.CharField(default='SDO/JSOC-SDP', null=True, blank=True, readonly=True, help_text='ORIGIN Location where file made')
	pc1_1 = fields.FloatField(default=1.0, null=True, blank=True, readonly=True, help_text='')
	pc2_2 = fields.FloatField(default=1.0, null=True, blank=True, readonly=True, help_text='')
	pixlunit = fields.CharField(default='DN/s', null=True, blank=True, readonly=True, help_text='Pixel intensity unit')
	roi_llx1 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='CCD X location of lower left corner of ROI1')
	roi_llx2 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='CCD X location of lower left corner of ROI2')
	roi_lly1 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='CCD Y location of lower left corner of ROI1')
	roi_lly2 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='CCD Y location of lower left corner of ROI2')
	roi_nax1 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='Number of CCD columns for width of ROI1')
	roi_nax2 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='Number of CCD columns for width of ROI2')
	roi_nay1 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='Number of CCD rows for height of ROI1')
	roi_nay2 = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='Number of CCD rows for height of ROI2')
	roi_sum = fields.IntegerField(default=-2147483648, null=True, blank=True, readonly=True, help_text='Summing Mode: 1x1, 2x2, 4x4 (0,1,2)')
	rsun_ref = fields.FloatField(default=696000000.0, null=True, blank=True, readonly=True, help_text='Reference radius of the Sun: 696,000,000.0 m')
	segment = fields.CharField(default='image_lev1.fits', null=True, blank=True, readonly=True, help_text='JSOC Segment File Name')
	series = fields.CharField(default='aia.lev1', null=True, blank=True, readonly=True, help_text='JSOC Series Name')
	slotnum = fields.IntegerField(default=0, null=True, blank=True, readonly=True, help_text='JSOC Slot Number')
	telescop = fields.CharField(default='SDO/AIA', null=True, blank=True, readonly=True, help_text='For AIA: SDO/AIA')
	waveunit = fields.CharField(default='angstrom', null=True, blank=True, readonly=True, help_text='Wavelength unit: angstrom')
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = AiaLevel2.objects.all()
		resource_name = 'metadata_aia_level_2'
