# Generated by command write_metadata_files version 1
from metadata.models import AspiicsLevel3
from .base_metadata import BaseMetadataResource

__all__ = ['AspiicsLevel3Resource']


class AspiicsLevel3Resource(BaseMetadataResource):
	'''RESTful resource for model AspiicsLevel3'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = AspiicsLevel3.objects.all()
		resource_name = 'metadata_aspiics_level_3'
