# Generated by command write_metadata_files version 1
from metadata.models import Chrotel
from .base_metadata import BaseMetadataResource

__all__ = ['ChrotelResource']


class ChrotelResource(BaseMetadataResource):
	'''RESTful resource for model Chrotel'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = Chrotel.objects.all()
		resource_name = 'chrotel'
