# Generated by command write_metadata_files version 2
import datetime

from tastypie import fields

from metadata.models import Co5BoldIrsol

from .base_metadata import BaseMetadataResource

__all__ = ['Co5BoldIrsolResource']


class Co5BoldIrsolResource(BaseMetadataResource):
	'''RESTful resource for model Co5BoldIrsol'''
	
	# Fields for keywords with constant_value and that don't have a corresponding model field/database column
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = Co5BoldIrsol.objects.all()
		resource_name = 'metadata_co5bold_irsol'
