# Generated by command write_metadata_files version 2
from metadata.models import CompSLevel1

from .base_metadata import BaseMetadataResource

__all__ = ['CompSLevel1Resource']


class CompSLevel1Resource(BaseMetadataResource):
	"""RESTful resource for model CompSLevel1"""

	# Fields for keywords with constant_value and that don't have a corresponding model field/database column

	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = CompSLevel1.objects.all()
		resource_name = 'metadata_comp_s_level_1'
