# Generated by command write_metadata_files version 1
from metadata.models import Crisp
from .base_metadata import BaseMetadataResource

__all__ = ['CrispResource']


class CrispResource(BaseMetadataResource):
	'''RESTful resource for model Crisp'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = Crisp.objects.all()
		resource_name = 'crisp'
