# Generated by command write_metadata_files version 1
from metadata.models import Crisp2

from .base_metadata import BaseMetadataResource

__all__ = ['Crisp2Resource']


class Crisp2Resource(BaseMetadataResource):
	"""RESTful resource for model Crisp2"""

	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = Crisp2.objects.all()
		resource_name = 'metadata_crisp2'
