# Generated by command write_metadata_files version 1
from metadata.models import EuiLevel1
from .base_metadata import BaseMetadataResource

__all__ = ['EuiLevel1Resource']


class EuiLevel1Resource(BaseMetadataResource):
	'''RESTful resource for model EuiLevel1'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = EuiLevel1.objects.all()
		resource_name = 'metadata_eui_level_1'
