# Generated by command write_metadata_files version 1
from metadata.models import EuiLevel2
from .base_metadata import BaseMetadataResource

__all__ = ['EuiLevel2Resource']


class EuiLevel2Resource(BaseMetadataResource):
	'''RESTful resource for model EuiLevel2'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = EuiLevel2.objects.all()
		resource_name = 'metadata_eui_level_2'
