# Generated by command write_metadata_files version 2
import datetime

from tastypie import fields

from metadata.models import EuviLevel0

from .base_metadata import BaseMetadataResource

__all__ = ['EuviLevel0Resource']


class EuviLevel0Resource(BaseMetadataResource):
	'''RESTful resource for model EuviLevel0'''
	
	# Fields for keywords with constant_value and that don't have a corresponding model field/database column
	blank = fields.IntegerField(default=0, null=True, blank=True, readonly=True, help_text='FITS standard for UINT')
	bscale = fields.FloatField(default=1.0, null=True, blank=True, readonly=True, help_text='')
	bunit = fields.CharField(default='DN', null=True, blank=True, readonly=True, help_text='')
	bzero = fields.IntegerField(default=32768, null=True, blank=True, readonly=True, help_text='Data is Unsigned Integer')
	calfac = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='')
	cam_stat = fields.IntegerField(default=1, null=True, blank=True, readonly=True, help_text='CAMERA_READY')
	ccdsum = fields.FloatField(default=1.0, null=True, blank=True, readonly=True, help_text='')
	ceb_stat = fields.IntegerField(default=0, null=True, blank=True, readonly=True, help_text='SUCCESSFUL_RESPONSE')
	clr_tbl = fields.IntegerField(default=1, null=True, blank=True, readonly=True, help_text='')
	cosmics = fields.IntegerField(default=0, null=True, blank=True, readonly=True, help_text='')
	critevt = fields.CharField(default='0xF000', null=True, blank=True, readonly=True, help_text='')
	crval1 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='')
	crval2 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='')
	ctype1 = fields.CharField(default='HPLN-TAN', null=True, blank=True, readonly=True, help_text='')
	ctype1a = fields.CharField(default='RA---TAN', null=True, blank=True, readonly=True, help_text='')
	ctype2 = fields.CharField(default='HPLT-TAN', null=True, blank=True, readonly=True, help_text='')
	ctype2a = fields.CharField(default='DEC--TAN', null=True, blank=True, readonly=True, help_text='')
	cunit1 = fields.CharField(default='arcsec', null=True, blank=True, readonly=True, help_text='')
	cunit1a = fields.CharField(default='deg', null=True, blank=True, readonly=True, help_text='')
	cunit2 = fields.CharField(default='arcsec', null=True, blank=True, readonly=True, help_text='')
	cunit2a = fields.CharField(default='deg', null=True, blank=True, readonly=True, help_text='')
	detector = fields.CharField(default='EUVI', null=True, blank=True, readonly=True, help_text='')
	gaincmd = fields.IntegerField(default=1, null=True, blank=True, readonly=True, help_text='')
	gainmode = fields.CharField(default='HIGH', null=True, blank=True, readonly=True, help_text='')
	instrume = fields.CharField(default='SECCHI', null=True, blank=True, readonly=True, help_text='')
	ledcolor = fields.CharField(default='NONE', null=True, blank=True, readonly=True, help_text='')
	ledpulse = fields.IntegerField(default=0, null=True, blank=True, readonly=True, help_text='')
	lonpole = fields.IntegerField(default=180, null=True, blank=True, readonly=True, help_text='')
	naxis = fields.IntegerField(default=2, null=True, blank=True, readonly=True, help_text='')
	object = fields.CharField(default='', null=True, blank=True, readonly=True, help_text='')
	observer = fields.CharField(default='', null=True, blank=True, readonly=True, help_text='')
	obt_time = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='')
	offset = fields.IntegerField(default=600, null=True, blank=True, readonly=True, help_text='')
	offsetcr = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='')
	origin = fields.CharField(default='NRL', null=True, blank=True, readonly=True, help_text='')
	polar = fields.FloatField(default=-1.0, null=True, blank=True, readonly=True, help_text='')
	pv2_1 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='')
	pv2_1a = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='')
	sumcol = fields.IntegerField(default=1, null=True, blank=True, readonly=True, help_text='')
	sumrow = fields.IntegerField(default=1, null=True, blank=True, readonly=True, help_text='')
	telescop = fields.CharField(default='STEREO', null=True, blank=True, readonly=True, help_text='')
	tempthrm = fields.FloatField(default=9999.0, null=True, blank=True, readonly=True, help_text='')
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = EuviLevel0.objects.all()
		resource_name = 'metadata_euvi_level_0'
