# Generated by command write_metadata_files version 1
from metadata.models import EuviLevel0
from .base_metadata import BaseMetadataResource

__all__ = ['EuviLevel0Resource']


class EuviLevel0Resource(BaseMetadataResource):
	'''RESTful resource for model EuviLevel0'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = EuviLevel0.objects.all()
		resource_name = 'metadata_euvi_level_0'
