# Generated by command write_metadata_files version 1
from metadata.models import GaiaDem
from .base_metadata import BaseMetadataResource

__all__ = ['GaiaDemResource']


class GaiaDemResource(BaseMetadataResource):
	'''RESTful resource for model GaiaDem'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = GaiaDem.objects.all()
		resource_name = 'metadata_gaia_dem'
