# Generated by command write_metadata_files version 1
from metadata.models import GrisLevel1
from .base_metadata import BaseMetadataResource

__all__ = ['GrisLevel1Resource']


class GrisLevel1Resource(BaseMetadataResource):
	'''RESTful resource for model GrisLevel1'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = GrisLevel1.objects.all()
		resource_name = 'gris_level_1'
