# Generated by command write_metadata_files version 1
from metadata.models import HmiMagnetogram
from .base_metadata import BaseMetadataResource

__all__ = ['HmiMagnetogramResource']


class HmiMagnetogramResource(BaseMetadataResource):
	'''RESTful resource for model HmiMagnetogram'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = HmiMagnetogram.objects.all()
		resource_name = 'metadata_hmi_magnetogram'
