# Generated by command write_metadata_files version 1
from metadata.models import HmiMagnetogramLevel15
from .base_metadata import BaseMetadataResource

__all__ = ['HmiMagnetogramLevel15Resource']


class HmiMagnetogramLevel15Resource(BaseMetadataResource):
	'''RESTful resource for model HmiMagnetogramLevel15'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = HmiMagnetogramLevel15.objects.all()
		resource_name = 'metadata_hmi_magnetogram_level_1_5'
