# Generated by command write_metadata_files version 2
import datetime

from tastypie import fields

from metadata.models import IbisLevel2

from .base_metadata import BaseMetadataResource

__all__ = ['IbisLevel2Resource']


class IbisLevel2Resource(BaseMetadataResource):
	'''RESTful resource for model IbisLevel2'''
	
	# Fields for keywords with constant_value and that don't have a corresponding model field/database column
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = IbisLevel2.objects.all()
		resource_name = 'metadata_ibis_level_2'
