# Generated by command write_metadata_files version 1
from metadata.models import LarsLevel1
from .base_metadata import BaseMetadataResource

__all__ = ['LarsLevel1Resource']


class LarsLevel1Resource(BaseMetadataResource):
	'''RESTful resource for model LarsLevel1'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = LarsLevel1.objects.all()
		resource_name = 'metadata_lars_level_1'
