# Generated by command write_metadata_files version 1
from metadata.models import LyraLevel3
from .base_metadata import BaseMetadataResource

__all__ = ['LyraLevel3Resource']


class LyraLevel3Resource(BaseMetadataResource):
	'''RESTful resource for model LyraLevel3'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = LyraLevel3.objects.all()
		resource_name = 'metadata_lyra_level_3'
