# Generated by command write_metadata_files version 1
from metadata.models import LyraLevel2
from .base_metadata import BaseMetadataResource

__all__ = ['LyraLevel2Resource']


class LyraLevel2Resource(BaseMetadataResource):
	'''RESTful resource for model LyraLevel2'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = LyraLevel2.objects.all()
		resource_name = 'metadata_lyra_level_2'
