# Generated by command write_metadata_files version 1
from metadata.models import SpocaCoronalHole
from .base_metadata import BaseMetadataResource

__all__ = ['SpocaCoronalHoleResource']


class SpocaCoronalHoleResource(BaseMetadataResource):
	'''RESTful resource for model SpocaCoronalHole'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = SpocaCoronalHole.objects.all()
		resource_name = 'metadata_spoca_coronal_hole'
