# Generated by command write_metadata_files version 2
import datetime

from tastypie import fields

from metadata.models import SwapLevel1

from .base_metadata import BaseMetadataResource

__all__ = ['SwapLevel1Resource']


class SwapLevel1Resource(BaseMetadataResource):
	'''RESTful resource for model SwapLevel1'''
	
	# Fields for keywords with constant_value and that don't have a corresponding model field/database column
	bunit = fields.CharField(default='DN/s', null=True, blank=True, readonly=True, help_text='unit of physical value')
	cd1_1 = fields.FloatField(default=3.1646941, null=True, blank=True, readonly=True, help_text='WCS coordinate description matrix')
	cd1_2 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='WCS coordinate description matrix')
	cd2_1 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='WCS coordinate description matrix')
	cd2_2 = fields.FloatField(default=3.1646941, null=True, blank=True, readonly=True, help_text='WCS coordinate description matrix')
	cdelt1 = fields.FloatField(default=3.1646941, null=True, blank=True, readonly=True, help_text='average pixel scale along axis 1')
	cdelt2 = fields.FloatField(default=3.1646941, null=True, blank=True, readonly=True, help_text='average pixel scale along axis 2')
	crota1 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='axis 1 to WCS rotation angle')
	crota2 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='axis 2 to WCS rotation angle')
	crval1 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='reference point WCS axis X')
	crval2 = fields.FloatField(default=0.0, null=True, blank=True, readonly=True, help_text='reference point WCS axis Y')
	ctype1 = fields.CharField(default='HPLN-TAN', null=True, blank=True, readonly=True, help_text='WCS axis X')
	ctype2 = fields.CharField(default='HPLT-TAN', null=True, blank=True, readonly=True, help_text='WCS axis Y')
	cunit1 = fields.CharField(default='arcsec', null=True, blank=True, readonly=True, help_text='WCS axis X units')
	cunit2 = fields.CharField(default='arcsec', null=True, blank=True, readonly=True, help_text='WCS axis Y units')
	detector = fields.CharField(default='SWAP', null=True, blank=True, readonly=True, help_text='HAS CMOS detector 1024x1024 pixels')
	filter = fields.CharField(default='Al', null=True, blank=True, readonly=True, help_text='Aluminum filter')
	instrume = fields.CharField(default='SWAP', null=True, blank=True, readonly=True, help_text='instrument name')
	level = fields.IntegerField(default=1, null=True, blank=True, readonly=True, help_text='data processing level')
	lonpole = fields.FloatField(default=180.0, null=True, blank=True, readonly=True, help_text='native longitude of the celestial pole')
	naxis = fields.IntegerField(default=2, null=True, blank=True, readonly=True, help_text='number of data axes')
	naxis1 = fields.IntegerField(default=1024, null=True, blank=True, readonly=True, help_text='length of data axis 1')
	naxis2 = fields.IntegerField(default=1024, null=True, blank=True, readonly=True, help_text='length of data axis 2')
	object = fields.CharField(default='Sun EUV', null=True, blank=True, readonly=True, help_text='object observed')
	origin = fields.CharField(default='ROB', null=True, blank=True, readonly=True, help_text='Royal Observatory of Belgium')
	telescop = fields.CharField(default='PROBA2', null=True, blank=True, readonly=True, help_text='satellite name')
	wavelnth = fields.IntegerField(default=174, null=True, blank=True, readonly=True, help_text='bandpass peak response')
	wcsname = fields.CharField(default='Helioprojective-cartesian', null=True, blank=True, readonly=True, help_text='aligned with solar North')
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = SwapLevel1.objects.all()
		resource_name = 'metadata_swap_level_1'
