# Generated by command write_metadata_files version 1
from metadata.models import SwapLevel1
from .base_metadata import BaseMetadataResource

__all__ = ['SwapLevel1Resource']


class SwapLevel1Resource(BaseMetadataResource):
	'''RESTful resource for model SwapLevel1'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = SwapLevel1.objects.all()
		resource_name = 'metadata_swap_level_1'
