# Generated by command write_metadata_files version 1
from metadata.models import Themis
from .base_metadata import BaseMetadataResource

__all__ = ['ThemisResource']


class ThemisResource(BaseMetadataResource):
	'''RESTful resource for model Themis'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = Themis.objects.all()
		resource_name = 'metadata_themis'
