# Generated by command write_metadata_files version 1
from metadata.models import UsetHAlphaLevel1
from .base_metadata import BaseMetadataResource

__all__ = ['UsetHAlphaLevel1Resource']


class UsetHAlphaLevel1Resource(BaseMetadataResource):
	'''RESTful resource for model UsetHAlphaLevel1'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = UsetHAlphaLevel1.objects.all()
		resource_name = 'metadata_uset_h_alpha_level_1'
