# Generated by command write_metadata_files version 1
from metadata.models import Xrt
from .base_metadata import BaseMetadataResource

__all__ = ['XrtResource']


class XrtResource(BaseMetadataResource):
	'''RESTful resource for model Xrt'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = Xrt.objects.all()
		resource_name = 'metadata_xrt'
