# Generated by command write_metadata_files version 1
from metadata.models import XrtLevel0
from .base_metadata import BaseMetadataResource

__all__ = ['XrtLevel0Resource']


class XrtLevel0Resource(BaseMetadataResource):
	"""RESTful resource for model XrtLevel0"""

	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = XrtLevel0.objects.all()
		resource_name = 'metadata_xrt_level_0'
