# Generated by command write_metadata_files version 1
from metadata.models import XrtLevel1
from .base_metadata import BaseMetadataResource

__all__ = ['XrtLevel1Resource']


class XrtLevel1Resource(BaseMetadataResource):
	"""RESTful resource for model XrtLevel1"""

	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = XrtLevel1.objects.all()
		resource_name = 'metadata_xrt_level_1'
