# Generated by command write_metadata_files version 1
from metadata.models import ZimpolSpectrographIrsol
from .base_metadata import BaseMetadataResource

__all__ = ['ZimpolSpectrographIrsolResource']


class ZimpolSpectrographIrsolResource(BaseMetadataResource):
	'''RESTful resource for model ZimpolSpectrographIrsol'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = ZimpolSpectrographIrsol.objects.all()
		resource_name = 'metadata_zimpol_spectrograph_irsol'
