# Generated by command write_metadata_files version 1
from metadata.models import ZimpolSpectrographGregor
from .base_metadata import BaseMetadataResource

__all__ = ['ZimpolSpectrographGregorResource']


class ZimpolSpectrographGregorResource(BaseMetadataResource):
	'''RESTful resource for model ZimpolSpectrographGregor'''
	
	class Meta(BaseMetadataResource.Meta):
		abstract = False
		queryset = ZimpolSpectrographGregor.objects.all()
		resource_name = 'metadata_zimpol_spectrograph_gregor'
